### ISSUE TITLE
Implementing Multiscale Scene Parsing

### ISSUE THREAD

**Issue by BlGene** [BVLC/caffe#1041]
Hello All,

I have recently started working with on scene parsing, I choose to start by re-implementing the approach taken by [1] in caffe. The approach that they take to scene parsing is somewhat different from normal classification and thus requires some changes to caffe. I will outline how I plan to integrate these changes into caffe so that I can get feedback on how sensible these ideas are. The eventual aim is to have a branch with an example that can be merged into the main dev branch.

Problem 1) Dealing with multiple labels per image, heavily unbalanced class frequencies.

To solve this problem I have started writing a data sampler analogous to the data transformer. See  [here](https://github.com/BlGene/caffe/commit/b705fcb720bfccdffec6c5845f5d88e39a5be1f1) for details. It relies on a separate protobuffer file which specifies polygons for each label for each image and can sample random points from these.

Problem 2) Extracting multiscale patches

The approach relies on showing the convNet image patches at three different scales, running the same network on them and concatenating the output before doing a softmax. For this I plan to add a new method to the transformer class that takes as input the datum as well as the center around which we want to extract the patch, this method would then extract the patches of different scales and concatenate them again. In a splitting layer this datum could then be split. 

After these two issues are dealt with the convNet should be quite easy to specify using the protobuffer configuration.

As I am new to caffe and scene parsing any tips on how I  should implement this are appreciated. Is this design good? 

[1] Scene Parsing with Multiscale Feature Learning, Purity Trees, and Optimal Covers

**Comment by godprincelp** [comment]
Hi Bigene，

I am wondering if the project on Multiscale Scene Parsing is done or not.  Can you upload the code again?

Thank you.

**Comment by BlGene** [comment]
Have a look at [this](https://github.com/BlGene/caffe/tree/master_scene) code and this [net](https://gist.github.com/BlGene/d60b99a806425bbe4ed3#file-gistfile1-txt) (untested).

The branch may be a bit over engineered and under tested, but may be helpful depending on what you want to do.

To use it you need a  normal caffe DB with the label info in the last ( probably 4th) channel.

**Comment by godprincelp** [comment]
Thanks for sharing the code as well as the instructions.  I am trying to compile the code and will let you know if there is any questions.

**Comment by godprincelp** [comment]
Hi BIGene,

Can you share with me the caffe DB that you are using? I am trying so hard
to write the code for DB. But still cannot make it.

Thanks.

Peng Lei
leip@oregonstate.edu


On Thu, Sep 10, 2015 at 5:47 AM, BlGene <notifications@github.com> wrote:

> Have a look at this <https://github.com/BlGene/caffe/tree/master_scene>
> code and this net
> <https://gist.github.com/BlGene/d60b99a806425bbe4ed3#file-gistfile1-txt>
> (untested).
>
> The branch may be a bit over engineered and under tested, but may be
> helpful depending on what you want to do.
>
> To use it you need a normal caffe DB with the label info in the last (
> probably 4th) channel.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BVLC/caffe/issues/1041#issuecomment-139225150>.
>



-- 
Best Regards,
Peng Lei
------------------------------------------------
EECS, Oregon State University (OSU)
leip@onid.orst.edu
prcv.plei@gmail.com
1-541-737-7268

**Comment by godprincelp** [comment]
Hello BIGene,

Thanks for sharing the code.

I am writing to ask you for clarifications regarding the net script as well
as the caffe DB file.

1. For the DB, as for my understanding, the input are the original RGB
image (in jpg format) as well as the corresponding label (in pgm format).
Is that right?

2. It seems that you input the net with RGB images in different scales
instead of the normalized pyramid that has zero-mean and unit variance.  Am
I right? If not, could you please specify the file/code for preprocessing
steps (as depicted in Section 5.1 in [1], transformed RGB into LUV, built a
Laplacian pyramid and applied the normalization procedure)？

3. As defined in the net
<https://gist.github.com/BlGene/d60b99a806425bbe4ed3#file-gistfile1-txt>,
you applied the convolution kernels (with the same size) onto images in
different scales. How can you share the weights among the convolution
kernels?  Are you done with the weight sharing part?

4. For the net
<https://gist.github.com/BlGene/d60b99a806425bbe4ed3#file-gistfile1-txt>,
 in line 41, you wrote the following sentence:

specialization: { top_index: 3 crop_size:256 label:1 }

What is the meaning of "*label:1*"? Are you specifying the number of
channels in the label layer? I am begging your clarification.




On Thu, Sep 10, 2015 at 5:47 AM, BlGene <notifications@github.com> wrote:

> Have a look at this <https://github.com/BlGene/caffe/tree/master_scene>
> code and this net
> <https://gist.github.com/BlGene/d60b99a806425bbe4ed3#file-gistfile1-txt>
> (untested).
>
> The branch may be a bit over engineered and under tested, but may be
> helpful depending on what you want to do.
>
> To use it you need a normal caffe DB with the label info in the last (
> probably 4th) channel.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BVLC/caffe/issues/1041#issuecomment-139225150>.
>



-- 
Best Regards,
Peng Lei
------------------------------------------------
EECS, Oregon State University (OSU)
leip@onid.orst.edu
prcv.plei@gmail.com
1-541-737-7268

**Comment by BlGene** [comment]
1. Yes, but you should be able to change the script to whatever file encoding opencv can read.

2. Yes I use different scales, I do not do subtract the mean or shift the variance.

3. Weights are shared using the caffe's built in functionality for this, it is defined by:
  param { name: "conv1_w" }
  param { name: "conv1_b" }

4. label:1 means this specialization (i.e. top blob) should contain label information. Maybe it would be clearer if it were named something like output_labels:True. The by default the label information is the last channel of DB datums.

BR, Max

**Comment by hkcqr** [comment]
@BlGene  Hi, have you done any performance testing with your proposed model? I'm working on a similar project, if you have any progress, can we discuss it further ?
