### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by wuxinhong** [BVLC/caffe#1390]
$make runtest
F1101 15:30:32.729866  4032 math_functions.cu:81] Check failed: error == cudaSuccess (11 vs. 0)  invalid argument
make: *** [runtest] 已放弃 (core dumped)
what's wrong with it?

**Comment by pnambiar** [comment]
Did you find a solution. I have the same problem

**Comment by pannous** [comment]
search for causes and solution in the google group

**Comment by pnambiar** [comment]
I was able to find a thred with the same cause. But no solution :(

https://groups.google.com/forum/#!searchin/caffe-users/Check$20failed$3A$20error$20$3D$3D$20cudaSuccess$20%2811$20vs.$200%29$20$20invalid$20argument|sort:relevance/caffe-users/-XcvUmFGJco/7hljfiTRRkIJ

**Comment by pannous** [comment]
make sure cuda example deviceQuery works

if you have recent hardware check in CMakeLists.txt :
set(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS} -gencode arch=compute_50,code=sm_50   )
and in Makefile.config CUDA_ARCH := -gencode arch=compute_50,code=sm_50
(should be default now, but doublecheck)

**Comment by pannous** [comment]
one bizarre error we encountered is that you might have to run sudo deviceQuery before you can run deviceQuery as user

**Comment by pnambiar** [comment]
The deviceQuery work. Result attached

In Makefile.config , I have
CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
        -gencode arch=compute_20,code=sm_21 \
        -gencode arch=compute_30,code=sm_30 \
        -gencode arch=compute_35,code=sm_35 \
        -gencode arch=compute_50,code=sm_50 \
        -gencode arch=compute_50,code=compute_50

But I do not see  set(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS} -gencode
arch=compute_50,code=sm_50 )  in CMakeLists.txt.

Should I just add it anywhere in the code?


On Thu, Jan 8, 2015 at 9:54 AM, pannous <notifications@github.com> wrote:

> one bizarre error we encountered is that you might have to run sudo
> deviceQuery before you can run deviceQuery as user
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BVLC/caffe/issues/1390#issuecomment-69189406>.
>
cmake_minimum_required(VERSION 2.8.8)
project( Caffe )

###    Build Options     ##########################################################################

option(CPU_ONLY "Build Caffe without GPU support" OFF)
option(BUILD_PYTHON "Build Python wrapper" OFF)
option(BUILD_MATLAB "Build Matlab wrapper" OFF)
option(BUILD_EXAMPLES "Build examples" ON)
option(BUILD_SHARED_LIBS "Build SHARED libs if ON and STATIC otherwise" OFF)


if(NOT BLAS)
    set(BLAS atlas)
endif()

if(NOT CUDA_TEST_DEVICE)
    set(CUDA_TEST_DEVICE -1)
endif()

#    Install Prefix
if (CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
    set (CMAKE_INSTALL_PREFIX "${CMAKE_BINARY_DIR}/install" CACHE PATH "Default install path" FORCE )
endif()

###    Configuration    ###########################################################################
#    Compiler Flags
set(CMAKE_CXX_COMPILER_FLAGS ${CMAKE_CXX_COMPILER_FLAGS} -Wall)
set(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} -fPIC) # set global flags
set(CMAKE_CXX_FLAGS_DEBUG ${CMAKE_CXX_FLAGS_DEBUG}) # set debug flags
set(CMAKE_CXX_FLAGS_RELEASE ${CMAKE_CXX_FLAGS_RELEASE}) # set release flags

#    Global Definitions
if(CPU_ONLY)
    add_definitions(-DCPU_ONLY)
endif()

#    Include Directories
set(${PROJECT_NAME}_INCLUDE_DIRS ${CMAKE_SOURCE_DIR}/include)
include_directories(${${PROJECT_NAME}_INCLUDE_DIRS})
include_directories(${CMAKE_SOURCE_DIR}/src)

#    CMake Scripts dir
set(CMAKE_SCRIPT_DIR ${CMAKE_SOURCE_DIR}/CMakeScripts)

#	CMake module path for custom module finding
set( CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_SCRIPT_DIR})

#    CUDA is required globally
if(NOT CPU_ONLY)
    find_package(CUDA 5.5 REQUIRED)
    include_directories(${CUDA_INCLUDE_DIRS})
endif()

###    Subdirectories    ##########################################################################

add_subdirectory(src/gtest)
add_subdirectory(src/caffe)
add_subdirectory(tools)

if(BUILD_EXAMPLES)
    message(STATUS "Examples enabled")
    add_subdirectory(examples)
endif()

if(BUILD_PYTHON)
    message(STATUS "Python enabled")
    add_subdirectory(python)
endif()

if(BUILD_MATLAB)
    message(STATUS "Matlab enabled")
    add_subdirectory(matlab)
endif()

###    Lint Target Setup    ##########################################################################

set(LINT_TARGET lint)
set(LINT_SCRIPT ${CMAKE_SCRIPT_DIR}/lint.cmake)
add_custom_target(
    ${LINT_TARGET} 
    COMMAND ${CMAKE_COMMAND} -P ${LINT_SCRIPT}
)

###    Install    #################################################################################

#    Install Includes
file(GLOB folders ${${PROJECT_NAME}_INCLUDE_DIRS}/*)
install(DIRECTORY ${folders} DESTINATION include)

**Comment by pnambiar** [comment]
I tried with
set(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS} -gencode arch=compute_50,code=sm_50
). It still gave the same error
-P

**Comment by shelhamer** [comment]
Compile with the official Makefile or try the new CMake build in #1667.

**Comment by OliviaMG** [comment]
Im install a caffe, when i saw:
file(GLOB folders ${${PROJECT_NAME}_INCLUDE_DIRS}/*)
install(DIRECTORY ${folders} DESTINATION include)
then cmake ..  it shows:install DIRECTORY given non-directory
  "/Users/WarmingBug/comp2560-master/project/matlab/CY/external/caffe/include/.DS_Store"
  to install. would you mind tell me how to solve it? i used mac(cup-only). Thanks so much 
@pnambiar
