### ISSUE TITLE
GPU Memory Usage for Multiple GPUS

### ISSUE THREAD

**Issue by liuxianming** [BVLC/caffe#1399]
![screen shot 2014-11-04 at 1 10 30 pm](https://cloud.githubusercontent.com/assets/1305722/4906153/4d091f4e-6456-11e4-902b-165bf75c6cd0.png)
Hi, Guys

I'm wondering if anyone has already posted this issue before. I'm working on a machine with two Tesla K40 gpus. When I trained a network on GPU1, there is a thread in GPU0 which takes a portion of GPU memory. I used to find this problem on early version of Caffe, in which the process in GPU0 took a duplicated memory block but the utilization of GPU is 0. Now it only takes a portion of the total memory usage. 

I guess it is because that some initialization of the code is fixed to use GPU0, but where is it?

**Comment by xavigibert** [comment]
This issue is still unresolved. The DataLayer prefetch thread, "DataLayer<Dtype>::InternalThreadEntry" in data_layer.cpp, indirectly calls "cudaEventCreate" in benchmark.cpp. The whole story is that "DataLayer<Dtype>::InternalThreadEntry()" instantiates an object of class "CPUTimer". "CPUTimer" is derived from "Timer", and the constructor of "Timer" calls "Timer::Init", which calls "cudaEventCreate". Since only the main thread calls caffe::Caffe::SetDevice, this other thread defaults to GPU 0. In my machine, this results in a memory allocation of about 38M on GPU 0 for each instance of Caffe (see my example below).

![screen shot 2015-08-14 at 1 08 42 pm](https://cloud.githubusercontent.com/assets/1545442/9279569/679158ea-4286-11e5-8e49-c89fb408e0c4.png)

In my application, I cannot not run two instances of Caffe on a GTX 690 because it exceeds the 2048MB limit, so I have had to fix this problem by modifying class CPUTimer so that it no longer inherits Timer. If you find my fix acceptable, please let me know and I will create and submit a pull request.

**Comment by frombeijingwithlove** [comment]
I got the same issue, and finally found to be the use from opencv, particularly cv::merge, cv::subtract and cv::split which are common operations for caffe.
