### ISSUE TITLE
Reference AlexNet is incorrect: alpha is 5 times too small in the LRN layer

### ISSUE THREAD

**Issue by seanbell** [BVLC/caffe#1453]
LRN is specified by this equation (from the AlexNet paper [Krizhevsky 2012]):

![screenshot from 2014-11-19 15 00 17](https://cloud.githubusercontent.com/assets/1844189/5113347/eff6d9ec-6ffc-11e4-85f4-365647d73e5c.png)

Rather than multiplying the sum by alpha, caffe multiplies the sum by (alpha / n).  Thus, the coefficient of the sum used in the reference model is actually n=5 times smaller than the original parameter suggested by [Krizhevsky 2012].

So, either the reference AlexNet should use alpha = 5e-4 instead of 1e-4 to match [Krizhevsky 2012], or the LRN layer should not divide by n (aka "local_size").

**Comment by studio1729** [comment]
Another possible difference we just noticed: the AlexNet paper [Krizhevsky 2012] specifies k=2.  However, it looks like since k is not specified in train_val.prototxt, Caffe will use its default value of k=1 (from https://github.com/BVLC/caffe/blob/master/src/caffe/proto/caffe.proto).  Has anyone played with this?
