### ISSUE TITLE
How to turn on backward computation in source code

### ISSUE THREAD

**Issue by jamesguoxin** [BVLC/caffe#1515]
Hello guys,

Yesterday, I wrote a new layer I called EarlystopLayer, which is used to check whether we should terminate back-propagation of EuclideanLossLayer under some certain circumstances. So this layer will be above EuclideanLossLayer, I pass the LOSS value to this layer, do some computation to see if it meets some condition. If so, I could set bottom[0]->mutable_cpu_diff()[0] as 0 in EarlystopLayer to turn off EuclideanLossLayer's back propagation. 

What bothers me is that during the training, caffe seems automatically set this new layer as "does not need back propagation", I would like to ask is there any way we could set back propagation as true for my EarlystopLayer. Thank you very much!

**Comment by shelhamer** [comment]
The details of `need_backward` are in [Net::Init](https://github.com/BVLC/caffe/blob/master/src/caffe/net.cpp#L34-L219) although it's essentially whether a layer is on a path between parameters to be learned and a loss. Since your layer is after the loss, Caffe does not think it is needed for backward.

Whether to stop learning or not is likely better put in a Solver than in the logic for a given Layer.
