### ISSUE TITLE
RNN LSTM layer

### ISSUE THREAD

**Issue by bhack** [BVLC/caffe#1653]
@jeffdonahue @sguada Do you have code to share for your pubblication: http://arxiv.org/abs/1411.4389?

**Comment by cbalint13** [comment]
Should see this: https://github.com/dophist/kaldi-lstm (holds CUDA code too, i think is the best one).

**Comment by nakosung** [comment]
https://github.com/junhyukoh/caffe-lstm nice work from u-mich.

**Comment by bhack** [comment]
@junhyukoh Do you have a plan to contribute back to caffe with a PR?

**Comment by sunbaigui** [comment]
@junhyukoh looking forward to your merge :D

**Comment by junhyukoh** [comment]
@bhack @sunbaigui Thank you for your interest! 
But, I think my current implementation does not perfectly fit to Caffe. 
Since I'm using a mini-batch as a training sequence (an unrolled RNN), my code supports only SGD not the mini-batch update (one update after processing several training sequences).
I plan to rewrite the code and do PR when it's ready, but I cannot guarantee the timeline. 
Feel free to use my code and any comments are welcome!

**Comment by jeffdonahue** [comment]
Closing, see #1873 for (a cleaned up version of) the implementation we used for LRCN.
