### ISSUE TITLE
MAC OS X 10.10:make all ,issue:ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by greatgao** [BVLC/caffe#2018]
the same issue to the website:https://github.com/BVLC/caffe/issues/1725.And my caffe-master is the lasted .My OS is MAC OSX 10.10.and follow the installed guide document.but there is a problem about "ld: symbol(s) not found for architecture x86_64"。and the information is as the follow:
clang: warning: argument unused during compilation: '-pthread'
Undefined symbols for architecture x86_64:
  "cv::imread(std::string const&, int)", referenced from:
      caffe::WindowDataLayer<float>::InternalThreadEntry() in window_data_layer.o
      caffe::WindowDataLayer<double>::InternalThreadEntry() in window_data_layer.o
      caffe::ReadImageToCVMat(std::string const&, int, int, bool) in io.o
  "cv::imencode(std::string const&, cv::_InputArray const&, std::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)", referenced from:
      caffe::ReadImageToDatum(std::string const&, int, int, int, bool, std::string const&, caffe::Datum*) in io.o
  "leveldb::DB::Open(leveldb::Options const&, std::string const&, leveldb::DB**)", referenced from:
      caffe::db::LevelDB::Open(std::string const&, caffe::db::Mode) in db.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [.build_release/lib/libcaffe.so] Error 1
What should I do could solve the issue?

**Comment by colincsl** [comment]
This thread might help you: https://groups.google.com/forum/#!topic/caffe-users/G7gj03A-JPw

**Comment by wookayin** [comment]
I am also experiencing this issue, on OS X 10.10 with any version of `protobuf` (on current master).
In my environment, **libstdc++ was NOT used** at all for building anything, including `opencv`, `glog`, `protobuf`, and so on.

When doing `make` on `CAFFE_ROOT`, I get the same error as you; but using `cmake` (`cd build && cmake .. && make`) it works fine (I don't know why `make` on the root would fail).

I am doubtful that the ordering of library linkings is correct (i.e. `LDFLAG`), since the following workaround which places libraries the unresolved symbols in front, is working:

```
$ DFLAGS="`pkg-config --libs protobuf` `pkg-config --libs opencv`" make all
```

Additionally, in similar way, the following would be a workaround leading me to successfully matlab bindings (to build `matcaffe`)

```
# LIB_MATLIB="/Applications/MATLAB_R2014b.app/bin/maci64
$ DFLAGS="(... as above...) -L$LIB_MATLIB" make matcaffe
```

I hope I can further investigate into this issue afterwards as well.

**Comment by greatgao** [comment]
Thanks your words.But after that I did follow you ,there is the same error here.Could u tell me the detail step by step？And I type the linev in terminal :"$ DFLAGS="`pkg-config --libs protobuf` `pkg-config --libs opencv`" make all".and there is a error as follow:
greatgaos-MacBook-Pro:build greatgao$ $ DFLAGS="`pkg-config --libs protobuf` `pkg-config --libs opencv`" make all

-bash: $: command not found
