### ISSUE TITLE
Dose anyone know how to extract features from some patches generated by cropping an image using matlab  based on caffe

### ISSUE THREAD

**Issue by henurgwpf** [BVLC/caffe#2091]
Dose anyone know how to extract features from some patches generated by cropping an image using matlab  based on caffe

**Comment by henurgwpf** [comment]
using a pretrained model or using my own model,but I also do not know how to train my own modle,anyone knows????

**Comment by n-zhang** [comment]
There is matlab example in  https://github.com/BVLC/caffe/blob/master/matlab/caffe/matcaffe_demo.m
One way to extract from one layer in the middle instead of last layer is to modify the prototxt to end in that layer and run forward. 

We welcome you to look at the extensive documentation, tutorials, and examples at http://caffe.berkeleyvision.org/ and ask usage questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!

**Comment by henurgwpf** [comment]
@n-zhang  I mean that I want use my own deploy.prototxt(not imagenet), but I think I should train a corresponding model(not imagenet-reference model) for the deploy.prototxt file. The problem is how I train my own model use matlab interface.
