### ISSUE TITLE
Non-image application in caffe.

### ISSUE THREAD

**Issue by getsiddd** [BVLC/caffe#2141]
Does anyone know how to use caffe with non-image applications...?

**Comment by erictzeng** [comment]
There's nothing about Caffe that requires you to use images specifically. There are plenty of data layers that load arbitrary data, and while some of our layers are more useful with images, most of them will work on non-image data as well.

If you have any further questions, please ask them on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) -- this issues tracker is primarily for Caffe development discussion. Thanks!

**Comment by bhack** [comment]
@erictzeng I see you and other at BVLC are doing some triage of issues (mainly trivial/support one). I suggest you to not reply directly on the ticket but point people on mailing list. Because user often try to open ticket as a "short path" for post already done in mailinglist (to have a faster reply). If you give a reply closing ticket some people will continue to open one for support. This generate a little bit of continuous noise. Probably if also some discussion could be developed on the gitter channel to have a little more "interactive" conversation if needed.

**Comment by erictzeng** [comment]
@bhack I talked with a few of the other members, and we agree. Moving forward, we'll be more aggressive about moving usage questions to caffe-users. Thanks for the insight.
