### ISSUE TITLE
DataTransformer as a separate layer

### ISSUE THREAD

**Issue by danielhauagge** [BVLC/caffe#2225]
I'd like to be able to use DataTransformer with HDF5, is there any intention of pulling DataTransformer out of ImageData so that it can be associated with any data source? Is there some good technical reason why this is not already the case?

**Comment by shelhamer** [comment]
Transformations should be there own layers for modularity and simplicity. However, to maintain speed and memory usage Caffe needs to learn more about pipelining so that all transformation layers can be done in prefetch. Right now prefetching is a special case handled within data layers in their own separate thread. To make good use of IO and transformation layers, Caffe needs to have a better module of execution so that the `Net::Init()` logic can schedule different layers instead of everything happening in forward or backward (or the oddball data layer prefetch threads).

This deserves improvement.

There is some discussion at #569.
