### ISSUE TITLE
Problem with make runtest

### ISSUE THREAD

**Issue by Tutufa** [BVLC/caffe#2262]
Hi, Im trying to install caffe and everything works, until I run: make runtest, it outputs this:

.build_release/tools/caffe
dyld: Library not loaded: libcaffe-nv.so.0
Referenced from: /Users/caffeteria/caffe/.build_release/tools/caffe
Reason: image not found
make: *** [runtest] Trace/BPT trap: 5

can anyone help how to solve this?

OS 10.10.2, I mostly used brew and pip

this refers to NVIDIAs version of caffe, BVLC version compiles and runs runtest just fine

**Comment by lukeyeager** [comment]
Please ask DIGITS-related questions [there](https://github.com/NVIDIA/DIGITS/issues) instead of here at BVLC's page.

The issue seems to be that our implementation of versioning isn't done correctly for a cross-platform build environment (see this commit: NVIDIA/caffe@18a3ff4e12c3431d5124c8e997944b75407ff442). Thanks for bringing to my attention - let's talk about it at NVIDIA/DIGITS#46.
