### ISSUE TITLE
Embarresment to the Caffe C++ community....

### ISSUE THREAD

**Issue by michael-george-hart** [BVLC/caffe#2306]
We as C++ developer need to do something about this...

It is an embarrassment to all Caffe C++ developers and ME (well not so much me since I am a novice at Caffe :p ) when a very experience (20 plus years) and very dedicated to C++ (20 plus years) development that spent more than 2 days (a real 36 hours) reading every possible C++ Caffe related BLOG and could not find an acceptable solution that seems easy enough to add the desire features to NVIDIA-DIGITS/PYTHON to get what I want in about 3 hours...(I really don't like using the PYTHON language)

I think that we should band together and get a clean, simple to use high lever wrappers that make Caffe easy to integrate into C++ systems....

Perhaps such a group of high level code/framework exist ... I couldn't find them.... Anyone for a new C++ project that complements NVIDIA DIGITS....

Michael

**Comment by KangKyungSoo** [comment]
Qt/Caffe would be nice.

**Comment by michael-george-hart** [comment]
QT/Caffe is exactly my thoughts ....

**Comment by michael-george-hart** [comment]
That is exactly my thoughts

On Mon, Apr 13, 2015 at 6:40 PM, KangKyungSoo <notifications@github.com>
wrote:

> Qt/Caffe would be nice.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BVLC/caffe/issues/2306#issuecomment-92520156>.
>



-- 
*"...Hope is what makes us strong. It is why we are here. It is what we
fight with when all is lost..."*

**Comment by flx42** [comment]
I'm sorry but I didn't understand what you are trying to achieve with the C++ API.
The current C++ API is low level but I don't think it's that hard to use.

**Comment by michael-george-hart** [comment]
There is no good reason it needs to be "LOW LEVEL".
 C++, dare I say, can achieve level of abstraction of a Domain Specific Language (DSL) ... perfect examples are things like BOOST Spirit and BOOST FSM. The Qt Framework is another good example of very high level concepts expressing the graphic elements that makes it very easy for anyone without any real experience to be sophisticated GUI applications .... There is absolutely no good reason for the Caffe to wallow in "low level" abstractions....

 It is well established that C++ can achieve level of abstraction beyond PYTHON via its meta programming capabilities create to a DSL for Caffe... My thinking is you could do away with the PROTO files expressing the as sort of DSL directly in C++

**Comment by flx42** [comment]
Of course there are good reasons to stay rather low level: efficiency and avoiding unnecessary dependencies like python does.

But what is it you're trying to achieve? Training or inference?
Why would you need a DSL for that? Do you really want to recompile your code all the time instead of modifying a simple text file in a well-defined and well-supported format?

**Comment by michael-george-hart** [comment]
High Level, especially in C++, does not mean less efficient... The C++ STL is a perfect example of this. Meta coding can be very effective ....

The only dependencies most DSL have are C++ headers.
My recent experience Caffe pronto there are certain strategies assume. If everything line up correctly ....FANTASTIC!!! if not you end up going back to the C++ code poking and prodding the code to get around some of the assumption of the PROTO's

My frustrating example was a proto that worked perfectly find in python during testing but would complain about things that needed to be reshaped ... spending 2 days reading all the blogs had me doing all sorts of convoluted things with the Caffe C++ codes ... including limiting Caffe to handle only gray scale images.... Something is very wrong when a recommended fix was to break the Caffe C++ API.
Lets face it Caffe is for all intended purposes is an interpreter (the protos being the syntaxs), that has become a low level component of PYTHON, another interpreter. 

What this has done it push and hide any difficulties one may have with bad design in the C++ code under the covers of PYTHON .... continuing to do this in my opinion will eventually make the underlying C++ code for Caffe become unmanagable... the amount of frustration I have read about on the various blogs about getting simple things to was was a sad reflection of a bad design and push PYTHON to hide those design deficiencies

**Comment by flx42** [comment]
You are being overly vague again. You should demonstrate your claims by mentioning existing API functions and the problems you stumbled upon while trying to use them.
Then, you should submit a RFC for a new C++ API and explain how it solves your problems while being more generic.

**Comment by michael-george-hart** [comment]
You are quite right I am being vague,...At this point in time... when one has bought into the advertising about ease of use and have made a major project commitment in using said product and then find that the product is not as easy to use as said and seems to be in a late beta stage, for the C++ developer using said C++ API... one has little time writing/keeping detail notes of the mind numbing  number of on blogs and problems one has discovered on the way to issues encountered using C++ and fixing issues  Convolutions Shape and dimensions... If it wasn't for the PYTHON/DIGITS where I simply dropped in my proto I probably be still be bashing my head again the wall...... 
ADDITIONALLY--- From this quote .... I get the impression that Caffe is truly heading in the direction of being the low level supporting library for PYTHON .... similar to the what numpy (C based library at it core) 
"Caffe has command line, Python, and MATLAB interfaces for day-to-day usage, interfacing with research code, and rapid prototyping. While Caffe is a C++ library at heart and it exposes a modular interface for development, not every occasion calls for custom compilation. The cmdcaffe, pycaffe, and matcaffe interfaces are here for you."

So in my eyes it would seem more prudent in taking the original C++ code and abstract away as pure C++ project independent without consideration for any other language binding such as PYTHON, MATHLAB.... which seems like a reasonable thing to do since more of Caffe are not system level developers...... Just my opinion

**Comment by jyegerlehner** [comment]
I was going to make a lengthy reply, but I think I'll just say [no good deed goes unpunished](http://en.wiktionary.org/wiki/no_good_deed_goes_unpunished).

**Comment by michael-george-hart** [comment]
Just so that none one get me wrong about Caffe....
I commend all the people who have brought C++ code/system  this far...
My one real gripe is that Caff seems, from what I have read, is becoming a infrastructure system/library for PYTHON and not a system unto itself.

**Comment by dxj19831029** [comment]
@michael-george-hart I see your points. 
First, python and matlab is heavily used in the research area.

Second, I believe caffe and any other machine learning libraries is started as research project or 
served for very similar purpose. Therefore, python and matlab support is required.

Third, if you diving into the C++ code, you will find that, all you needed is written in C++. If you only want to write C++, you can. Yeah, they need more documentation to teach people how to do it, but this should not stop anyone to do it. I don't know if you look at torch/cuda-convnet/theano inside, I did. And you can not simply write in purely C++, because some important training logic is written in script language. So the caffe so far is the best choice. 

 Fourth, I do agree with your points.

 I think the maintainers of caffe group have their own research targets, they don't have that much time. 

I agree with @flx42 , if you think your idea is good, please demonstrate it in detail with samples. We can discuss on it, we may come up with something good. :)

**Comment by michael-george-hart** [comment]
There is no doubt in my mind that Caffe is the best of the lot of them. 
That is perhaps my greatest source of disappointment, as far as a C++ developer goes.
The great part about it being opensouce is .... I cannot truly complain about Caffe, since I have the source code to extend Caffe into what I want and need it to be....
Hopefully, I will start doing that after I have helped get DIGITS to what I would like to see it become.
Right now I simply hope to get DIGITS to where Luke and its community envision it should be.

**Comment by hartsantler** [comment]
The C++ API has some ugly parts, but it generally looks ok. I'm still learning Caffe, later I plan to make a high level interface to it so its simpler to use.  Here is my caffe hello world with simpler interface (rusthon->c++).

[hello_caffe](https://github.com/rusthon/Rusthon/blob/master/examples/hello_caffe.md)

**Comment by shelhamer** [comment]
Interface suggestions and pull requests speak louder than comments, so have a cup of :coffee: and join in!

I'm closing this since Issues are for detailed development discussion and constructive comments -- this conversation has been vague and the tone has left a little to be deserved. Follow-ups with thought-out and detailed suggestions are welcome, but this thread is done.

Thanks everyone who contributed precise, reasoned discussion.

Thanks @flx42 for trying to steer in the direction of details and concrete suggestions.
Thanks @jyegerlehner for delivering the wisdom.
