### ISSUE TITLE
What is the difference between using layers and layer while defining DAG?

### ISSUE THREAD

**Issue by AmNotGod** [BVLC/caffe#2345]

**Comment by jyegerlehner** [comment]
"layers" is deprecated. It was changed to "layer".

**Comment by kevinkit** [comment]
I wrote a small converter, it is not fancy and anything but it works as far as I could test it: [Converter](https://github.com/kevinkit/ColdCoffeToHotCoffe)

**Comment by shelhamer** [comment]
@kevinkit I like the project title, but you should know there's a built-in tool for upgrading definitions https://github.com/BVLC/caffe/blob/master/tools/upgrade_net_proto_text.cpp

**Comment by kevinkit** [comment]
Wow thank you ! I have not known about this, is there a python interface for this, too ?

**Comment by fungtion** [comment]
Is there any way to convert the caffemodel pre-trained using layers, so that it can be used by the model using layer?

**Comment by shelhamer** [comment]
@kevinkit it's called behind-the-scenes when you instantiate a `caffe.Net` in pycaffe so you shouldn't have to do it yourself.

**Comment by kevinkit** [comment]
@fungtion  You should be able to use the .caffemodel files since they only store the weights. If your architecture still describes the same filters, and so the same amount of weights etc. , it should be no problem to load a file that was trained on the old syntax. However, you must load the new architecture with layer - since caffe will now throw an error if there is layerS defined. 


@shelhamer Thank you, well I note my project as an experience gain

**Comment by fungtion** [comment]
@kevinkit thank you, it works
