### ISSUE TITLE
Fast R-CNN

### ISSUE THREAD

**Issue by bhack** [BVLC/caffe#2411]
**Fast R-CNN** is a fast framework for object detection with deep ConvNets. Fast R-CNN
 - trains state-of-the-art models, like VGG16, 9x faster than traditional R-CNN and 3x faster than SPPnet,
 - runs 200x faster than R-CNN and 10x faster than SPPnet at test-time,
 - has a significantly higher mAP on PASCAL VOC than both R-CNN and SPPnet,
 - and is written in Python and C++/Caffe.

Please take a look at @rbgirshick work at https://github.com/rbgirshick/fast-rcnn
And [here](https://pdollar.wordpress.com/2014/11/18/evaluating-object-proposals/) for other object proposal other then selective search.

EDIT:
See also fresh new fast object proposal LPO by @philkr https://github.com/philkr/lpo

**Comment by longjon** [comment]
Thanks for the pointers, but this is not an issue. This kind of thing is useful, though, so I've created a new wiki page at https://github.com/BVLC/caffe/wiki/Related-Projects and roughly pasted this text there; feel free to edit and add as you see fit, and announce as you like on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users). Thanks!

**Comment by bhack** [comment]
I think that could be an issue if there is something that could be integrated upstream. See https://github.com/BVLC/caffe/pull/482#issuecomment-98723687

**Comment by longjon** [comment]
Yes, you're welcome to create issues or PRs for specific individual features implemented in Fast R-CNN that should be included in Caffe; it's just that generically pointing out the existence of a related project isn't appropriate for issues. As a general rule, there should be a clear way to tell whether each issue has been addressed or not; otherwise, use other discussion channels so we can have a meaningful picture of things that need to be done here.
