### ISSUE TITLE
Unit-Tests do not use custom parameters

### ISSUE THREAD

**Issue by PatWie** [BVLC/caffe#2584]
Running

    LayerParameter layer_param;
    layer_param.ParseFromString("mvn_param{normalize_variance: false}");
    std::cout << layer_param.mvn_param().normalize_variance()<<std::endl;
    LayerParameter layer_param2;
    layer_param2.ParseFromString("mvn_param{normalize_variance: true}");
    std::cout << layer_param2.mvn_param().normalize_variance()<<std::endl;

in `src/caffe/test/test_mvn_layer.cpp` makes no difference.

**Comment by jyegerlehner** [comment]
Right. That issue was discussed in [1938](https://github.com/BVLC/caffe/issues/1938) and before that in [1355](https://github.com/BVLC/caffe/pull/1355). We should be using 

```
CHECK(google::protobuf::TextFormat::ParseFromString("mvn_param{normalize_variance: false}", &layer_param));
```
instead. In the code you show, LayerParameter::ParseFromString is failing but the failure goes undetected since we ignore the return value. I think it fails because it expects a binary-serialized object as its argument. 

If you change to using the correct ParseFromString, you will see a number of the MvnLayer tests are failing. I think [PR 1979](https://github.com/BVLC/caffe/pull/1979) fixes those problems.

**Comment by PatWie** [comment]
This seems to be a general problem in each unit test for each layer using `ParseFromString`.
It does not expect a binary-serialized object. Its definition is:

     ParseFromString(const string & input, Message * output)

**Comment by jyegerlehner** [comment]
> This seems to be a general problem in each unit test for each layer using ParseFromString.

The only test that doesn't use `TextFormat::ParseFromString` is `MVNLayerTest`. So I don't think it is a general problem. DBTest also uses Message::ParseFromString but its usage is correct because it is parsing a binarized protobuff message.

>It does not expect a binary-serialized object. 

The member function Message::ParseFromString expects a binarized message. The string `input` is a buffer for it. Static function TextFormat::ParseFromString is the one that parses human-readable message.
