### ISSUE TITLE
Temporarily disable logging for Caffe

### ISSUE THREAD

**Issue by PiranjaF** [BVLC/caffe#2628]
I've tried in different ways to temporarily disable the logging done when e.g. loading prototxt files in the Python interface to Caffe, but I've been unsuccessful and most of the solutions were quite hacky. See https://groups.google.com/forum/#!topic/caffe-users/4-HtwKqE5xM for more information.

I would therefore like to request a way of temporarily disabling the logging using the Python interface. This would hopefully be useful for everyone that likes short concise logs and know the definition of their network.

**Comment by lukeyeager** [comment]
See #2504

**Comment by lukeyeager** [comment]
@jshfeng, can you explain why you closed this issue?

> I would therefore like to request a way of temporarily disabling the logging using the Python interface.

This seems like a valid RFE to me, which deserves some sort of a response.

**Comment by VasLem** [comment]
Do we have any update on this subject? I want to change sys.stderr to a custom output, so that to capture caffe log in a database for experimentation logging, but I am not able to alter anything after importing caffe module, as far as glog logging is considered. The custom output object is created inside the Python program, so I can not call it through terminal (that is, use the bash stderr redirection). I can think of some dirty workarounds, but I would mess really hard with my code. Why aren't any Python wrappers for logging configuration in caffe? This is a severe drawback, with which many people have to make ammends. Are there any plans to fix this behavior, or at least force caffe to actually return the stderr output after each method call, as a variable, so that one can actually do what he pleases with it?
