### ISSUE TITLE
Incompatibility with RCNN due to new Matlab wrapper

### ISSUE THREAD

**Issue by nightrome** [BVLC/caffe#2641]
The changes made on 21 May on this file (1) break the compatibility of Caffe and RCNN. I don't understand why they needed to take place and the documentation does not mention them either. By putting the caffe mex file into a private folder, it is not accessible any more. See for example (2). These changes should be undone!

(1) https://github.com/BVLC/caffe/commits/master/matlab/%2Bcaffe/private/caffe_.cpp
(2) https://github.com/rbgirshick/rcnn/blob/master/rcnn_load_model.m

**Comment by ronghanghu** [comment]
Hi, @nightrome I wrote the new Matlab interface in #2505 , and I apologize for your inconvenience.

The purpose of this update is to add more functionality (e.g. net surgery and training) into matlab interface. However, I admit that it is somehow an aggressive change and lacks backward compatibility, which breaks RCNN code.

Caffe mex file into a private folder to prevent from accessing it directly. One should use `caffe.set_mode_gpu()` instead of `caffe_('set_mode_gpu')`.

There are several solutions you can do to get RCNN work.
1. Use Caffe's RCNN release: https://github.com/BVLC/caffe/releases/tag/rcnn-release
2. Update code in RCNN to fit new matcaffe. To do that, one need to a) replace things like `caffe('set_mode_gpu')` with `caffe.set_mode_gpu()` and similar for "set_device". b) replace `caffe('init', ...)` with `net = caffe.Net(...)` to create a net and hold it in `rcnn_model`, and replace `caffe('forward', ...)` with `net.forward` c) replace caffe('get_weights') with parameter access in new interface.

**Comment by Linzert** [comment]
Hi.@ronghanghu I can't compile the caffe you provided.When I compile the newest version caffe,I can do it successfully!But the newest version is not compatible with RCNN,why is it?The error messages are:

In file included from ./include/caffe/caffe.hpp:8:0,
                        from tools/finetune_net..cpp:11:
./include/caffe/common.hpp:13:21:fatal error:mkl_vsl.h:No such file or directory
compilation terminated.
 I have the file mkl_vsl.h and it's included in the makefile.config path.What's the problem?
