### ISSUE TITLE
traind model on GTX 760 but different classification results on GTX 980 Ti

### ISSUE THREAD

**Issue by cysin** [BVLC/caffe#2734]
I am using caffenet and trained model on my own image dataset with GTX 760 cards. It works fine with GTX 760 cards but got different results when using GTX 980 Ti cards. I have tried to reinstall nvidia driver and cuda but still the same. GTX 760 is more accuracy. So would anyone please explain this?

**Comment by seanbell** [comment]
Are you using cuDNN?  Are you using dropout our any randomization?  How different are the results?

**Comment by cysin** [comment]
Yes I am using cuDNN v2 (cuda 7.0, on CentOS 7). I didn't modify the caffenet definitions except the 'num_output' in 'fc8'. About 8% - 15% of the results are different.

**Comment by cysin** [comment]
And also every time I run the program (with 980 Ti) the results are slightly different, I mean I can't get exactly the same results every time I run the program multiple times

**Comment by seanbell** [comment]
Do you have the same problem if you build without cuDNN?

**Comment by cysin** [comment]
I mean the testing part. I trained a model with 760 and I use this model to do image classification on 760 and 980 Ti. The 'different' means the classification results. I haven't test it without cuDNN but I will update this thread as soon as I have done the test.

**Comment by seanbell** [comment]
My thinking is that cuDNN may introduce non-determinism into the calculation.  We can't know because the code is proprietary.  However, you can inspect the open-source non-cuDNN caffe implementation and verify that all computations are deterministic (up to machine error).

**Comment by cysin** [comment]
I just confirmed that it all went fine without cuDNN. And also it might even be a little bit faster without cuDNN. I don't understand that why nvidia provides such a library that introduces so much troubles...

**Comment by seanbell** [comment]
Yeah, I've found that cuDNN isn't always faster; it depends on the model.  I only use it when I can verify that it's better than the caffe engine.  cuDNN also makes some assumptions that don't always hold (e.g. in-place computation breaks some cuDNN layers, see #2688).  I think that there is work to be done in better documenting and checking for these sorts of issues.

**Comment by wafflette** [comment]
You say 8-15% of the results are different but what about classification accuracy? How different from run to run? How different vs Caffe?

**Comment by slayton58** [comment]
Are you fixing the random seed in order to remove that element of randomness?

@seanbell cuDNN does use non-deterministic algorithms in a couple of routines, from the v2 user guide:

"By design, most of cuDNN's routines from a given version generate the same bit-wise
results at every run when executed on GPUs with the same architecture and the same
number of SMs. However, bit-wise reproducibility is not guaranteed across versions,
as the implementation of a given routine may change. With the current release, the
following routines do not guarantee reproducibility because they use atomic add
operations:
‣ cudnnConvolutionBackwardFilter
‣ cudnnConvolutionBackwardData"

**Comment by smartbitcoin** [comment]
Even you run everything on CPU , the result maybe different too.  that's the nature of floating point!  floating point calculation is not accurate! 
Tell you a fact,  I find same model on  intel's 3th i5 3470 and amd 's A10 6800k,  the result is different!
so,  don't feel astonished, and try to figure out how far the diff is and why.
another possibility is the SGD resolver,  no guarantee for alway hit same optimization. it's better to plot out your loss curve to check where it hit.
And maybe its caffe's bug or your model's bug. but that need more detail to tell.  so your post suppose to have models , logs etc. to help us identify.  right ?  lol

**Comment by wafflette** [comment]
As smartbitcoin said, results can vary depending on a specific CPU/GPU model because floating point results are not the same even if you reorder additions between 4 numbers, for instance:

(100000 + 0.001) + (-100000 + 0.002) = 0. (in FP32)
but
(100000 - 100000) + (0.001 + 0.002) ~ 0.003

So when running on a smaller card it's extremely unlikely that you will get the same exact result.

However getting a significantly different result might be a bug as generally things should converge.

One idea could be to try different random seeds for initial weights and seeing how it affects convergence/accuracy.

**Comment by cysin** [comment]
Thanks for the replies. According to my test, the results without cuDNN are excepted and have a higher correct ratio. I do understand the floating point calculation differences between CPU and GPU, but this time it's obviously not that case.

**Comment by slayton58** [comment]
@cysin Actually it looks like the calculation differences are the case - some of cuDNN's algorithms use atomic operations, which means the order of summation is not guaranteed to be the same every run - this can give different answers (as per @wafflette's explanation). That order of summation is likely to be different again when run on different GPUs, explaining your discrepancies.
