### ISSUE TITLE
Using GPU on a virtual machine

### ISSUE THREAD

**Issue by tiferet** [BVLC/caffe#2749]
I am about to create a VM running Ubuntu in order to use Caffe from my Windows machine, and wanted to know if there is any way I can set things up so I can use GPU despite this being a VM. I prefer to use VMWare but am open to other options, and I can configure the VM to use its own dedicated physical disk. I prefer to run Ubuntu through the VM, though, and not boot directly into it.

Any advice would be much appreciated! Thank you!

**Comment by danbuckler** [comment]
I do not believe that you will be able to access the physical GPU from within the virtual machine.

**Comment by seanbell** [comment]
I think it depends on the virtualization method -- for example, virtual machines on Amazon EC2 can access the GPU.  You might have better luck dual-booting rather than running an Ubuntu VM inside Windows.

Also, please ask questions like this on the caffe-users group (https://groups.google.com/forum/#!forum/caffe-users), as it is unrelated to the codebase.

**Comment by tiferet** [comment]
Sorry for posting in the wrong place. Thank you for the information!
