### ISSUE TITLE
dynamic module does not define init function (initcaffe)

### ISSUE THREAD

**Issue by tepposaari** [BVLC/caffe#2770]
Hi,

had so much trouble compiling caffe, and when I finally managed to get it compiled it gives me an error about init function (both with ipython and running a python script):
```
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
Type "copyright", "credits" or "license" for more information.

IPython 3.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import caffe
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-1cca3aa1f8c5> in <module>()
----> 1 import caffe

ImportError: dynamic module does not define init function (initcaffe)
```

The caffe module is used in [https://github.com/graphific/DeepDreamVideo](DeepDreamVideo) which I tried running.

**Comment by BlGene** [comment]
Do you get the same error if you do 
```
python2 -c "import caffe"

**Comment by tepposaari** [comment]
Hi,

yes it seems so.

```caffe$ python2 -c "import caffe"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dynamic module does not define init function (initcaffe)
```

**Comment by longjon** [comment]
Closing as this looks like a mismatch between build library and Python versions; please ask installation questions on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users). If you do think there is a bug in Caffe, you're welcome to open a new issue according to https://github.com/BVLC/caffe/wiki/Reporting-Bugs-and-Other-Issues. Thanks!

**Comment by cqulin** [comment]
`sudo vim ~/.bashrc
export PYTHONPATH=$**home/username/**caffe/python:$PYTHONPATH
source ~/.bashrc`
For me, i added the module directory to our $PYTHONPATH, and `make all -j8
make test -j8
make runtest -j8` again, and its works for me.

**Comment by Laowai01** [comment]
i have compiled caffe on Ubuntu 16.04 LTS both with python 2 and python, it is really a hectic process for beginners, for caffe with python 2.7 make sure that your /.local/lib/python2.7/site-packages only contains a version same as you protoc version. protoc version can be checked by entering
`protoc --version`
for me i got problems with python 2.7 because by mistake i installed protbuf 3.0 alpha in python 2.7 site packages, so there was a protobuf error after removing it from python 2.7 site packages everything worked fine
also install python-dev version
`apt-get install the python3.x-dev`
and for python 3.5 make sure you have python 3.0 alpha, if you have both python 2.7 and python 3.x in the system use pip3 otherwise use pip

`pip3 install protobuf==3.0.0-alpha-3`

or another protobuf such as 3.5 version of protobuf.
also do this
`pip3 install python-dateutil --upgrade`
after that do 
`make clean`
`make all -j8`
`make runtest -j8`
`make pycaffe`
after performing make all make runtest steps don't forget to do that
`sudo ldconfig`

hope everything works OK for you.

**Comment by kivoimusa** [comment]
Add the following lines of code to fix the python interpreter
locate your scripts in local machine with 'io.py' name and edit the script to include the following:
#new line of code
void*const libpython_handle = dlopen("libpython3.8.so", RTLD_LAZY | RTLD_GLOBAL);
PyInitialize();
