### ISSUE TITLE
Fully Convolutional Semantic Segmentation error

### ISSUE THREAD

**Issue by vibhav-vineet** [BVLC/caffe#2788]
Hi, 
While running the Fully Convolutional Semantic Segmentation Code, I get following error:

... layer_factory.hpp:77] Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: Crop (known types ... 

Any suggestion in solving this issue would be really helpful. 

Thanks,

**Comment by Geekrick88** [comment]
You need to merge the pull requests that are in the future branch of John Long's repo. It contains, among several other things an implementation of the crop layer.

**Comment by kashefy** [comment]
@vibhav-vineet 
You can find instructions on merging on [longjon's fork](https://github.com/longjon/caffe) after checking out his ['future' branch](https://github.com/longjon/caffe/tree/future). Look for [future.sh](https://github.com/longjon/caffe/blob/future/future.sh)

However, it seems that recent PR merges on the main BVLC repo, have made some of these instructions obsolete. This may have to do with longjon's master branch falling behind of the BVLC master. A few observations:

* merging #1976 into longjon:master works fine. The PR **has yet to be merged into BVLC:master**. This PR contains the crop layer.
* #1977 has been **merged into BVLC:master**. It's no longer possible to merge into longjon:master. I think the author of the PR removed the branch from his remote. This PR is for gradient accumulation.
hub merge https://github.com/BVLC/caffe/pull/1977
# python net spec
hub merge https://github.com/BVLC/caffe/pull/2086
* #2086 has been merged into BVLC:master. It should still be possible to merge it into longjon:master but  it runs into conflicts.

I was thinking of doing this from the BVLC master instead of longjon:master. That way I only need to merge the crop-layer changes from #1976. It requires some conflict resolution though. Lines from the CropLayer and SPPLayer are interleaved and need to be separated. Will see if I can separate them.

**Comment by longjon** [comment]
Closing since this is about longjon/caffe rather than BVLC/caffe. You're welcome to open issues there as appropriate (I just turned this on), or discuss on [caffe-users](https://groups.google.com/forum/#!forum/caffe-users).

It is possible to merge `CropLayer` into BVLC's master. Sorry I've let it fall so far behind! I do have a planned path for merge into BVLC/caffe (that involves less aggressive changes to Caffe), but that will be a little longer still.

**Comment by acgtyrant** [comment]
@longjon Do you get it done now? Thank you!

**Comment by acgtyrant** [comment]
Well, I will try to merge the #1976 into BVLC's master by myself.

**Comment by eswears** [comment]
Has anyone been able to merge #1976 into BVLC master yet? I was going to use longjon's fork for the FCN 32 work, but it's over 2200 commits behind BVLC.

**Comment by muthurengan** [comment]
Any idea which # should we merge with the BVLC's master to get rid of this Unknown layer type: Crop. I tried making the Longjon's branch and it looks to give us more errors

**Comment by gxdai** [comment]
Hi, I compiled the caffe-future branch, but I still got the same error. anyone knows how to fix it?

**Comment by danishrathore** [comment]
@gxdai I ran my python notebook from the caffe-future directory and got rid of the error.
