### ISSUE TITLE
Is Caffe compatible with PyPy?

### ISSUE THREAD

**Issue by alfredox10** [BVLC/caffe#2803]
I have just finished installing PyPy and added the numpy and PIL packages to my installation. But I am wondering now if Caffe can be interfaced with PyPy somehow, I haven't been able to find any info on how to do this?

**Comment by SlimeQ** [comment]
numpy and pypy do not play well together. i'mm not totally sure why, it probably has something to do with the way numpy/scipy optimizes things. ipso facto, no caffe w/ pypy. :'(

**Comment by alfredox10** [comment]
Really there is no Caffe compatability for pypy?!?! That's astonishing considering how slow a pure python implementation is. I am trying to speedup a pure python/caffe implementation that has a lot of overhead on image resizing, and I found out PyPy may be my best bet, so this is severly dissapointing :(.

Isn't there a way to just redirect the "make pycaffe" to the pypy source? I mean it's all python code from what I've checked, I don't know why this wouldn't be possible?

**Comment by SlimeQ** [comment]
you **can** do this... but from what i've read the pypy implementation of numpy is significantly slower. it's because of low level optimization stuff. the numpy/pypy implementation is incomplete.

[further reading](https://www.google.com/search?q=numpy+pypy&oq=numpy+pypy&aqs=chrome..69i57j0l5.1835j1j4&sourceid=chrome&es_sm=93&ie=UTF-8)

**Comment by alfredox10** [comment]
Thanks I've already installed it. I'm honestly not too worried about the numpy implementation, my program is not super dependent on it. I am more worried about not being able to run the entire program with pypy and have to split up the solution into two parts because caffe won't run on pypy :(

**Comment by SlimeQ** [comment]
i don't have the time to look right now to make sure, but i'm fairly certain the pycaffe wrapper is **critically dependent** on numpy and that means you'll have problems.

that being said.... have you simply tried running it on pypy? should be as simple as 
    $ pypy your_caffe_app.py

**Comment by alfredox10** [comment]
Yes I have, gives me error right at import caffe :p 
No problems running import numpy

I will try to strip all the extra stuff from it later today and run it with only the numpy stuff and see how runtime is affected. I've read that PyPy is supposed to be best for algorithms that do many loops and run for long periods of time. Mine does about 20K loops per iteration (per image it processes), so I think it would be a perfect candidate for getting some sweet speedup from PyPy :D

**Comment by lukeyeager** [comment]
See discussion at #2440.

**Comment by alfredox10** [comment]
I saw that but it doesn't actually explain how to run caffe with pypy

**Comment by shelhamer** [comment]
Caffe itself and pycaffe are fast and there is little overhead. As you noted, the lack of performance is in Python IO and image processing. If you find a fast Python module, or write an interface to fast IO code in C / C++ through Cython, then you can have a fast overall pipeline in Python. Binding pycaffe to pypy instead of vanilla Python in some way would have practically no effect -- the boost::python interface essentially operates at the library speed.

**Comment by longjon** [comment]
Closing as, as explained by @shelhamer, there doesn't seem to be anything to do here. It could be interesting to consider ways to integrate layer code executed with PyPy with Caffe, but it's likely that such cases will benefit more from better use of numpy or CUDA options, so that direction may not be worth the hassle.
