### ISSUE TITLE
I create a new cuda loss layer named DML_LossLayer.cu, but when i make all, there are some errors.

### ISSUE THREAD

**Issue by takecareofbigboss** [BVLC/caffe#2854]
![bug1](https://cloud.githubusercontent.com/assets/11883059/9051608/24d12354-3a8f-11e5-94bd-6fbd13b494c8.png)

I wonder how can i make all successfully, hope i can get ur reply. THX.

**Comment by seanbell** [comment]
It looks like you have a number of compiler errors.  For example lines 51, 52, 73, 100 (and probably others) have problems.  It's possible that you're missing header files and/or your code isn't in the right namespace.  Filing a github issue is not the right place to get help with this, since your problems are basic C++ problems.  Please close this issue.

Please see the note about filing issues: *Please do not post usage, installation, or modeling questions, or other requests for help to Issues. Use the caffe-users (https://groups.google.com/forum/#!forum/caffe-users) list instead.*

**Comment by takecareofbigboss** [comment]
@seanbell  Ok, i have closed it, and thank you for ur reply...
