### ISSUE TITLE
conversion of data to LMDB

### ISSUE THREAD

**Issue by dvartani** [BVLC/caffe#3019]
I am new to Caffe and I am trying to convert some portion of a dataset to LMDB format to input it to Caffe's prototxt file to start the training. However, it seems to create an empty lmdb folder.

i do the following from command line:

./build/tools/convert_imageset -gray=true -resize_height=256 -resize_width=256 DATA_ROOT DATA_ROOT/trainFiles.txt ~/Downloads/trainNew5_lmdb

DATA_ROOT is the path to the folder containing my dataset. The folder itself has 10 subfolders which iclude images of 10 different types of cars. and the trainFiles.txt has the path to each image within the folder. i.e,
DATA_ROOT-~/Documents/cars

inside trainFiles.txt looks like:
mazda/mazda_pos13_3361.png 6
maxima/maxima_pos15_2833.png 5
mazda/mazda_pos14_0894.png 6
jeep93/jeep93_pos15_3017.png 3
jeep93/jeep93_pos4_3099.png 3
jeep99/jeep99_pos3_3384.png 4
....

the reason why I believe that the created lmdb folder is empty is that from its properties I can see that it has 16.4kB which is very small compated to the size of my dataset which has 600000 images!! and also when I execute the command, it does not show any processing (unlike an example that I'v seen before). 

moreover, when I start training the network using the created lmdb folder, I get the following error: 

I0903 11:23:30.387845  2548 db.cpp:34] Opened lmdb /home/dvartani/Downloads/caffe/trainNew5_lmdb
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid

Any help would be very much appreciated

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

If you think you've found a bug:
> * What steps reproduce the bug?
* Can you reproduce the bug using the latest [master](https://github.com/BVLC/caffe/tree/master), compiled with the `DEBUG` make option?
* What hardware and operating system/distribution are you running?
* If the bug is a crash, provide the backtrace (usually printed by Caffe; always obtainable with `gdb`).

**Comment by annanurov** [comment]
I have a similar problem. What is a standard way to convert id data to lmdb?
The data files for mnist example are train-images.idx3-ubyte and train-labels.idx1-ubyte.
