### ISSUE TITLE
SGDSolver() and get_solver()

### ISSUE THREAD

**Issue by christopher5106** [BVLC/caffe#3033]
Dears,
I see two ways of calling the solver, but no much differences :
    solver = caffe.get_solver('examples/hdf5_classification/nonlinear_solver.prototxt')
    solver = caffe.SGDSolver('models/bvlc_reference_caffenet/solver.prototxt')
What is the difference between the 2 ? Where can I find the doc of the get_solver function ?
Thanks,

**Comment by seanbell** [comment]
The first (get_solver) allows you to specify the solver type in the prototxt.

The second (SGDSolver) is less reliable because if you specify a different solver type in the prototxt, then it will still use SGDSolver and not tell you that you have a mismatch.  I've made this mistake before and not realized it was using the wrong solver.

Maybe you should leave this issue open, for discussion.  See https://github.com/BVLC/caffe/pull/3024.

**Comment by christopher5106** [comment]
Ok thanks a lot for this answer :)

**Comment by ronghanghu** [comment]
Close as this seems to haven been resolved in #3024. All solvers are directly exposed to Python interface. For Matlab interface, this is going to be resolved in #3116 .
