### ISSUE TITLE
SoftmaxWithLoss layer doesn't work with blobs with more than 4 axes

### ISSUE THREAD

**Issue by YutingZhang** [BVLC/caffe#3097]
SoftmaxWithLoss is supposed to work with blobs of any number of axes, but it gives errors when more than 4 (not including) axes are used.
The issue is cause by Line 25 of loss_layer.cpp, which uses the legacy accessors on Blobs.

  CHECK_EQ(bottom[0]->num(), bottom[1]->num())
      << "The data and label should have the same number.";

It is quite easy to fix the issue in a hacky manner, but it may be good to come up with a clear solution for all the loss layers. 

Any ideas?

**Comment by longjon** [comment]
Right, see #2097 (wow! was that really one thousand issues ago?); I think that PR is just waiting because it might make sense to propagate that check to some individual loss layers. You're welcome to look into that and open another PR or argue that it makes sense as-is.

I'm closing this as the issue's already covered by #2097; continue discussion there.

**Comment by YutingZhang** [comment]
@longjon Lol. Exact 1000 issues ... Let's move back to #2097
