### ISSUE TITLE
conv and deconv shape inconsistent

### ISSUE THREAD

**Issue by prclibo** [BVLC/caffe#3119]
Hi, sometimes when I use a conv and a deconv layers with same params to process a blob, the output size is not the same with input as supposed.

For example, with kernel=4, pad=2, stride=2 and input_dim=21, conv outputs a size of (21 + 2 * 2 - 4) / 2 + 1 = 11. Deconv outputs a size of 2 * (11 - 1) + 4 - 2 * 2 = 20 != 21.

So just suggest to change https://github.com/BVLC/caffe/blob/master/src/caffe/layers/conv_layer.cpp#L20 as:

    const int output_dim = (input_dim + 2 * pad_data[i] - kernel_shape_data[i] + 1)
        / stride_data[i]; // (21 + 2 * 2 - 4 + 1) / 2 = 11

and https://github.com/BVLC/caffe/blob/master/src/caffe/layers/deconv_layer.cpp#L20 as:

    const int output_dim = stride_data[i] * (input_dim)
        + kernel_shape_data[i] - 2 * pad_data[i] - 1; // 2 * 11 + 4 - 2 * 2 - 1=21

I am a beginner of deep learning, so please let me know if I understand this wrong. thanks

**Comment by longjon** [comment]
The convolution size computation involves rounding, and must always, because the filter need not always perfectly tile the input. So there is no bijection between input and output sizes, and deconv can't be guaranteed to produce output of the same size as conv input. That's why there's, e.g., #1976, so you can avoid worrying about such issues.

I'm closing since there's not a real issue here, but feel free to discuss on caffe-users.

**Comment by jeffdonahue** [comment]
![](https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/TooManyPigeons.jpg/440px-TooManyPigeons.jpg)
