### ISSUE TITLE
Performance / compatibility testing before pull request

### ISSUE THREAD

**Issue by jreniecki** [BVLC/caffe#3120]
Could someone advice what configurations would be worth testing before sending pull request? Or maybe someone has already prepared such a summary? By configurations I mean a matrix of supported operating systems, compiler versions, BLAS and other libraries versions.

My team is planning to develop some performance improvements and we would like to make sure that we won't break anything or improve performance in one configuration while sacrificing another.
Thank you.

**Comment by lukeyeager** [comment]
You can turn on TravisCI for your own personal fork (like I did here - https://travis-ci.org/lukeyeager/caffe). That's somewhat helpful because it will run the tests for you automatically on a different machine.

A big caveat is that there aren't any GPUs on TravisCI build machines. So you should definitely run the tests locally with a GPU if your code changes anything related to CUDA/cuDNN.

**Comment by bhack** [comment]
There was an old dream to run CUDA basic tests on Travis with Ocelot at https://github.com/BVLC/caffe/issues/939
