### ISSUE TITLE
Silence layer deletes data during backprop

### ISSUE THREAD

**Issue by cvondrick** [BVLC/caffe#3151]
During Backward_* in the Slience layer, it performs the following operation when propagate_down[i] is set to true:

    caffe_set(bottom[i]->count(), Dtype(0), bottom[i]->mutable_cpu_data());

and similarly for the GPU.

Usually this code will not run because the Silence layer does not generally need backprop. However, if you force the network to do backprop, this will have the consequence of overwriting the bottom data blob with all zeros.

I think the correct behavior is to set the bottom *diff* to 0:

    caffe_set(bottom[i]->count(), Dtype(0), bottom[i]->mutable_cpu_diff());

Should this be changed?

Thanks!

**Comment by jeffdonahue** [comment]
Thanks for reporting @cvondrick.  You're right, this is a bug and should be fixed.  In practice though I think `propagate_down` should always be set to false since `SilenceLayer` won't be on a path to a loss (unless manually overridden with `propagate_down: true` in the `LayerParameter`, which would be odd), so this *probably* isn't affecting anyone...

**Comment by cvondrick** [comment]
I agree that is an odd case, but I think it can also be triggered by setting the entire network to do force_backward (which is how I found this bug).

**Comment by jeffdonahue** [comment]
You're right, that would trigger it as well. I'll send a PR with the fix in a second.  Thanks again!
