### ISSUE TITLE
Data layer prefetch queue empty.

### ISSUE THREAD

**Issue by gsxuan1127** [BVLC/caffe#3177]
I have met this issue, and I haven't find out how to solve it yet
![mistake](https://cloud.githubusercontent.com/assets/13956819/10421493/e7ffe928-70db-11e5-90c1-e87ed6401d53.png)

**Comment by ronghanghu** [comment]
Please do not post usage, installation, or modeling questions, or other requests for help to Issues.
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

That being said, `Data layer prefetch queue empty` means that your data loading is slower than net forward, so net has to wait for data IO to prepare next batch. This message is OK and you can ignore it
Note: the "Test interrupted" appears because you've pressed Ctrl+C (see ^C in your log)

**Comment by gsxuan1127** [comment]
Sorry. I pressed Ctrl+C because if I didn't do that, my system would shut down. It bothers me quiet a lot.

**Comment by ronghanghu** [comment]
Oh, I didn't expect system shutdown... Not sure if it is something related to #3174

**Comment by howtobeahacker** [comment]
Hi @gsxuan1127 
I think it is the problem of power supply, not the problem of Caffe. Pls see #3174.

**Comment by gsxuan1127** [comment]
Thank you very much.

**Comment by sajjo79** [comment]
I got same error and i checked that network is not able to read files. Instead of giving relative path in deeplab test prototxt, i provided absolute path and it worked.
