### ISSUE TITLE
I have  problem when I run the alexnet model and the cifar10  train_full model.

### ISSUE THREAD

**Issue by lji72** [BVLC/caffe#3307]
At first,I can run successfully until to the a to iteator=2000+,my server shut down.so reduce the batch_size in train_val.prototxt file.then I try again,it will be crash again.I cannot find the reasons.I can run cifar10 train-quick model success all the time, but using the cifar10 train_full model  I will fail when iteator = XXX .I think maybe my video memory is to small.(originally the server video memory only 16 M,but I have installed a tesla K40 ).If you give me some advices,I will be very grade to you.I have 16G memory,12 cores.5T hard device,GPU K40.I want to run the Alexnet.

**Comment by ronghanghu** [comment]
Server shutdown can be caused by multiple software or hardware reasons (e.g. out of CPU memory, GPU overheat, etc.). We don't have any evidence that indicates there is bug related to server shutdown in Caffe.

Please do not post usage, installation, or modeling questions, or other requests for help to Issues.
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
