### ISSUE TITLE
Caffe + cross validation

### ISSUE THREAD

**Issue by acpn** [BVLC/caffe#3327]
Hi Guys,

Anyone already do cross validation in caffe?

I'm do it through manual splits, but I dispense much time doing this.

Thanks!

**Comment by seanbell** [comment]
https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

There is no built-in mechanism for CV in caffe right now.  You need to script it or do it manually.  You could look into scikit-learn since they have some scripts for automating some parts of it, but I don't think you will gain much since you still need to set up caffe for each split.

**Comment by acpn** [comment]
ok, Thanks!
