### ISSUE TITLE
Question: Why does do classification training size have to be equal?

### ISSUE THREAD

**Issue by alfredox10** [BVLC/caffe#3339]
I have tried searching for an explanation but have found none. The general guidelines I've seen are that if you are training caffe for classification problem, say with 2 categories (positive, negative) that the training size for each has to be exactly equal. So for example if you have 100K positives, you need 100K negatives for best results, but why is this so? I understand it is also recommended to use 10% sample for testing, and if they are both equal then you get an even spread in the testing sample, however, if you have say 105K positives and 100K negatives, would this really affect accuracy that much? Or is there certain parameters that need to be adjusted for uneven training?

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

The simple answer is that when training, you are optimizing an objective function which directly depends on the distribution of training data.  Though, you should really consult intro machine learning tutorials and/or textbooks, since this is a general machine learning question, not a caffe question.
