### ISSUE TITLE
Linking error for libcaffe.so when running 'make'

### ISSUE THREAD

**Issue by krishkoushik** [BVLC/caffe#3343]
When running make, the following error occurs.

LD -o .build_release/lib/libcaffe.so
/usr/bin/ld: /usr/lib/libc.a(atexit.o): relocation R_X86_64_32 against `__dso_handle' can not be used when making a shared object; recompile with -fPIC
/usr/lib/libc.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make: **\* [.build_release/lib/libcaffe.so] Error 1

**Comment by Noiredd** [comment]
Exact steps were given as an answer to #2171. If these don't work, please post to the [caffe-users list][1] with more details on the problem.

Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
