### ISSUE TITLE
Compile fails using g++ 4.8 with "kernel launches from templates are not allowed in system files" 

### ISSUE THREAD

**Issue by AndrewLavin** [BVLC/caffe#337]
Build fails using g++ 4.8 with error message "kernel launches from templates are not allowed in system files". Using g++ 4.6 instead works.

Here is the compiler error.

/opt/nvidia/cuda/bin/nvcc -ccbin=/usr/bin/g++ -Xcompiler -fPIC -DNDEBUG -O2 -I/usr/include/python2.7 -I/usr/local/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -I./include -I/opt/nvidia/cuda/include -I/opt/intel/mkl/include -gencode arch=compute_20,code=sm_20 -gencode arch=compute_20,code=sm_21 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -c src/caffe/layers/pooling_layer.cu -o build/src/caffe/layers/pooling_layer.cuo
src/caffe/layers/pooling_layer.cu(164): error: kernel launches from templates are not allowed in system files

src/caffe/layers/pooling_layer.cu(171): error: kernel launches from templates are not allowed in system files

src/caffe/layers/pooling_layer.cu(291): error: kernel launches from templates are not allowed in system files

src/caffe/layers/pooling_layer.cu(298): error: kernel launches from templates are not allowed in system files

src/caffe/layers/pooling_layer.cu(305): error: kernel launches from templates are not allowed in system files

5 errors detected in the compilation of "/tmp/tmpxft_00006a5e_00000000-10_pooling_layer.cpp4.ii".
make: **\* [build/src/caffe/layers/pooling_layer.cuo] Error 2

**Comment by magicknight** [comment]
I got the same error and I switch to gcc 4.6 then it works

**Comment by RyanCarey** [comment]
It also corrects for me when switching to g++4.6

**Comment by fuglede** [comment]
Ran into the same problem using the g++-4.9 shipped with Debian Jessie. Downgrading to g++-4.6 from testing and using CUSTOM_CXX did the trick here as well.

**Comment by Jack-Foster** [comment]
Hi, I got the same problem using g++4.8 & 4.9 with Debian Jessie. I tried using g++-4.6 but it doesn't work neither because the recent version of caffe requests some new includes that do not exist for g++4.6.
For instance in .build_release/src/caffe/proto/caffe.pb.h line 7 there is :
#include <string>

This include exists for g++-4.8 but doesn't with g++-4.6.... 
I also tried to use the include from g++-4.8 using g++-4.6 for compilation but it (obviously) gives  weird errors : 

In file included from /usr/include/c++/4.8/bits/basic_string.h:39:0,
                 from /usr/include/c++/4.8/string:52,
                 from /usr/include/google/protobuf/stubs/common.h:41,
                 from .build_release/src/caffe/proto/caffe.pb.h:9,
                 from .build_release/src/caffe/proto/caffe.pb.cc:5:
/usr/include/c++/4.8/ext/atomicity.h: In function ‘_Atomic_word __gnu_cxx::__exchange_and_add(volatile _Atomic_word*, int)’:
/usr/include/c++/4.8/ext/atomicity.h:49:45: error: ‘__ATOMIC_ACQ_REL’ was not declared in this scope
/usr/include/c++/4.8/ext/atomicity.h:49:61: error: ‘__atomic_fetch_add’ was not declared in this scope
/usr/include/c++/4.8/ext/atomicity.h: In function ‘void __gnu_cxx::__atomic_add(volatile _Atomic_word*, int)’:
/usr/include/c++/4.8/ext/atomicity.h:53:38: error: ‘__ATOMIC_ACQ_REL’ was not declared in this scope
/usr/include/c++/4.8/ext/atomicity.h:53:54: error: ‘__atomic_fetch_add’ was not declared in this scope
Makefile:551: recipe for target '.build_release/src/caffe/proto/caffe.pb.o' failed

Could anyone give me some help on this ? Thx

**Comment by dgeo** [comment]
Tried here on debian jessie to install using nvidia-cuda-toolkit-6.4.14 from stretch instead of using gcc-4.6 from wheezy: seems to works for me™ here with a K80.
