### ISSUE TITLE
Unknown bottom blob 'data' 

### ISSUE THREAD

**Issue by n3011** [BVLC/caffe#3375]
I am training a vggnet 19 layers, But the problems is am getting the following errors and coulnt proceed
`F1124 16:05:28.878301 25702 insert_splits.cpp:35] Unknown bottom blob 'data' (layer 'conv1_1', bottom index 0)
`
top part of prototxt file
`
VGG_19_layers_prelu_train_val.prototxt
name: "VGG_ILSVRC_19_layers"
layer {
  name: "data"
  type: "Data"
  include {
    phase: TRAIN
  }
 transform_param {
    crop_size: 224
    mean_value: 104
    mean_value: 117
    mean_value: 123
    mirror: true
 }
 data_param {
    source: "data/ilsvrc12/ilsvrc12_train_lmdb"
    batch_size: 64
    backend: LMDB
  }
  top: "data"
  top: "label"
}
layer {
  name: "data"
  type: "Data"
  include {
    phase: TEST
  }
 transform_param {
    crop_size: 224
    mean_value: 104
    mean_value: 117
    mean_value: 123
    mirror: false
 }
 data_param {
    source: "data/ilsvrc12/ilsvrc12_val_lmdb"
    batch_size: 50
    backend: LMDB
  }
  top: "data"
  top: "label"
}
layer {
  bottom: "data"
  top: "conv1_1"
  name: "conv1_1"
  type: "Convolution"
  convolution_param {
    num_output: 64
    pad: 1
    kernel_size: 3
  } 
}

`

**Comment by seanbell** [comment]
Wait, how does this even load?  You have `layers` (i.e. the old V1 format) and then a string layer type (the new format).  This should fail at the point where the prototxt is parsed, since your file is invalid.  For example, it should have failed when trying to parse the `type` for your conv1_1 layer: https://github.com/BVLC/caffe/blob/master/src/caffe/proto/caffe.proto#L1106

You are using `layers` which uses the old enum type from V1, but then you use a string type for the type name for conv1.  You need to fix this to all be consistent.  It's currently a mix-and-match between V1 and the current version.

You should change all of the `layers {` to `layer {`, and change the enum types (e.g. `type: DATA`) to strings (e.g. `type: "Data"`).

**Comment by n3011** [comment]
@seanbell I have changed my prototxt to current version, but still getting the same errors...

**Comment by n3011** [comment]
@seanbell hi, when I run both training and testing together it works doesnt give any error, but when I delete all relevant TEST phase it give errors, Any idea?

**Comment by n3011** [comment]
I was doing some silly mistakes, I have forgot to change my solver.prototxt file. All are good now.

**Comment by smajida** [comment]
@n3011 having the same problem and it is not a mixture of V1 format and current one. how did you solve this problem? what do you mean changing solver.prototxt what did you change?

**Comment by n3011** [comment]
@smajida sorry for late reply. I just removed test parameter (test_iter and test_interval) from solver file.

**Comment by 2ros0** [comment]
an explanation of why removing the test parameters solves the problem would help :smiley:

**Comment by Gokulakrishnan-96** [comment]
> @smajida sorry for late reply. I just removed test parameter (test_iter and test_interval) from solver file.

I am getting the same error **F0821 11:27:20.151577 17919 insert_splits.cpp:29] Unknown bottom blob 'data' (layer 'conv1_1', bottom index 0)** and I don't have any parameters named (test_iter and test_interval) in any of my solver files. Please help me! @n3011

**Comment by Songxinlei** [comment]
> @smajida an explanation of why removing the test parameters solves the problem would help

do you know why removing the test parameters solves the problem ?
