### ISSUE TITLE
bug with max pooling

### ISSUE THREAD

**Issue by ravos** [BVLC/caffe#3399]
In the CPU implementation of max pooling layers 
(see https://github.com/BVLC/caffe/blob/master/src/caffe/layers/pooling_layer.cpp)

There is no boundary check on variables "hend" and "wend" for the max pooling case. Compare line 159-160 vs. the average pooling case line 202-205. Without such boundary check, the out of boundary indices will point to wrong places in bottom_data, causing the max pooling result to be inaccurate.

**Comment by ronghanghu** [comment]
I don't know what you mean...

In https://github.com/BVLC/caffe/blob/master/src/caffe/layers/pooling_layer.cpp#L157-L158, there is such checks 

            int hend = min(hstart + kernel_h_, height_);
            int wend = min(wstart + kernel_w_, width_);

so that `hend` never exceeds `height_`.

**Comment by jimmygod** [comment]
Thanks for the reply! Yes you are right. I was trying to debug a separate issue with the max pooling codes and the boundary check is not the source of the problem.

I have extracted the intermediate layer outputs from both the bottom and and top of a max-pooling layer and I was trying to verify the max-pooling procedure is functioning as my expectation. However the output of the max-pooling algorithm is correct for about 10% of the times and incorrect for the rest of the time (the output given by the max-pooling code is larger than the local maxima of each pooling region).

I replaced the max-pooling operations in 
https://github.com/BVLC/caffe/blob/master/src/caffe/layers/pooling_layer.cpp#L162-L174
by the corresponding average-pooling operations, i.e. something similar to
https://github.com/BVLC/caffe/blob/master/src/caffe/layers/pooling_layer.cpp#L206-L212
and everything works as expected. I was pretty sure the bottom data is exactly what I was expecting and the problem only exists if I try to do the max-pooling. I also tried the built-in max function max(a,b) and also the algebraic max function 0.5*(a+b) + 0.5*fabs(a-b) but the results are still wrong. Also it seems that when I do comparison between two Dtype variables (a > b) ? a:b, the returned result is (sometimes) neither a or b but some number larger than both a and b. 

I have been struggling on this bug for a few days. I would really appreciate if you can share your idea about what is going on.

**Comment by jimmygod** [comment]
So here is the detail of the bug that I have encountered.

First I trained a CNN using the cifar-10 dataset, pretty much as the caffe-turtorial. The first two layers are
```
name: "CIFAR10_quick_test"
input: "data"
input_shape {
  dim: 1
  dim: 3
  dim: 32
  dim: 32
}
layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  top: "conv1"
  param {
    lr_mult: 1
  }
  param {
    lr_mult: 2
  }
  convolution_param {
    num_output: 48
    pad: 0
    kernel_size: 5
    stride: 1
    weight_filler {
      type: "gaussian"
      std: 0.0001
    }
    bias_filler {
      type: "constant"
    }
  }
}
layer {
  name: "pool1"
  type: "Pooling"
  bottom: "conv1"
  top: "pool1"
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
  }
}
```

I tested the network using the first image (in jpg format) in the cifar-10 test dataset. With slight modification of the $cafferoot/python/classify.py, I was able to extract the output of each layer. So here is the 3x7 top-left corner of first feature after the layer conv1:
```
    1.5891    3.4922    3.6079    3.2632    1.6659   -1.2543   -0.6846
    3.1798    2.0100   -0.3708   -0.6938    1.0321    1.0418    1.1402
    6.1795    2.2500   -3.1681   -3.9305   -1.8181    0.7115    4.7941
```
Here is the 1x3 top-left corner after the max pooling (3x3 region, stride 2, pad 0):
```
6.26635265   5.72300577   6.0361948
```
None of them matches my expectation. In fact, when I examine each single blocks, the number outputed by the max-pooling process is always greater than the number within the corresponding box.

At first I thought it is because the max-pooling process is reading numbers from a wrong locations (therefore I submitted the original issue). So I modified the file pooling_layer.cpp in the following way:

I removed the iteration
```
            for (int h = hstart; h < hend; ++h) {
              for (int w = wstart; w < wend; ++w) {
                const int index = h * width_ + w;
                if (bottom_data[index] > top_data[pool_index]) {
                  top_data[pool_index] = bottom_data[index];
                  if (use_top_mask) {
                    top_mask[pool_index] = static_cast<Dtype>(index);
                  } else {
                    mask[pool_index] = index;
                  }
                }
              }
            }
```
and simply replaced by 
```
Dtype current = bottom_data[hstart * width_ + wstart];
top_data[pool_index] = current;
```
to read out the first elements in each 3x3 pooling region. It gives me exactly what I expected:
```
1.58909643   3.60793185   1.66592717
```
I have also tested the sum-pooling/average-pooling over the 3x3 region and all work as expected. However, whenever it comes to comparison, it gives me a wrong answer for most of the time. Therefore I loaded the top-left element out of each 3x3 pooling region
```
Dtype current = bottom_data[hstart * width_ + wstart];
```
and tested the following three one at a time to see whether the numeric comparison can be done properly
```
top_data[pool_index] = std::max<Dtype>(current, 0.0);
top_data[ph * pooled_width_ + pw] = (current > 0.0)? current:0.0;
top_data[ph * pooled_width_ + pw] = 0.5*current + 0.5*fabs(current);
```
Each one would give me the same following result, which is 
```
1.58909643   3.60793185   2.00318933
```
The first two numbers are correct but the third number is wrong (and larger than it should be). For the third case I think it has implicitly compared the current variable with 0.0 as well. So I modified this again
```
top_data[pool_index] = std::max<Dtype>(current, -0.1);
```
and surprisingly, the third result is shifted by a constant, which has nonlienar dependency on the second number that I have manually selected
```
1.58909643   3.60793185   1.95318913
```
The max-pooling process seems to be off the track as more comparison goes on and there is a small chance (about 5%-10%) that the final number (after 8 comparisons for a 3x3 max-pooling region) is correct. For the rest of the time, max-pooling would return a number larger than the local maxima.

**Comment by seanbell** [comment]
If you're consistently getting wrong answers, perhaps the problem is in the step where you extract a blob from the network?  If you are using the python interface, you need to make a copy from the blob when grabbing a reference.

I think it would be helpful if you could write a failing unit test, so that your problem is reproducible.  See https://github.com/BVLC/caffe/blob/master/src/caffe/test/test_pooling_layer.cpp for the current set of tests.  You could also write the test in Python (see [here](https://github.com/BVLC/caffe/tree/6eae122a8eb84f8371dde815986cd7524fc4cbaa/python/caffe/test)).

**Comment by ravos** [comment]
Thanks for the suggestions! I'll try to write a test case for this problem.

However I do not think it is the python problem because other pooling operations (single element extraction, average-pooling or any linear sums) are all working well as long as there is no numerical comparison involved.

**Comment by ravos** [comment]
I have tried to tweak the test cases but couldn't reproduce the error. So I have looked a little bit more into this issue from the other end. I tried to track how the first three numbers are propagating throughout the network. 
```
1.58909643   3.60793185   1.66592717
```
It turns out that during the forward calculation of this max-pooling process, the function 
```
void PoolingLayer<Dtype>::Forward_cpu(const vector<Blob<Dtype>*>& bottom,
      const vector<Blob<Dtype>*>& top)
```
in the pooling_layer.cpp has been called 10 times. For the first 5 times, the numbers being processed are
```
1.88147   2.03501   4.00638
```
and for the 6-10th times, the numbers being processed are
```
1.29672   5.18085   -0.674524
```
Note that the average of these two sequence is exactly the same as the original three numbers. It looks like my three input numbers generate two copies, each with a + or - offset (and the offset is different from elements to elements). The final output seems to be the average of these two copies, that is why we have the wrong output when we take the max with 0.0:
```
1.88147   2.03501   4.00638 -> 1.88147   2.03501   4.00638
1.29672   5.18085   -0.674524 -> 1.29672   5.18085   0.00000
```
and taking the average would lead to the weird numbers that I reported earlier
```
1.58909643   3.60793185   2.00318933
```
This is also consistent with the fact that average pooling, single element extraction and linear sum are all not affected.

I'm currently reading the net.forward() implementation and I would really appreciate it if someone can give me a little bit insight on (1) why the feedforward operation takes 10 call of the max-pooling function, where first 5 are identical and last 5 are identical? (2) what is the possible reasons of this +/- noise on the copies of the data?

**Comment by ravos** [comment]
I was able to locate why there are multiple calls to the max-pooling function. 

In the classify.py file, there was an input argument asking for oversampling or not. If oversampling is true, the algorithm would generate 10 copies of the same image
https://github.com/BVLC/caffe/blob/master/python/caffe/io.py#L349-L352

With oversampling ON, the classify.py and classifier.py will serialize the K*H*W feature map for you and generate an output equal to the average of all 10 trials. See
https://github.com/BVLC/caffe/blob/master/python/caffe/classifier.py#L93-L95

I guess this totally makes sense for the final layer. But if you are interested in the intermediate layer results, this could cause some confusion.
