### ISSUE TITLE
Issue with net.forward

### ISSUE THREAD

**Issue by mariolew** [BVLC/caffe#3414]
When using the pretrained Caffenet model with the python interface, I found that when I use
net.forward(end='conv1')
net.forward(start='pool1')
the model works fine and give reasonable output.

But when I change the deploy file from  
layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  top: "conv1"
  convolution_param {
    num_output: 96
    kernel_size: 11
    stride: 4
  }
}
layer {
  name: "relu1"
  type: "ReLU"
  bottom: "conv1"
  top: "conv1"
}
layer {
  name: "pool1"
  type: "Pooling"
  bottom: "conv1"
  top: "pool1"
  top: "pool1_mask"
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
  }
}

to

layer {
  name: "conv1"
  type: "Convolution"
  bottom: "data"
  top: "conv1"
  convolution_param {
    num_output: 96
    kernel_size: 11
    stride: 4
  }
}
layer {
  name: "relu1"
  type: "ReLU"
  bottom: "conv1"
  **top: "relu1"**
}
layer {
  name: "pool1"
  type: "Pooling"
  bottom: "conv1"
  top: "pool1"
  top: "pool1_mask"
  pooling_param {
    pool: MAX
    kernel_size: 3
    stride: 2
  }
}

It didn't work and output all zeros, I do think it should be an issue.

**Comment by shelhamer** [comment]
This is not an issue. In both cases you did not execute the `relu1` layer forward.

- In the first case `relu1` is in-place so that `conv1 top == relu1 bottom == relu1 top`. The net forward is incorrect since the output of `conv1` was never ReLU'd.
- In the second case you forward `conv1`, skip `relu1`, then forward `pool1` to the end. `relu1` forward is never executed so its top `relu1` stays all zeros and so zeros propagate to the end of the net.

See https://github.com/BVLC/caffe/blob/master/python/caffe/pycaffe.py#L72-L74 for the explanation of the `start` and `end` args that take layer names.

Please ask usage questions on caffe-users.  From [CONTRIBUTING.md](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md):
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by mariolew** [comment]
Sorry for the question, but I think pool1 has the bottom blob conv1 which is not relu1, so I think I can skip relu1 and get result, I am still a bit confused.

**Comment by shelhamer** [comment]
@mariolew thanks for following up [in this caffe-users thread](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/caffe-users/A96EIlp4--M/i5BYOlTVAgAJ). Please see the edit above and answer there.
