### ISSUE TITLE
Official model format prototxt reference for Caffe?

### ISSUE THREAD

**Issue by enoonIT** [BVLC/caffe#3454]
According to [this page](http://caffe.berkeleyvision.org/tutorial/net_layer_blob.html) "the model format is defined by the protobuf schema in [caffe.proto](https://github.com/BVLC/caffe/blob/master/src/caffe/proto/caffe.proto). The source file is mostly self-explanatory so one is encouraged to check it out"

But it seems some parameters are not very clear. For example, what is the difference between `lr_mult` (*The multiplier on the global learning rate for this parameter.*) and `blobs_lr` (*The ratio that is multiplied on the global learning rate. If you want to set the learning ratio for one blob, you need to set it for all blobs.*)?

Also, the first time you define `param {lr_mult=...}` is for filters and the second one is for the biases - but how would one understand this?

Is there a comprehensive reference on the model format used by Caffe?
Thanks,
FM

**Comment by shelhamer** [comment]
There have been several version of the model schema as we have improved it. `blobs_lr` is deprecated, as are all the other settings in the past `V1LayerParameter`: https://github.com/BVLC/caffe/blob/master/src/caffe/proto/caffe.proto#L1141-L1142. It hasn't been deleted outright so that Caffe can automatically update older models.

> Also, the first time you define param {lr_mult=...} is for filters and the second one is for the biases - but how would one understand this?

This could be better documented, but it is listed in the samples for `InnerProductLayer` and `ConvolutionLayer` in the [layer catalogue](http://caffe.berkeleyvision.org/tutorial/layers.html). Pull requests for more layer documentation, as found in the header comments or in our examples, are welcome.
