### ISSUE TITLE
could i use the hdf5 datalayer on .mat data in caffe as inout or not?

### ISSUE THREAD

**Issue by linalily** [BVLC/caffe#3479]
i have my input dataset in .mat format,with N*mdimensional, N samples with each 1*m dimensions.  my output is with P dimensions, namely a P dimensions vector. i want to do the regession work using caffe.
my question is: could i use the hdf5 format on my inout and output data of not?
i saw somebody said the hdf5 dataset need the input size to be 4D and labels to be 2D, i have no idea if the N*m dimensional input could use with hdf5.
thanks for your explaining, i am totally new to caffe...

**Comment by BlGene** [comment]
This is a usage question, so it should be asked on the mailing list. 

The question is not entirely clear, but I would recommend reshaping you data so that I can fit into the standard hdf5 4D size, in such a way that you can use the provided reshape layer to recover your original data shape. If this is not possible, just write your own reshape layer in python.

BR, Max

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
