### ISSUE TITLE
multi-sever access lmdb problem

### ISSUE THREAD

**Issue by taoari** [BVLC/caffe#3491]
I found that for a lmdb database, it is OK to access the same database with multiple Caffe instances from one server, but fails if I try to access it from multiple servers.

For example, suppose that ilsvrc12_train_lmdb and ilsvrc12_val_lmdb are stored in server A, I can train two caffe instances with this database on server A. But I fails to run another instance on sever B. Is this a problem with the LMDB library, or with Caffe implementation?

**Comment by xkszltl** [comment]
It is caused by the implementation of LMDB's lock. It uses the lock provided by OS instead of a file lock.

For example, on Windows the named lock is managed by Windows itself so it is impossible to be shared across servers.

There're some work around for this issue:
1. Use a single process for DB management and connect to it via socket.
2. Add a file lock in LMDB
3. Add a file lock in Caffe's db_lmdb.cpp
4. Switch to a better DB.

**Comment by taoari** [comment]
@xkszltl Thanks for the explanation, Do you have some ideas to circumvent this problem. For GPU clusters, it seems that each job is assigned to a different server. And make a copy of the database is time - and space-consuming.

**Comment by xkszltl** [comment]
I currently use the "space-consuming" method in most cases since hard disk is much cheaper than my time.

Sometimes I simply dump the whole DB into an 4-dim array and store in a file (just as a blob with batch_size=#img). This work around requires writing some code in caffe but it's achievable within 1 hour.

**Comment by taoari** [comment]
@xkszltl For caffe training, I think it should be default behavior to open LMDB without lock, can you point me to the position for setting this flag, since I am not quite familiar with the source code?

**Comment by xkszltl** [comment]
I just found something:
https://github.com/BVLC/caffe/pull/3527
https://github.com/BVLC/caffe/pull/3088
You can have a check.

BTW I don't think it should be a normal behavior. It is NOT safe. For example:
1. You run a script to generate the DB.
2. Training with caffe.
3. Accidently run step 1 again while training (Sometimes you use "up" arrow to scroll back in shell history, which may easily cause such mistake).
4. Oops!

Wanna do stupid thing without protection? Then explicitly claim it! LOL

**Comment by taoari** [comment]
@xkszltl Thank you very much.

**Comment by CarlosYeverino** [comment]
Hi @taoari ,

reading the lmdb without lock improves performance while training compared to training with lock?
