### ISSUE TITLE
Accessing the model parameters in cuda code: Segmentation fault

### ISSUE THREAD

**Issue by bhokaal** [BVLC/caffe#3564]
Hi,
     Apologies if it has been answered somewhere, I tried but could not find anything related to this. I need to access the values of model parameters of InnerProductLayer element by element. In the inner_product_layer.cu if I introduce such access code, I am getting segmentation fault error 

```
  const Dtype* weight = this->blobs_[0]->gpu_data();
  Dtype check = *(weight + this->blobs_[0]->offset(0,0,0,0));
  Dtype foo  = check* 12.32 ;
  LOG(INFO) << foo;
```
*** Aborted at 1453128689 (unix time) try "date -d @1453128689" if you are using GNU date ***
PC: @     0x7f40e31a9836 caffe::InnerProductLayer<>::Forward_gpu()
*** SIGSEGV (@0x704aa0000) received by PID 19316 (TID 0x7f40e4663a40) from PID 78249984; stack trace: ***
    @     0x7f40e2709d40 (unknown)
    @     0x7f40e31a9836 caffe::InnerProductLayer<>::Forward_gpu()
    @           0x40eca6 caffe::Layer<>::Forward()
    @           0x417361 caffe::InnerProductLayerTest_TestForward_Test<>::TestBody()
    @           0x436bd3 testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x42d557 testing::Test::Run()
    @           0x42d5fe testing::TestInfo::Run()
    @           0x42d705 testing::TestCase::Run()
    @           0x430a48 testing::internal::UnitTestImpl::RunAllTests()
    @           0x430cd7 testing::UnitTest::Run()
    @           0x40a6ca main
    @     0x7f40e26f4ec5 (unknown)
    @           0x40ab29 (unknown)
    @                0x0 (unknown)
Segmentation fault (core dumped)

When I comment out LOG(INFO) << foo; and replace with something else such as LOG(INFO) << "Hello Caffe"; Everything is fine again, which means the issue is not with LOG(INFO) and I can confirm that the issue crops up only when I am trying to access the model param elements by value

**Comment by seanbell** [comment]
Yes, you should expect a segmentation fault.  `this->blobs_[0]->gpu_data()` returns a pointer to GPU memory.  You cannot de-reference.  If you want to copy the value to main memory so that yuo can access it on the CPU, you need to call `this->blobs_[0]->cpu_data()`.

In the future, please ask the caffe-users mailing list for help with debugging.  See https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
