### ISSUE TITLE
caffe   db_lmdb.hpp:14] Check failed: mdb_status == 0 (2 vs. 0) No such file or directory

### ISSUE THREAD

**Issue by zhanpx** [BVLC/caffe#3639]
I ran  **compute_image_data.exe** to calculate the **mean.binaryproto** data of **cifar10_test_leveldb**, but program crashed at the beginning and reported the following errors:

> db_lmdb.hpp:14] Check failed: mdb_status == 0 (2 vs. 0) No such file or directory 

what about the reason for this issue, thanks.

**Comment by seanbell** [comment]
The file path to your lmdb database is most likely incorrect.  I'm closing the issue since this is a request for help with usage -- please use the mailing list for that.

From https://raw.githubusercontent.com/BVLC/caffe/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by annanurov** [comment]
Sorry guys, I still have this issue, even after converting idx file to mdb file. I do not see how to resolve this issue. Please explain in baby steps...

Thank you.
