### ISSUE TITLE
make clean error

### ISSUE THREAD

**Issue by datomnurdin** [BVLC/caffe#3646]
I got this error message when execute make clean command

```
/bin/sh: /bin/nvcc: No such file or directory
awk: syntax error at source line 1
 context is
	{exit  >>>  < <<<  7.0;}
awk: illegal statement at source line 1
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
/bin/sh: line 0: [: -gt: unary operator expected
```

Please advice. Thank you.

**Comment by seanbell** [comment]
Please read the [CONTRIBUTING](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) guidelines before posting issues:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

If you think you found a bug in caffe,
> * What steps reproduce the bug?
* Can you reproduce the bug using the latest [master](https://github.com/BVLC/caffe/tree/master), compiled with the `DEBUG` make option?
* What hardware and operating system/distribution are you running?
* If the bug is a crash, provide the backtrace (usually printed by Caffe; always obtainable with `gdb`).

**Comment by datomnurdin** [comment]
Solved. It's because misconfiguration in Makefile.config file.

**Comment by CallmeSunnyday** [comment]
Can you show me the way to solve it?I had the same problem, I tried to install the Xcode command tools, then 
```
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
/bin/sh: line 0: [: -gt: unary operator expected`
```
dispeared.
```
awk: syntax error at source line 1
 context is

    {exit  >>>  < <<<  7.0;}
awk: illegal statement at source line 1
```
But it still have an error.

**Comment by ShaggO** [comment]
I'm getting this error because my grep finds an empty match in the Makefile line 275. I fixed it by changing the last grep from "grep -o '[0-9.]*' to "grep -o '[0-9.]\{1,\}'
I however don't know if this breaks compatibility with other grep engines.
I'm using grep (BSD grep) 2.5.1-FreeBSD on OS X 10.10 (Yosemite).

**Comment by Shuai-Xie** [comment]
This may help. @CallmeSunnyday 

`xcode-select --install`

Command Line Tools 是Xcode的一款工具，可以在命令行中运行C程序。
