### ISSUE TITLE
Reason: image not found

### ISSUE THREAD

**Issue by datomnurdin** [BVLC/caffe#3655]
I got this kind of error message

```
Traceback (most recent call last):
  File "python-caffe.py", line 4, in <module>
    import caffe
  File "/Applications/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/Applications/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: dlopen(/Applications/caffe/python/caffe/_caffe.so, 2): Library not loaded: /usr/local/opt/boost/lib/libboost_system.dylib
  Referenced from: /Applications/caffe/python/caffe/_caffe.so
  Reason: image not found
```

Source code
```
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import caffe

caffe.set_mode_cpu()

net = caffe.Net('conv.prototxt', caffe.TEST)

im = np.array(Image.open('/ComputerVision/cat_gray.jpg'))
im_input = im[np.newaxis, np.newaxis, :, :]
net.blobs['data'].reshape(*im_input.shape)
net.blobs['data'].data[...] = im_input

net.forward()

net.save('mymodel.caffemodel')
```

Please advice. Thank you.

**Comment by seanbell** [comment]
This is the important line: `Library not loaded: /usr/local/opt/boost/lib/libboost_system.dylib`.  Boost is not linked properly.

I'm closing the issue since this is a request for help with installation -- please use the mailing list.

From https://raw.githubusercontent.com/BVLC/caffe/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
