### ISSUE TITLE
How to pass hdf5 labels to the cnn?

### ISSUE THREAD

**Issue by rslprpr** [BVLC/caffe#3658]
I have extracted multiple patches out of each image from my image dataset and then I computed feature descriptor for each patch. Then I converted the matrix of feature vectors to the hdf5 file. Finally I have two hdf5 files, one is table of feature vectors and the other is table of original image and its label.
  I want to pass this data to cnn in caffe to learn these features, and compute loss regression. But I don't understand how does the label corresponds to original images should be passed to the network. 
Would you please help me?

**Comment by SvenTwo** [comment]
I don't know what the "official" way is, but I usually just make it two input layers and make sure there's no shuffling, no starting offset randomization and no difference in their length. Then I do get corresponding inputs into the network.

Also, you may get more help asking in forums, since this is the caffe bugtracker.

**Comment by rslprpr** [comment]
Thank you

**Comment by seanbell** [comment]
This looks like a request for help.  From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
