### ISSUE TITLE
 libcudart.so.7.5: cannot open shared object file: No such file or directory-----but  it is exist in the path

### ISSUE THREAD

**Issue by andyyuan78** [BVLC/caffe#3685]
envy@ub1404envy:~/os_prj/github/_QA/VT-vision-lab/VQA_LSTM_CNN$ ll /usr/local/cuda-7.5/targets/x86_64-linux/lib/libcudart.so.7.5
lrwxrwxrwx 1 root root 19 Aug 15  2015 /usr/local/cuda-7.5/targets/x86_64-linux/lib/libcudart.so.7.5 -> libcudart.so.7.5.18*
envy@ub1404envy:~/os_prj/github/_QA/VT-vision-lab/VQA_LSTM_CNN$ echo $LD_LIBRARY_PATH
/usr/local/cuda-7.5/lib64:/home/envy/torch/install/lib:/usr/local/cuda-7.5/lib64:/home/envy/torch/install/lib:
envy@ub1404envy:~/os_prj/github/_QA/VT-vision-lab/VQA_LSTM_CNN$ ll /usr/local/cuda-7.5/lib64
lrwxrwxrwx 1 root root 24 Aug 15  2015 /usr/local/cuda-7.5/lib64 -> targets/x86_64-linux/lib/
envy@ub1404envy:~/os_prj/github/_QA/VT-vision-lab/VQA_LSTM_CNN$ export LD_LIBRARY_PATH=/usr/local/cuda-7.5/targets/x86_64-linux/lib:$LD_LIBRARY_PATHenvy@ub1404envy:~/os_prj/github/_QA/VT-vision-lab/VQA_LSTM_CNN$ sudo PYTHONPATH=/media/envy/data1t/github/caffe/python python prepro.py --input_train_json data/vqa_raw_train.json --input_test_json data/vqa_raw_test.json --num_ans 1000
Traceback (most recent call last):
  File "prepro.py", line 21, in <module>
    import caffe
  File "/media/envy/data1t/github/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/media/envy/data1t/github/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory

**Comment by seanbell** [comment]
No, it's not on your path, because you use `sudo`.  That resets path variables.  You need to pass the variables you need with something like `sudo LD_LIBRARY_PATH=$LD_LIBRARY_PATH PYTHONPATH=... <command> <args> ...`.

Also, you shouldn't be running the library as `root`.  The better solution is to fix your permissions and then not use `sudo`.

In the future, please check https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md before posting to github issues.  Relevant section:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
