### ISSUE TITLE
Rigster a new layer VideoDataLayer with error.

### ISSUE THREAD

**Issue by haohao900618** [BVLC/caffe#3710]
I add a new layer VideoDataLayer following the steps as https://github.com/BVLC/caffe/wiki/Development
but I encountered an error when I make the projection.
 
I register the VideoDataLayer in the cpp file as:
INSTANTIATE_CLASS(MyAwesomeLayer);
REGISTER_LAYER_CLASS(MyAwesome);

The make error as:
src/caffe/layers/video_data_layer.cpp: In function ‘boost::shared_ptr<caffe::Layer<Dtype> > caffe::Creator_VideoDataLayer(const caffe::LayerParameter&) [with Dtype = float]’:
src/caffe/layers/video_data_layer.cpp:489:   instantiated from here
src/caffe/layers/video_data_layer.cpp:489: error: cannot allocate an object of abstract type ‘caffe::VideoDataLayer<float>’
./include/caffe/data_layers.hpp:334: note:   because the following virtual functions are pure within ‘caffe::VideoDataLayer<float>’:
./include/caffe/layer.hpp:100 : note:    void caffe::Layer<Dtype>::Reshape(const std::vector<caffe::Blob<Dtype>*, std::allocator<caffe::Blob<Dtype>*> >&, const std::vector<caffe::Blob<Dtype>*, std::allocator<caffe::Blob<Dtype>*> >&) [with Dtype = float]
./include/caffe/layer.hpp:304: note:    void caffe::Layer<Dtype>::Forward_cpu(const std::vector<caffe::Blob<Dtype>*, std::allocator<caffe::Blob<Dtype>*> >&, const std::vector<caffe::Blob<Dtype>*, std::allocator<caffe::Blob<Dtype>*> >&) [with Dtype = float]
./include/caffe/layer.hpp:320: note:    void caffe::Layer<Dtype>::Backward_cpu(const std::vector<caffe::Blob<Dtype>*, std::allocator<caffe::Blob<Dtype>*> >&, const std::vector<bool, std::allocator<bool> >&, const std::vector<caffe::Blob<Dtype>*, std::allocator<caffe::Blob<Dtype>*> >&) [with Dtype = float]

Anyone knows what's wrong with it. Thanks a lot.

**Comment by sam-lass** [comment]
Did you solve this error ?

**Comment by sam-lass** [comment]
I am getting the similar error

**Comment by 96imranahmed** [comment]
Hey @haohao900618, do you happen to know how you resolved this? This error has been plaguing me all day!

**Comment by du0002in** [comment]
hi, @haohao900618 and @96imranahmed , have you solved the problem? I am facing the same here.

**Comment by 96imranahmed** [comment]
Hi @du0002in, so the reason I had this error was because I wasn't correctly implementing the delegate/call-back functions (and caffe kept throwing weird and wonderful C++ errors without telling me about it). Have a look at the functions that caffe expects to be implemented and make sure those match the function headers etc. :)

**Comment by haohao900618** [comment]
@du0002in you can check the function header of definition in *.h matching the header of implementation in *.cpp.

**Comment by du0002in** [comment]
@haohao900618 , @96imranahmed  thank you for the reply. it is indeed the real reason. I downloaded the new layer from online and did not check the header definitions explicitly. It turns out that the code defines the function headers in an abnormal way as compared to the caffe conventions and thus causing the wired errors.
