### ISSUE TITLE
/bin/ld: /usr/local/lib/libpython2.7.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by datomnurdin** [BVLC/caffe#3714]
I got this error message when after run it on Centos 7 (512MB).

> sudo make pycaffe

or 

>sudo make distribute

Error message

```
CXX/LD -o python/caffe/_caffe.so python/caffe/_caffe.cpp
/bin/ld: /usr/local/lib/libpython2.7.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libpython2.7.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
make: *** [python/caffe/_caffe.so] Error 1
```

Please advice. Thank you.

**Comment by seanbell** [comment]
If you are having trouble getting it to work on other operating systems (i.e. not Ubuntu), you could try using the docker image: https://github.com/BVLC/caffe/pull/3518 .  Otherwise, please ask installation questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by seanbell** [comment]
If you are having trouble getting it to work on other operating systems (i.e. not Ubuntu), you could try using the docker image: https://github.com/BVLC/caffe/pull/3518.

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
