### ISSUE TITLE
input blob memory type in gpu and cpu mode

### ISSUE THREAD

**Issue by cheer37** [BVLC/caffe#3768]
I saw many samples to deal with input blob.
There, mutable_cpu_data is used mostly even though it's running on gpu mode.
It's not that mutable_gpu_data should be used?
Thanks in advnace.

**Comment by BlGene** [comment]
It gets synced automatically. 

As this is not an issue, please close. I would recommend you try the mailing list for these questions.

**Comment by seanbell** [comment]
`mutable_cpu_data` returns a pointer for main memory for access by the CPU.  `mutable_gpu_data` returns a pointer for access by the GPU.  You cannot access GPU memory directly from the CPU; you have to explicitly transfer it (which is done automatically by the synced memory class if you use it correctly).  In the future, please ask for usage help on the mailing list, since it adds noise to the issue tracker.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
