### ISSUE TITLE
Travis CI builds fail due to boost

### ISSUE THREAD

**Issue by sasagalic-MSFT** [BVLC/caffe#3786]
It seems that Travis builds fail randomly due to some issue with Boost (boost include files cannot be found for some reason). I have tried adding apt-get for libboost-all-dev in Travis scripts but that did not help since build timed out.
Any ideas on what may be the issue and how to fix it?

**Comment by sasagalic-MSFT** [comment]
It seems that adding rm -rf $CONDA_DIR just before conda installation in travis_install.sh fixes the issue. I assume that issue may be with travis directory cache.
@shelhamer any ideas?

**Comment by anfeng** [comment]
CaffeOnSpark also faced the same problem. Our build is now working w/ "rm -rf $CONDA_DIR".

**Comment by shelhamer** [comment]
@sasagalic-MSFT I thought this was due to travis caching https://github.com/BVLC/caffe/blob/master/.travis.yml#L14-L20 but now it seems caching is only turned on for private/container builds: https://docs.travis-ci.com/user/caching/.

> rm -rf $CONDA_DIR

This looks like a valid workaround but fixing the travis configuration itself would be ideal.

**Comment by shelhamer** [comment]
See #3797 for a cherry-pick of the `rm -rf conda` workaround -- we can return to this after the ECCV deadline 03/14.

**Comment by shelhamer** [comment]
Closing this but #3798 notes the need to migrate to new travis configuration instead of including a workaround.
