### ISSUE TITLE
About how to apply the trained model in C++ environment

### ISSUE THREAD

**Issue by SawyerSun** [BVLC/caffe#3836]
Hey guys!

I‘ve trained my LeNet for classification. But I don't know how to load the model and test on the specific data in my C++ program. I feel confused and hope to helped. 
Thanks anyway.

**Comment by seanbell** [comment]
Here is an example: https://github.com/BVLC/caffe/tree/master/examples/cpp_classification

**Comment by seanbell** [comment]
I'm closing this question since it belongs on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
