### ISSUE TITLE
How to reconstruct a caffemodel by some parameters?

### ISSUE THREAD

**Issue by JackieTseng** [BVLC/caffe#3851]
I have met a problem that I have a sparse-matrix-stored-version neural network which means I have only some parameters of the network including its indexes like which layer does it belong and which location does it belong in each layer? How can I use these information and a `prototxt` to reconstruct the `caffemodel` by python. Thanks

**Comment by shaibagon** [comment]
just adding a link to the same question at [stackoverflow.com](http://stackoverflow.com/q/36103955/1714410).

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

Closing this since it's a usage question, and appears to be answered elsewhere.
