### ISSUE TITLE
How can I classify ImageNet in MATLAB and visualize intermediate filter matrix in the net

### ISSUE THREAD

**Issue by monjoybme** [BVLC/caffe#3875]
Hi,

I trained the imagenet model using my own dataset. Now I want to classify in MATLAB. What ever classification examples are given in the website all are in python. I also want to check intermediate filter matrix after first convolution. Please suggest how can I solve these two issues?

**Comment by seanbell** [comment]
While I haven't used the matlab interface, my understanding is that you can extract data from blobs.  From there you can write your own visualization using matlab image plotting commands.

From https://raw.githubusercontent.com/BVLC/caffe/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

Closing since this is a usage question (how to use the matlab interface).

**Comment by monjoybme** [comment]
How can I extract the output of layers in MATLAB? Any help will be
appreciated.






*Thanks and Regards,*
*Monjoy Saha*
