### ISSUE TITLE
matcaffe installation error

### ISSUE THREAD

**Issue by balakg** [BVLC/caffe#3941]
I am getting linking errors when I run 'make matcaffe':

Undefined symbols for architecture x86_64:
  "_mxArrayToString", referenced from:
      get_solver(int, mxArray_tag**, int, mxArray_tag const**) in caffe_.o
      ...
  "_mxCreateCellMatrix_700", referenced from:
      str_vec_to_mx_strcell(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) in caffe_.o
  
I saw other posts on this issue before, and I made the appropriate adjustment to this line in Makefile.config:

LIBRARY_DIRS := $(PYTHON_LIB) /usr/local/lib /Applications/MATLAB_R2016a.app/bin/maci64 /usr/lib

but I still get these compile warnings. I am using Matlab 2016a, and am on OS X 10.11. Any help would be appreciated.

**Comment by albanie** [comment]
Just in case this proves useful to someone else, the issue was resolved for me by changing the `LIBRARY_DIRS` order to:

    LIBRARY_DIRS := /usr/local/lib $(MATLAB_DIR)/bin/maci64 $(PYTHON_LIB) /usr/lib 

**Explanation**
The problem was that I had defined

    PYTHON_LIB := /usr/lib

previously in the Makefile, which consequently appeared before the `maci64` directory in the path. Depending on your `libpythonX.X.so` location, the `/usr/lib` part of `LIBRARY_DIRS` may then become redundant.

**Comment by nastyad** [comment]
Thanks for posting the solution!
