### ISSUE TITLE
blob data_at and diff_at seem unsafe

### ISSUE THREAD

**Issue by D-X-Y** [BVLC/caffe#3952]
in blob.hpp , data_at  and diff_at function call offset function, but offset function only check n <= num(), rather n < num().

**Comment by ajtulloch** [comment]
It's overloaded actually - there are layers that run stuff like:

```
bottom_diff += bottom[0]->offset(0, 1);
```

which is safe even for {1, 1, x, y} blobs as long as you don't access bottom_diff (since it points past the end).

Perhaps what would be valuable is a DCHECK_GE/DCHECK_LT around the actual access in `data_at`, `diff_at`? That will catch the underlying accesses to bad memory.
