### ISSUE TITLE
python pycaffe: caffe.params.Data does not have hdf5 defined

### ISSUE THREAD

**Issue by weiliu620** [BVLC/caffe#3996]
caffe.params.Data.LMDB is defined, but not hdf5. It looks hdf5 was defined for c/c++ but not defined for python interface. 

Also, did some investigation in pycaffe:
dp = getattr(caffe_pb2, 'DataParameter')

dp.LMDB and dp.LEVELDB are there, but no hdf5.

**Comment by ajtulloch** [comment]
This comes from https://github.com/BVLC/caffe/blob/master/src/caffe/proto/caffe.proto#L629

You can use an HDF5DataLayer directly from pycaffe though. Does that work for you?

**Comment by weiliu620** [comment]
Thanks for the reply, do you have a minimal example for using this layer in pycaffe? The [ipython notebook example ](https://github.com/BVLC/caffe/blob/master/examples/01-learning-lenet.ipynb) looks outdated: "from caffe import layers as L" gave me error. 

Thanks again.

**Comment by ddfabbro** [comment]
Make sure to have `net_spec.py` and that `__init__.py` contains
```
from .net_spec import layers, params, NetSpec, to_proto
```
if you want to import it directly as `from caffe import layers as L`, otherwise you can simple import `layers` with `from caffe.net_spec import layers as L`.

On how to use it on python, you can define a HDF5 Data layer as `caffe.net_spec.layers.HDF5Data()`.

Example:
```
>>> from caffe import NetSpec, layers
>>> net = NetSpec()
>>> net.data = layers.HDF5Data()
>>> print(net.to_proto())
layer {
  name: "data"
  type: "HDF5Data"
  top: "data"
}
```
