### ISSUE TITLE
GPU support for Intel graphics 5500

### ISSUE THREAD

**Issue by AlexTS1980** [BVLC/caffe#3997]
I'm trying to run caffe with cuda7.5 on gpu. deviceQuery returns 'no CUDA-capable device is detected' error. Any way to do it with the graphics card I specified?

**Comment by seanbell** [comment]
I'm pretty sure that Intel graphics cards don't support CUDA.  You should first check whether CUDA is supported, before trying to use GPUs with caffe.

You can either use CPU-only, or try and get the opencl branch to run (not sure what the state of that is).

I'm closing this because it's an installation question, which doesn't belong on the Issues page.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by naibaf7** [comment]
@AlexTS1980 
Try https://github.com/BVLC/caffe/tree/opencl
All networks should work with that as well, as long as you stay within the limits of your GPUs memory.
