### ISSUE TITLE
caffe model convert error

### ISSUE THREAD

**Issue by xzqjack** [BVLC/caffe#4014]
I tried to convert pretrained Alex caffe model into mxnet model with `convert_model.py` but an error existed. The imported prarameters shape of conv2 should be 256x96x5x5 rather than 256x48x5x5. By looking up some caffe example code, i found that there is a group parameter in caffe-python interface.
But i still have no idea about how to extract all parameters of group parameter of caffe.

Any hint will be appreciated!

**Comment by seanbell** [comment]
If `group: 2` (which is the default for AlexNet), then you would expect the weights to have shape 256x48x5x5 for conv2.  If you read the original AlexNet paper you will notice that the architecture is divided in two pieces, so that the number of input connections in each layer is half.  Please ask the mailing list for help with usage/modeling.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
