### ISSUE TITLE
Undefined function or variable 'caffe_'.

### ISSUE THREAD

**Issue by HLinn** [BVLC/caffe#4064]
I have compiled the caffe solution successfully. When I run the matlab demo,I get the error:
''Invalid MEX-file 'G:\caffe-MS\caffe-master\Build\x64\Release\matcaffe\caffe_.mexw64,Can't find the specified module'',

**Comment by seanbell** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> When reporting a bug, it's most helpful to provide the following information, where applicable:
> 
> * What steps reproduce the bug?
> * Can you reproduce the bug using the latest [master](https://github.com/BVLC/caffe/tree/master), compiled with the `DEBUG` make option?
> * What hardware and operating system/distribution are you running?
> * If the bug is a crash, provide the backtrace (usually printed by Caffe; always obtainable with `gdb`).

**Comment by bwiltshire** [comment]
I'm having the same issue on Windows 7 SP 1, VS Pro 2013 (12.0.40629.00 Update 5) and Matlab 2016a.

I have tested Release and Debug builds using CPU. I'm using the CommonSettings.props as per the instructions and altering:

```
<CpuOnlyBuild>true</CpuOnlyBuild>
<UseCuDNN>false</UseCuDNN>
<MatlabSupport>true</MatlabSupport>
<MatlabDir>C:\Program Files\MATLAB\R2016a</MatlabDir>
```

Solution builds with no errors.

I then add the built Matcaffe path to Matlab and attempt to run caffe.version and this is the output in Matlab command window:

```
caffe.version
Invalid MEX-file
'd:\caffe-windows\Build\x64\Debug\matcaffe\+caffe\private\caffe_.mexw64':
The specified module could not be found.

Error in caffe.version (line 5)
version_str = caffe_('version');
```

**Comment by astalring** [comment]
I got the same problem, I guess that the reason is that the gflag library is not renamed. Look in FixGFlagsNaming.bat. Unfortunatly does  that just help a Little, when that was fixed I got a missing entry point when loading caffe_:
MATLAB.exe' (Win32): Loaded 'D:\workspace\caffe_windows\caffe-windows\Build\x64\Debug\matcaffe\+caffe\private\libgflags-debug.dll'. Cannot find or open the PDB file.
'MATLAB.exe' (Win32): Loaded 'D:\workspace\caffe_windows\caffe-windows\Build\x64\Debug\matcaffe\+caffe\private\libgfortran-3.dll'. Module was built without symbols.
Exception thrown at 0x00007FFA979A4AB0 (ntdll.dll) in MATLAB.exe: 0xC0000139: Entry Point Not Found.
'MATLAB.exe' (Win32): Loaded 'D:\workspace\caffe_windows\caffe-windows\Build\x64\Debug\matcaffe\+caffe\private\libgcc_s_seh-1.dll'. Module was built without symbols.
