### ISSUE TITLE
Fine Tunning of GoogLeNet Model

### ISSUE THREAD

**Issue by ashutosh3308** [BVLC/caffe#4072]
I did the fine tunning but the results are not promising. I am only getting the accuracy of 50% after 1000 iterations. My training dataset has 3k images validation has 1k images and evaluation has 1k images. I set the base_lr to 0.001 and max_itr to 10000. Is this accuracy normal or did I do something wrong? I can also share what changes I did in the files, if needed.

**Comment by seanbell** [comment]
Closing since this is a usage/modeling question.  Please use the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
