### ISSUE TITLE
wired bug for 1x1 conv kernel with value one, it changed the original input blob ? 

### ISSUE THREAD

**Issue by jerryking234** [BVLC/caffe#4077]
I recently met a weird problem with convolution.  
I load a  blob from HDF5 data layer and normal is a blob 1x3xhxw  with value in 0 to 1. 

as follows I first slice the blob into three and then split the first blob to  "normal_c1_a"  "normal_c1_b", 

For  "normal_c1_a",  I use a value 1,  1x1 kernel to do convolution yielding "normal_c1_n".  This suppose to give the same results as "normal_c1_b".  However,  I found the results are some how 4 times larger than  "normal_c1_b".  The results are so wired and I can not figure out any reason for that. 

In addition,  when I change the stride of Convolution to 2.  It performs exactly copying the corresponding values. Is this a bug for caffe ?  

layer { bottom: "normal" top: "normal_c1" top: "normal_c2" top: "normal_c3" type: "Slice" 
  slice_param {axis: 1 slice_point: 1 slice_point: 2}
}
layer { bottom: "normal_c1" top: "normal_c1_a" top: "normal_c1_b" name: "test" type: "Split"}

layer { bottom: 'normal_c1_a' top: 'normal_c1_n' name: 'reset' type: "Convolution"
  convolution_param { num_output: 1 kernel_size: 1 stride: 1
  weight_filler { type: "constant"  value: 1  }
  bias_term: false }
}

'''
I0501 00:07:46.785307 24484 solver.cpp:244]     Train net output #0: normal_c1_b = -0.885672
...

I0501 00:07:47.864508 24484 solver.cpp:244]     Train net output #64092: normal_c1_n = -3.54269 
...

Any ideas ? 

Thanks

**Comment by jerryking234** [comment]
BTW  I use a cpu only machine to perform such operation

**Comment by seanbell** [comment]
Please ask questions about how to use caffe on the mailing list.  If it turns out that this is a bug in caffe, please prepare a minimal test case showing the error, and re-open the issue (or file a new one).  Thanks!

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
