### ISSUE TITLE
Caffe fails to use GPU in a new thread

### ISSUE THREAD

**Issue by jpiabrantes** [BVLC/caffe#4178]
I have a Caffe neural network and I want to do forward pass (using the GPU) in the network without blocking the main thread. I am using python, I tried using threading and multiprocessing. Multiprocessing is giving me an error and threading is using the CPU even though I am asking it to use the GPU.
Here's my code:

```python
class ThreadingWorker(threading.Thread):
    def __init__(self):
        super(ThreadingWorker,self).__init__()
        param = config()
        self.model = param.model
        self.net = caffe.Net(self.model.deployFile, self.model.caffemodel, caffe.TEST)

    def run(self):
        input_data = np.random.rand(1,4,self.model.width,self.model.height)
        start = time()
        self.net.forward(data=input_data)
        print 'Success, took %f seconds' % (time()-start)      

class MultProcessingWorker(mp.Process):
    def __init__(self):
        super(MultProcessingWorker,self).__init__()
        param = config()
        self.model = param.model
        self.net = caffe.Net(self.model.deployFile, self.model.caffemodel, caffe.TEST)

    def run(self):
        input_data = np.random.rand(1,4,self.model.width,self.model.height)
        start = time()
        self.net.forward(data=input_data)
        print 'Success, took %f seconds' % (time()-start)      

class NormalWorker(object):
    '''Using the main thread, no parallelization is being used here'''
    def __init__(self):
        param = config()
        self.model = param.model
        self.net = caffe.Net(self.model.deployFile, self.model.caffemodel, caffe.TEST)

    def run(self):
        input_data = np.random.rand(1,4,self.model.width,self.model.height)
        start = time()
        self.net.forward(data=input_data)
        print 'Success, took %f seconds' % (time()-start)   

p = NormalWorker()
p.run()

>> Success, took 0.34 seconds

thread = ThreadingWorker()
thread.start()   

>> Success, took 3.54 seconds

p = MultProcessingWorker()
p.start()

>> F0519 11:43:01.104552  6985 syncedmem.hpp:18] Check failed: error == cudaSuccess (3 vs. 0)  initialization error
*** Check failure stack trace: ***
```

**Comment by seanbell** [comment]
If you are using multiple processes, you need to make sure that you load the net entirely in the worker process.  The `__init__` function gets called in the main process.  I believe you want to initialize the net in the `run` method which runs in the worker process.  I would just put everything in the `run` method and not use an `__init__` method (unless you need to pass lock objects or something).

Also, it looks like you're failing to call `Process.__init__()` (https://docs.python.org/2/library/multiprocessing.html#process-and-exceptions).  Subclasses of `Process` need to call that if you override the constructor.

Regarding the multithreading option, since only one thread can run at a time, and the interface blocks on the GPU and doesn't release the GIL, I would expect that the multithreading option isn't any faster than just calling the function in the main thread and waiting.

**Comment by jpiabrantes** [comment]
@seanbell Thanks for your answer. I already moved the initialization to the `run` and I obtained the same results I was getting with the `threading` it seems that caffe is using the CPU instead of the GPU. I was calling `Process.__init__()` by running this line `super(MultProcessingWorker,self).__init__()`. How can I solve this?

**Comment by ajtulloch** [comment]
the `Caffe::mode_` variable that controls this is thread-local, so ensure you're calling `caffe.set_mode_gpu()` in each thread before running any Caffe functions. That should solve your issue.

**Comment by mad-saurabh** [comment]
I think this is a problem with cuda putting a mutex for a process ID. So when you use the multiprocessing module another subprocess with a separate pid is spawned. And it is not able to access because of the mutex for the GPU.

A quick solution which I found to be working is using the threading module instead of the multiprocessing module.

**Comment by wincle** [comment]
@ajtulloch Thank you so much! It worked!
