### ISSUE TITLE
Error when installing protobuf  on Mac.

### ISSUE THREAD

**Issue by XiaXuehai** [BVLC/caffe#4183]
OS X Installation said:
```
#with Python pycaffe needs dependencies built from source
brew install --build-from-source --with-python -vd protobuf
brew install --build-from-source -vd boost boost-python
# without Python the usual installation suffices
brew install protobuf boost
```
and I used
brew install --build-from-source --with-python -vd protobuf`

then I got this:

```
==> Patching
patching file src/google/protobuf/descriptor.h
==> ./configure --disable-debug --disable-dependency-tracking --prefix=/usr/local/Cellar/protobuf/2.6.1 --with-zlib
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir'
Errno::EACCES: Permission denied - /Users/xxh/Library/Logs/Homebrew/protobuf
1. raise
2. ignore
3. backtrace
4. irb
5. shell
```

**Comment by seanbell** [comment]
Do you have permission problems in your homebrew installation?

What happens when you run `brew doctor` ?

I'm closing this since it looks like a problem with your system, and not with caffe.  Please ask for installation help on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by XiaXuehai** [comment]
THX.
