### ISSUE TITLE
Command line classifier failed due to libpng version

### ISSUE THREAD

**Issue by zdong01** [BVLC/caffe#4184]
I compiled Caffe with Anaconda Python (with libpng16). When I run command line classifier:  

---------- Prediction for ../web-cnn/test_labeled_images/AND18.png ----------
libpng warning: Application was compiled with png.h from libpng-1.6.13
libpng warning: Application  is  running with png.c from libpng-1.2.49
libpng error: Incompatible libpng version in application and library
F0519 22:17:15.609571 13943 classification.cpp:251] Check failed: !img.empty() Unable to decode image ../web-cnn/test_labeled_images/AND18.png
*** Check failure stack trace: ***
    @     0x7f181d546b9d  google::LogMessage::Fail()
    @     0x7f181d54abb7  google::LogMessage::SendToLog()
    @     0x7f181d548a39  google::LogMessage::Flush()
    @     0x7f181d548d3d  google::LogMessageFatal::~LogMessageFatal()
    @           0x407254  main
    @       0x380ae1ed5d  (unknown)
    @           0x4041c9  (unknown)
./classifier.sh: line 15: 13943 Aborted                 $CLASSIFIER $NET $MODEL $MEAN $LABELS $TEST_IMAGE_PATH/$image

I have already set PATH and LD_LIBRARY_PATH to libpng16. When I run:
        libpng-config --ldflags --cflags
print:
        -L/work/zhang/common/tools/anaconda2/lib -lpng16
        -I/work/zhang/common/tools/anaconda2/include/libpng16
Both set to libpng16.

But there is still version conflict.

Any idea?

**Comment by seanbell** [comment]
Closing since this looks like a problem with your libraries / installation, and not with caffe.  Please ask for help with installation on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
