### ISSUE TITLE
What's the advantage of  the reference CaffeNet in comparison with the AlexNet?

### ISSUE THREAD

**Issue by Phoebe007** [BVLC/caffe#4202]
The reference CaffeNet is a modified Alexnet by switcing the order of pooling and normalization layers. I don't understand why they did like that. What the advantage of the reference caffenet ?
Thanks!!

**Comment by seanbell** [comment]
This was an accident; it was supposed to be the same as AlexNet.  This was one of the first reference implementations, so it's difficult to get everything right.  There isn't any difference in performance.

**Comment by seanbell** [comment]
Also, please ask questions like this on the mailing list, thanks!

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by shelhamer** [comment]
As a further note, there is a slight computational advantage to CaffeNet: the max pooling precedes the local response normalization (LRN) so that the LRN takes less compute and memory. However they are virtually indistinguishable, as @seanbell notes, and Caffe includes both CaffeNet and the exact AlexNet architecture.

**Comment by Phoebe007** [comment]
Thank you for you help. And I am so sorry for making that mistake!
