### ISSUE TITLE
Caffe run error: no CUDA-capable device is detected

### ISSUE THREAD

**Issue by zdong01** [BVLC/caffe#4225]
I compiled Caffe with CUDA and cuDNN, when I run `make runtest`: 

F0527 08:43:32.401912 27274 syncedmem.hpp:18] Check failed: error == cudaSuccess (38 vs. 0)  no **CUDA-capable device is detected**

I am running on AWS g2.2xlarge instance, Ubuntu 14.04, CUDA 7.5, cuDNN v5. 

Graphic card: 

00:02.0 VGA compatible controller: Cirrus Logic GD 5446
00:03.0 VGA compatible controller: NVIDIA Corporation GK104GL [GRID K520] (rev a1)

Any idea?

**Comment by martyychang** [comment]
Hi @zdong01 can you paste the output from the [`deviceQuery` sample](http://docs.nvidia.com/cuda/cuda-samples/#device-query)? NVIDIA has instructions for [building that sample](http://docs.nvidia.com/cuda/cuda-samples/#building-samples).

**Comment by bipul21** [comment]
Have you tried restarting. Post installation or upgrades. A simple restart fixed the issue for me.

**Comment by seanbell** [comment]
It looks like you don't have drivers and/or CUDA set up correctly, or you got unlucky with a g2.2xlarge machine that doesn't have a working GPU (rare, but happens).  Please follow up on the mailing list, since this is a installation/setup question.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
