### ISSUE TITLE
SIGFPE in caffe::Blob<float>::Reshape(std::vector<int, std::allocator<int> > const&) ()

### ISSUE THREAD

**Issue by moi90** [BVLC/caffe#4310]
I'm getting an SIGFPE when trying out the GoogLeNet that is bundled with NVIDIA digits:

```
I0614 11:45:20.968870  4811 net.cpp:163] Top shape: 24 1024 (24576)
I0614 11:45:20.968878  4811 layer_factory.hpp:76] Creating layer loss1/classifier
I0614 11:45:20.968888  4811 net.cpp:110] Creating Layer loss1/classifier
I0614 11:45:20.968895  4811 net.cpp:477] loss1/classifier <- loss1/fc
I0614 11:45:20.968904  4811 net.cpp:433] loss1/classifier -> loss1/classifier

Program received signal SIGFPE, Arithmetic exception.
0x00007ffff78a48f1 in caffe::Blob<float>::Reshape(std::vector<int, std::allocator<int> > const&) ()
   from /data1/mschroeder/Thesis/caffe-fast-rcnn/.build_release/tools/../lib/libcaffe.so
```

The only place I can imagine a SIGFPE can occur in `Reshape()`, is the following loop:

```
for (int i = 0; i < shape.size(); ++i) {
    CHECK_GE(shape[i], 0);
    CHECK_LE(shape[i], INT_MAX / count_) << "blob size exceeds INT_MAX";
    count_ *= shape[i];
    shape_[i] = shape[i];
  }
```

`shape[i]` is greater or equal to 0, `count_` is multiplied with `shape[i]`. If `shape[i]` is 0 before the last repetition of the loop, `count_` will be 0 and `INT_MAX / count_` will fail. But I don't see how `shape[i]` could be 0, so maybe the check should be `CHECK_GT` ?

**Comment by ajtulloch** [comment]
I think there are a few places in blob.cpp where the CHECK's are a bit too permissive. There are a few cases where this gets abused (IIRC in pooling layer we advance the data pointer to one past the end of the array via an offset() call, but since we don't read from it it's safe). I think cleaning this up would be valuable - in this code, shape[i] should be non-zero right? Or at least, one easy improvement to the error message would be a CHECK(count_); in the loop to ensure that we don't divide by zero.

**Comment by moi90** [comment]
Yes, I think shape[i] should be non-zero. If one dimension is zero, the array can't hold any data.

**Comment by shelhamer** [comment]
Shape can be 0 as in #4101. I don't know what this DIGITS issue is, but please ask at the downstream project.

This might be caused by an input of too small a size, and that could be caught by Caffe to give a more meaningful error.
