### ISSUE TITLE
Question about a wiki page

### ISSUE THREAD

**Issue by ExonRen** [BVLC/caffe#4330]
I noticed [Ubuntu-14.04-VirtualBox-VM](https://github.com/BVLC/caffe/wiki/Ubuntu-14.04-VirtualBox-VM) and I only have one question now, that is, **why did the author install CUDA** now that it was in a virtual machine and **he himself knew that there should be no graphic card available in a vm**? He even addressed not to install the nVIDIA driver when running the CUDA installation runfile.

**Comment by seanbell** [comment]
Maybe you should ask the authors? https://github.com/BVLC/caffe/wiki/Ubuntu-14.04-VirtualBox-VM/_history

Also, I think this discussion is better suited for the caffe mailing list, since it's a question about installation help.  Feel free to update the wiki once you resolve your questions.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by ExonRen** [comment]
@seanbell I'm sorry for my misuse of the GitHub Issue. I used to post a question like "does TensorFlow support something" in TF Issue and was closed at once too, but I only realized the right role of Issue after your reply. Thank you and I'll put up my questions in the caffe-users list.
