### ISSUE TITLE
vision_layers.o not being built

### ISSUE THREAD

**Issue by uidar** [BVLC/caffe#4331]
I am compiling tool depending on caffe.
It throws error:
No rule to make target 'caffe/include/caffe/vision_layers.o', needed by '_gpudm.so'

Caffe compiled nicely, but no vision_layers.o in place.

**Comment by seanbell** [comment]
There is no vision_layers file.  There used to be a header with that name in an older version of caffe.  I'm closing this issue since it isn't related to the current master version.

Please follow up on the mailing list if you are still having problems.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
