### ISSUE TITLE
Run Segmentation on multiple threads

### ISSUE THREAD

**Issue by eevolvelab** [BVLC/caffe#4335]
Hi, 

I am trying to run segmentation on four different threads. 

First two thread successfully completes the segmentation however, other two ends with exception:

I0621 02:01:14.645334   600 net.cpp:241] pool1 does not need backward computation.
I0621 02:01:14.645344   600 net.cpp:241] relu1_2 does not need backward computation.
I0621 02:01:14.645352   600 net.cpp:241] conv1_2 does not need backward computation.
I0621 02:01:14.645361   600 net.cpp:241] relu1_1 does not need backward computation.
I0621 02:01:14.645370   600 net.cpp:241] conv1_1 does not need backward computation.
I0621 02:01:14.645380   600 net.cpp:241] data_input_0_split does not need backward computation.
I0621 02:01:14.645393   600 net.cpp:284] This network produces output pred
I0621 02:01:14.645431   600 net.cpp:298] Network initialization done.
I0621 02:01:14.645445   600 net.cpp:299] Memory required for data: 1287634208
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 537968303
I0621 02:01:17.696367   600 upgrade_proto.cpp:620] Attempting to upgrade input file specified using deprecated V1LayerParameter: /home/ubuntu/crfasrnn/python-scripts/TVG_CRFRNN_COCO_VOC.caffemodel
Exception in thread Thread-4:
Traceback (most recent call last):
  **File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ubuntu/crfasrnn/python-scripts/crfasrnn_demo2.py", line 58, in getSegmented
    net = caffe.Segmenter(MODEL_FILE, PRETRAINED)
  File "/home/ubuntu/crfasrnn/caffe/python/caffe/segmenter.py", line 18, in __init__
    caffe.Net.__init__(self, model_file, pretrained_file, caffe.TEST)
MemoryError**
 

Is my system has no memory to run four threads? What causes this error to be thrown?

Thank you in advance for your answer.

**Comment by seanbell** [comment]
You probably want to use multiple _processes_, not threads.  Each process should load its own copy of the net.  The caffe python interface is not thread-safe.

**Comment by ssrinivasan** [comment]
Is having own copy of net for each process a strict requirement , since the net is read-only at this point of time . Is it possible to rely on fork for parallelism . I am working on a sample app which serves result from segmentation model . It utilizes copy on write and loads the net in the master once and serve memory references for the forked children . I am having trouble starting this setup in a web server setting . I get **Memory Error** when i try to initialize the model .

**Comment by seanbell** [comment]
There is no way to share a net across processes.  You need to load the net after the child process starts.

Please follow up on the mailing list, since this is more a question about python and how to do multiprocessing, and not really about BVLC/caffe.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
