### ISSUE TITLE
CaffeConfig.cmake for Windows 

### ISSUE THREAD

**Issue by JieZou1** [BVLC/caffe#4399]
I have successfully compiled and generated Caffe at Windows. Thanks.

Now, I am trying to consume Caffe in C++. I am using cmake to generate VS sln files. However, I am not able to find CaffeConfig.cmake. There is a CaffeConfig.cmake.in under cmake\Templates folder. Any idea how I can generate CaffeConfig.cmake from this CaffeConfig.cmake.in for Caffe at Windows? Many thanks.

**Comment by willyd** [comment]
This CaffeConfig.cmake is a template that will be installed by the Caffe CMake build. You can have a look a this PR https://github.com/BVLC/caffe/pull/3990 for a working (though not stable) CMake build. Alternatively you can write your own FindCaffe.cmake and use that in your own CMakeLists.txt files. Please note that you will need to link to object files and not the caffe library since the linker will remove any unused symbols.

**Comment by willyd** [comment]
The CMake build is now the only supported build system on windows. Please try the build and report if the install CaffeConfig.cmake works for you.
