### ISSUE TITLE
matcaffe with octave

### ISSUE THREAD

**Issue by twmht** [BVLC/caffe#4401]
hi,

I found that caffe support Octave interface https://github.com/BVLC/caffe/blob/master/matlab/CMakeLists.txt

I installed `octave` and `liboctave-dev` and uncomment `MATLAB_DIR := /usr/local` in `Makefile.config`.

but it still said that it required matlab binary

```
(caffe) tumh@tumh-Predator-G9-592:~/caffe$ make matcaffe
make: /usr/local/bin/mexext: Command not found
MEX matlab/+caffe/private/caffe_.cpp
/bin/sh: 1: /usr/local/bin/mex: not found
Makefile:508: recipe for target 'matlab/+caffe/private/caffe_.' failed
```

Is that Octave interface still an ongoing feature?

**Comment by shelhamer** [comment]
While the CMake build mentions Octave in lieu of MATLAB, to my knowledge Caffe is only MATLAB compatible. However if you want to try with Octave you will need to build with CMake since the Makefile build only supports MATLAB.

For further installation help please post on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
