### ISSUE TITLE
Is Caffe's reported Accuracy reliable? (Accuracy mismatch)

### ISSUE THREAD

**Issue by Coderx7** [BVLC/caffe#4404]
I recently tried to get the confusion matrix for one of my trained models, to see how precise it is.  I downloaded this script and fed my model. 
To my astonishment, The accuracy calculated by the script, is very different than the one, `Caffe` reports.   

I have used [this script][1] to calculate the confusion matrix, this however, reports the accuracy as well, **the problem is the accuracy reported by this script is way different that the one reported by `Caffe`!**    
For example `Caffe` reports the accuracy lets say for `CIFAR10`, as 92.34%, while, when the model is fed to the script to calculate confusion matrix and its accuracy, it results in for example something like 86.5%.!  

**Which one of these accuracies are the correct one, and can be reported in papers or compared with the results of other papers such as those [here][2]** ?

I also saw something weird again, I trained two identical models, with only one difference, that being one used `xavier`, and the other used `msra` for initialization.     
The first one reports an accuracy of 94.25 and the other reports 94.26 in caffe. when these models are fed to the script I linked above, for confusion matrix computations. their accuracies were 89.2% and 87.4% respectively!  
Is this normal? what is the cause for this? msra? 

I really dont know if the accuracies reported by caffe are truth-worthy and reliable. I'd be grateful if anyone could shed some light on the matter.  

P.N: 
The accuracy in the script is calculated as ([complete script][1]) :

      for i, image, label in reader:
            image_caffe = image.reshape(1, *image.shape)
            out = net.forward_all(data=np.asarray([ image_caffe ]))
            plabel = int(out['prob'][0].argmax(axis=0))
    
            count += 1
            iscorrect = label == plabel
            correct += (1 if iscorrect else 0)
            matrix[(label, plabel)] += 1
            labels_set.update([label, plabel])
    
            if not iscorrect:
                print("\rError: i=%s, expected %i but predicted %i" \
                        % (i, label, plabel))
    
            sys.stdout.write("\rAccuracy: %.1f%%" % (100.*correct/count))
            sys.stdout.flush()
    
        print(", %i/%i corrects" % (correct, count))

Which imho is OK and correct. the number of correct predictions, divided by the total number of instances in the dataset.  

 

  [1]: https://gist.github.com/axel-angel/b2af7d980eb217a0af07
  [2]: http://www.google.com/url?q=http%3A%2F%2Frodrigob.github.io%2Fare_we_there_yet%2Fbuild%2Fclassification_datasets_results.html%2343494641522d313030&sa=D&sntz=1&usg=AFQjCNHlNXPmKuvC0R2w8MsWikjC8O3nuQ

**Comment by Coderx7** [comment]
OK, Thanks to dear God, I found the reason. The reason for the mismatch between Caffe generated accuracy and the accuracy generated by the script in question, was solely because of mean-subtraction, which was done in Caffe, and not in the script.
[This](https://gist.github.com/Coderx7/830ada70049ebbe7d7dc75101645b2f9) is the modified version of script which takes this into account and hopefully everything is just fine.

**Comment by seanbell** [comment]
Glad you figured it out.  Yes, the user is expected to perform mean subtraction, channel swapping, and any other rescaling etc.  There is a `Transformer` class in `caffe.io` to do this for you.  Example usage: https://github.com/grokstyle/caffe-grokstyle/blob/af04325bfeadacbddd5a0392568bdf36ce97bfda/python/caffe/classifier.py#L30

Closing this since it's a usage question.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by jeiks** [comment]
Hello, I have a question and I would like that someone help me.

I trained a caffe model (classification problem) and tested it with a lmdb dataset composed by 1236 samples. The accuracy reported by caffe was exactly 0.905. And here is my problem.
I created a script to get all net's outputs and labels. Using it, I saw that I had 1118 correct outputs: 1118/1236 = 0.904530744337. I din't understand why caffe have rounded it, because it always shows format %.6f.
But I saw this error: to get this accuracy I need 118.58 correct samples ((correct/total) * total = 0.905*1236). I dont have half samples (0.58) in a classification problem.

Then I tested the net with another dataset composed by 980 samples. The caffe accuracy was 0.759375. To get this accuracy I need 0.759375*980 = 744.1875 samples. A fractional samples number again.
Using the my label script, I got 745 correct outputs: 745/980 = 0.760204081633

I have a classification problem and I think that I could never get these caffe accuracy values. Could someone explain me, please?

Thank you!
