### ISSUE TITLE
Use images as lalbel for segemtation

### ISSUE THREAD

**Issue by AlexandraAMC** [BVLC/caffe#4502]
Hello,

I am developing a CNN to do segmentation of biomedical images. 

As an input I have 572x572x3 images and my labels are the images with the ground truth. 
The problem is, at the end my output is smaller than the label image and the Euclidean loss layer can not work. 
I have this error: 
F0722 10:43:42.478071 10809 euclidean_loss_layer.cpp:12] Check failed: bottom[0]->count(1) == bottom[1]->count(1) (980000 vs. 981552) Inputs must have the same dimension.

I tried to use a reshape layer but I cannot get the exact same size .. 

Does anyone have an idea how to solve this problem ?

**Comment by vgenty** [comment]
What I do is make sure deconvolution produces an image _larger_ than my ground truth label, then I use crop layer to downsize it to the appropriate dimension.

**Comment by AlexandraAMC** [comment]
Ok thank you

**Comment by shelhamer** [comment]
Please ask usage questions on our mailing list.

For image-to-image tasks like this Caffe includes coordinate mapping and cropping tools to match the input and output images so that they are aligned and have the same dimension. There are exampled at http://fcn.berkeleyvision.org.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
