### ISSUE TITLE
Learning Caffe ~ Seeking for Further Insights 

### ISSUE THREAD

**Issue by wzleong** [BVLC/caffe#4514]
Hi, 

I am a beginner in Caffe. Would be nice if I could get some further insights and tips about Caffe. 
I have gone through the examples for MNIST and the demo for py-faster-rcnn. 
From my understanding, the "default" methodology to train in Caffe are:
i) preparing our own dataset 
--> Question 1. Do I need to always convert it lmdb? 
--> Question 2. Say I am interested in detection, after I prepared my dataset (sets of image for training and testing -listed in a .txt file) with my annotations (ground truths of the 4 boundary box coordinates) how can I link them to be the input into the network? 
ii) Defining my own network architecture (training, solver and testing) in the prototxt files. 
--> If I plan to design my own layers, I have to implement in both CUDA and C++? 
--> Do I need to edit the makefiles?  
iii) Finally using the trained model and deploying it. But how can I get the weights of the trained model and interfacing it? 

Thanks 
WZ

**Comment by seanbell** [comment]
Hi, welcome to using Caffe!  Please check out the BVLC page (http://caffe.berkeleyvision.org/), tutorials (http://tutorial.caffe.berkeleyvision.org/), and/or the mailing list.  I'm closing this issue, since it's a usage question, and not a code issue.  Please follow up with questions on the mailing list, thanks!

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
