### ISSUE TITLE
Fit bvlc_reference_caffenet for 64x64 pixel input images

### ISSUE THREAD

**Issue by roishik** [BVLC/caffe#4517]
Halo,

I'm really new in the deep learning field.

I'm trying to change the 'caffenet_train_val_1.prototxt' file so it will fit for training with my own data.  There is any easy way to fit the code so it will fit to 64x64 pixels images input? (instead of manually change every layer parameters).

Thank you very much!

**Comment by Apple-Of-Eden** [comment]
Hey roishik,

I don't see any file called caffenet_train_val_1.prototxt, but I assume you mean the `models/bvlc_reference_caffenet/train_val.prototxt` file. I don't know if the python wrapper has some nice way of modifying the .prototxt file for your needs, but I tend to doubt it (someone please correct me if I'm wrong). 

But to get a 64x64 input, isn't it just a matter of removing the `crop_size: 227` lines and providing your own lmdb that has 64x64 images? However, since the original images are 227x227 (after cropping), then the default kernel sizes are probably larger than would be ideal for you. Still, I think it should at least semi-work without modifying kernel sizes. Anyone else think so?

Side note, I think usage questions are supposed to be asked in the google group here: https://groups.google.com/forum/#!forum/caffe-users

**Comment by seanbell** [comment]
Please ask usage questions on the mailing list, thanks!

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
