### ISSUE TITLE
How to turn off multithreading?

### ISSUE THREAD

**Issue by KevinLucidyne** [BVLC/caffe#4525]
@pavlejosipovic I'm trying to debug an issue that's causing a crash and the multithreading is complicating my troubleshooting.  How do I turn off multithreading in the Windows branch, VS2013?

**Comment by seanbell** [comment]
Windows is currently unsupported  (i.e. nobody is maintaining that code right now).  My understanding is that they are looking for maintainers.  Until then, you'll need to figure out the issue yourself, or use linux which is supported.

I'm closing this since it's a usage question.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
