### ISSUE TITLE
This example requires LevelDB and LMDB; compile with USE_LEVELDB and USE_LMDB.

### ISSUE THREAD

**Issue by dxiaosa** [BVLC/caffe#4536]
When I execute './examples/mnist/create_mnist.sh'  with MINST data, error occurs, like this:
dxiaosa@dxiaosa:~/caffe-master$ ./examples/mnist/create_mnist.sh
Creating lmdb...
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0728 11:18:34.832721 28578 convert_mnist_data.cpp:144] This example requires LevelDB and LMDB; compile with USE_LEVELDB and USE_LMDB.
*** Check failure stack trace: ***
Aborted (core dumped)
so, what happened?

**Comment by seanbell** [comment]
> so, what happened?
Read the error message -- you need to `compile with USE_LEVELDB and USE_LMDB`

I'm closing this issue since it's an installation/debug question -- please follow up on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:
> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by fishfreetaken** [comment]
I'm the same problem, do you deal with it?

**Comment by fishfreetaken** [comment]
mkdir build
cd build
cmake ..
make all
make install
make runtest

do as up ,you must didn't do these!!!!

**Comment by lugui2009** [comment]
I am new to caffe.I also encouter the same error.I don't know how to solve it .can you help me .Thank you.
@dxiaosa
