### ISSUE TITLE
H5public.h file not found

### ISSUE THREAD

**Issue by bond992** [BVLC/caffe#4571]
When "make all" command executed I get this message:
   CXX src/caffe/layers/hdf5_output_layer.cpp
In file included from src/caffe/layers/hdf5_output_layer.cpp:3:0:
src/caffe/layers/hdf5.h:24:22: fatal error: H5public.h: No such file or directory
compilation terminated.
Makefile:574: recipe for target '.build_release/src/caffe/layers/hdf5_output_layer.o' failed
make: **\* [.build_release/src/caffe/layers/hdf5_output_layer.o] Error 1

Does anybody know what is wrong?

**Comment by zwets** [comment]
`H5public.h` and all other hdf5 headers are located in `/usr/include/hdf5/serial` (at least on Ubuntu, libhdf5-dev version 1.8.16). The fix is to add that directory to the `INCLUDE_DIRS` directive in `Makefile.config`, so it becomes:

    INCLUDE_DIRS := $(PYTHON_INCLUDE) /usr/local/include /usr/include/hdf5/serial

I suggest this change be added to `Makefile.config.example` in `master`.

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
