### ISSUE TITLE
Importing two modules using different caffe instances

### ISSUE THREAD

**Issue by AlexTS1980** [BVLC/caffe#4586]
This is more of a Python problem, but I did not get a good solution on MSE.

So I use two packages, both depend on caffe: crf-rnn and hed, but, of course, they have different implementation of caffe. What can I do to import both? Essentially I will need to use first crf-rnn and then hed. I realize I can just put all images through crf-rnn, store them and then run with hed, but it is kind of a hassle. If you could help with running caffe for each of the modules, that would be cool.

**Comment by wadefelix** [comment]
import multiprocessing

**Comment by lukeyeager** [comment]
You're right - this is a question about Python, not Caffe.

As I'm sure you found on SE, typically the recommended solution for this problem is to rename one package or the other. If Caffe's Python never referenced itself, then it would be easy to rename the top-level folder and/or place the folder inside of another module - either of which would solve your problem.

But as you can see from the discusson on https://github.com/BVLC/caffe/pull/4466, the BVLC devs aren't in favor of making that sort of a change. I actually agree with them in principle, but it is inconvenient for you in this case.

Feel free to add your own opinion to that discussion if you like. But you should close this issue.

**Comment by AlexTS1980** [comment]
OK I solved it in the most blunt way possible: first used crf-rnn on all (1000+) images and stored the output, and then ran hed in a different script. Straightforward? Maybe. But it works.
