### ISSUE TITLE
prediction in multi-thread has problems?

### ISSUE THREAD

**Issue by KangBing** [BVLC/caffe#4595]
I use caffe/examples/cpp_classification to predict. I meet a strange problem in multi-thread. When I create `Classifier` in thread A and use `Classifier->Classify()` in thread A, it predicts very fast. But when I create `Classifier` in thread A and use `Classifier->Classify()` in thread B, it predicts very slow. Is that a feature of caffe, or I use prediction in a wrong way?

**Comment by flx42** [comment]
Hello @KangBing 

This is because the Caffe context is a TLS variable:
https://github.com/BVLC/caffe/blob/master/src/caffe/common.cpp#L15-L20
So, if a new threads tries to use Caffe, it will initialize a new context (and initialize cublas/curand), making it slow the first time.
I published a small code sample showing heavily multithreaded inference server using the Go programming language: https://github.com/NVIDIA/gpu-rest-engine
My solution in this case is to patch caffe to make the context settable for any thread, then any thread can perform inference efficiently: 
https://github.com/flx42/caffe/commit/1a5187a259a5cb31fef0e091bfe4795b268b1238

**Comment by KangBing** [comment]
@flx42 Thanks for the answer.

**Comment by xiaoluojun** [comment]
你好，@KangBing，我也遇到这个问题，请问您是怎么解决的。
