### ISSUE TITLE
Why LSTMParameter code isn't merged?

### ISSUE THREAD

**Issue by sohey-miyazaki** [BVLC/caffe#4629]
I want to use LSTM layer.
So I try to make prototxt within LSTM layer.
But terminal says "Message type caffe.LayerParameter has no field named lstm_param".

And I checked source code. 
I found that lstm_param's code is not in "caffe.proto".
(lstm_param's code is in junhyukoh/caffe-lstm repository)

Why LSTMParameter code isn't merged in main repository?
Is some reason existed?

**Comment by shelhamer** [comment]
It is merged, and has been in Caffe `master` since #3948 in April.

For usage questions about LSTMs + recurrence and other modeling questions, please post on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by sohey-miyazaki** [comment]
Thanks for your information.
I understand the situation.
