### ISSUE TITLE
How hard is caffe to create layers, train and test network in python without writing prototxt?

### ISSUE THREAD

**Issue by thesby** [BVLC/caffe#4724]
I have used caffe more than 1 year. It's a greate deep learning framework. But there is not very easy to prepare data and  to train a network with data generator like tensorfow. And I want to know how hard is it to do deep learning with caffe fully in python, which means that we don't need to create any prototxt files or shell files.

**Comment by happyharrycn** [comment]
This is definitely possible by writing a wrapper on pycaffe. Here is an [example ](https://github.com/classner/barrista)

**Comment by shelhamer** [comment]
Or consider any of our notebook examples, like this: http://nbviewer.jupyter.org/github/BVLC/caffe/blob/master/examples/01-learning-lenet.ipynb

In my own work I make use of Caffe purely from Python, and I handle data through Python data layers like [this segmentation layer](https://github.com/shelhamer/fcn.berkeleyvision.org/blob/master/voc_layers.py). The Python net specification does still serialize a prototxt, but the point is that you don't have to write it yourself.

Since this is a usage question, it is better asked on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by thesby** [comment]
Thank you very much. @happyharrycn @shelhamer 
That's what i need, thank you.
