### ISSUE TITLE
Multi label output with caffe

### ISSUE THREAD

**Issue by shengyudingli** [BVLC/caffe#4744]
I want to apply caffe to handwritten text recognition, the number of labels of a training image is more than one, so I want to modify caffe that it can output serveral predictions for a input iamge, what should I do? Thank you!

**Comment by Noiredd** [comment]
A simplest idea would be to have multiple classifiers. Consider starting a thread on the [caffe-users list][1]. All usage, installation, or modeling questions, or other requests for help should go there instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
