### ISSUE TITLE
load libcaffe fault！！！

### ISSUE THREAD

**Issue by hukangrong** [BVLC/caffe#4761]
load libcaffe fault, Couldn't found libcaffe.vcxproj!

**Comment by Noiredd** [comment]
Please provide more details on your issue. If this is an usage/compilation problem, do post to [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
