### ISSUE TITLE
Python kernel is dead when I switch to GPU mode and run net.forward()

### ISSUE THREAD

**Issue by ssqNo1** [BVLC/caffe#4826]
the corresponding code:
```
caffe.set_device(0)  # if we have multiple GPUs, pick the first one
caffe.set_mode_gpu()
net.forward()
```
All things work well in the cpu mode.
p.s. classification.cpp works fine in gpu mode

**Comment by XiaoMaol** [comment]
Hey @ssqNo1: 

How did you solve the problem? I just ran into the same issue. Could you please give me some help? 

Thank you so much!

**Comment by naibaf7** [comment]
I think calling `set_mode_gpu` BEFORE `set_device` is the correct way to go about this.

**Comment by XiaoMaol** [comment]
Hey @naibaf7: 

Thank you so much for replying. I have tried what you suggested, but it still failed. 
The operation system I am using is 
```
Linux odroid 3.10.103-124 #1 SMP PREEMPT Tue Oct 11 11:51:06 UTC 2016 armv7l armv7l armv7l GNU/Linux
```
I have download my caffe though ck-caffe, and the full discriptions of the issue is here: 
https://github.com/dividiti/ck-caffe/issues/118
and @psyhtest suggested that you may have better ideas? Can you take a look at the problem?

The Caffe I download has no problem in cpu mode, but died on the gpu mode.
