### ISSUE TITLE
To save GPU memory by re-using.

### ISSUE THREAD

**Issue by thesby** [BVLC/caffe#4875]
Required GPU memory is allocated layer by layer before the network running. But some memory is wasted if used memory can be used again. For example, if the network contains 4 conv layers , conv1, con2, con3, conv4, and the memory used is as follow: 
conv1 > conv2 > conv3 > conv4,
we can just run conv3 memory on con1 memory, and conv4 memory on conv2. So a lot of memory will be saved by re-using.
Could caffe take a consideration about this ?
Thank you.

**Comment by naibaf7** [comment]
@thesby 
This is indeed a possibility, but it would have to be a quite complex directed acyclic graph analyzer;
You need at least 2 buffers per branch (the DAG can branch), and then the respective sizes of the required buffers have to be figured out with a max-cut algorithm in the graph (or similar, haven't worked out all the details yet).
So yes it's definitely worth looking into it, but keeping in mind this only works for the forward pass (backward pass/training requires all data blobs from the forward pass, however a similar trick could be applied for the backward pass only) and has some technical difficulties (branching, multi-GPU, in-place layers).

**Comment by flx42** [comment]
This is similar to the register allocation problem in compilers. There is a project that already does that: https://github.com/facebook/fb-caffe-exts
They have a good explanation in the README.
I don't think it's that hard, the most challenging part is probably having a clean integration in Caffe, especially since it's only for the inference path as @naibaf7 said.
