### ISSUE TITLE
Memory leaking ?

### ISSUE THREAD

**Issue by thesby** [BVLC/caffe#4915]
If I use CUDA, then the CPU_ONLY are not defined, and the following code allocates both CPU and GPU memory to ptr. So the problem comes.  `malloc` wil override the `cudaMallocHost`. The momory of `cudaMallocHost` will leak.

```C++
inline void CaffeMallocHost(void** ptr, size_t size, bool* use_cuda) {
#ifndef CPU_ONLY
  if (Caffe::mode() == Caffe::GPU) {
    CUDA_CHECK(cudaMallocHost(ptr, size));
    *use_cuda = true;
    return;
  }
#endif
  *ptr = malloc(size);
  *use_cuda = false;
  CHECK(*ptr) << "host allocation of size " << size << " failed";
}

inline void CaffeFreeHost(void* ptr, bool use_cuda) {
#ifndef CPU_ONLY
  if (use_cuda) {
    CUDA_CHECK(cudaFreeHost(ptr));
    return;
  }
#endif
  free(ptr);
}
```

**Comment by dhruvkakadiya** [comment]
@thesby No, code will not allocate memory two times if CPU_ONLY is not defined because of **"return;"** statement in the code. As soon as code will allocate memory on the GPU, it will return from there and it will not execute further **malloc** instructions so there is no issue of memory leakage.

**Comment by OranjeeGeneral** [comment]
I am running Caffe git clone from a week ago. On CentOS 6.4 and I am seeing a disturbing increase in memory usage that eventually causes a SIGBUS error when trying to convert a LMDBCursor data block into a string the memcpy seems to fail:

Stacktrace Is this:

** SIGBUS (@0x7ff7476d0000) received by PID 88262 (TID 0x7ffa03fff700) from PID 1198325760; stack trace: ***
    @       0x3351c0f500 (unknown)
    @       0x3351489b13 (unknown)
    @       0x335c89ce00 (unknown)
    @       0x335c89cf6b (unknown)
    @     0x7ffa1abd6b8b caffe::db::LMDBCursor::value()
    @     0x7ffa1aaac8dc caffe::DataReader::Body::read_one()
    @     0x7ffa1aaacce1 caffe::DataReader::Body::InternalThreadEntry()
    @     0x7ffa1aabbac6 caffe::InternalThread::entry()
    @     0x7ffa13c16190 thread_proxy
    @       0x3351c07851 (unknown)
    @       0x33514e890d (unknown)
Bus error

This is reproducible and happens about after 400 train iterations it bails out when the Resident memory usage reaches 6.0G. 
When caffe train is initially started the process uses 1.0G of resident  but with each test batch it seems to increase slightly until it finally reaches the 6.0G limit and the SIGBUS error happens.

I am running Caffe with CUDA-7.5 on a GTX1080. (No CuDNN) 

But it happens when using CPU instead of GPU for training as well.
