### ISSUE TITLE
make all fatal error: google/protobuf/arena.h

### ISSUE THREAD

**Issue by Meltemisi** [BVLC/caffe#4988]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary
ake: brew: Command not found
PROTOC src/caffe/proto/caffe.proto
CXX .build_release/src/caffe/proto/caffe.pb.cc
In file included from .build_release/src/caffe/proto/caffe.pb.cc:5:0:
.build_release/src/caffe/proto/caffe.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
.build_release/src/caffe/proto/caffe.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^
.build_release/src/caffe/proto/caffe.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^
.build_release/src/caffe/proto/caffe.pb.h:22:35: fatal error: google/protobuf/arena.h: No such file or directory
compilation terminated.
Makefile:591: recipe for target '.build_release/src/caffe/proto/caffe.pb.o' failed
make: *** [.build_release/src/caffe/proto/caffe.pb.o] Error 1

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system: Ubuntu 16:04
Compiler:gcc 5
CUDA version (if applicable):8
CUDNN version (if applicable): 5.1
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively): 2.7 no Matlab

My system works well with other DL packages but for caffe, I am getting this error, which seems like an old error, but there is no solution applicable for ubuntu 16.04... should I downgrade to 14.04

**Comment by KentShikama** [comment]
I had the same issue. It seems like apt's libprotobuf-dev is outdated. Compiling protobuf from the [source](https://github.com/google/protobuf/) fixed the issue.

**Comment by Meltemisi** [comment]
OK, thank you I am going to compile again and share the results...

**Comment by thelittlekid** [comment]
@KentShikama could you please explain a little bit more on what to do with protobuf? I'm having the same issue and not quite familiar with protobuf. Thanks.

**Comment by KentShikama** [comment]
@thelittlekid So usually you can just download packages with something like `apt install libprotobuf-dev` (or using some other package manager if you're not on Ubuntu). However, at least as of my earlier post, the package manager's libprotobuf-dev was outdated. Thus you need to compile protobuf from the source. This means downloading the source code for protobuf (checking out 3.0.x) and doing `./configure`, `make`, etc. The full instructions are at https://github.com/google/protobuf/blob/master/src/README.md

**Comment by shelhamer** [comment]
From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by AemikaChow** [comment]
@Meltemisi I got the same problem when I run faster rcnn. Could you fix it now?

Issue summary

CXX .build_release/src/caffe/proto/caffe.pb.cc
In file included from .build_release/src/caffe/proto/caffe.pb.cc:5:0:
.build_release/src/caffe/proto/caffe.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
.build_release/src/caffe/proto/caffe.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^
.build_release/src/caffe/proto/caffe.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^
In file included from .build_release/src/caffe/proto/caffe.pb.cc:5:0:
.build_release/src/caffe/proto/caffe.pb.h:23:35: fatal error: google/protobuf/arena.h: No such file or directory
compilation terminated.
Makefile:570: recipe for target '.build_release/src/caffe/proto/caffe.pb.o' failed
make: *** [.build_release/src/caffe/proto/caffe.pb.o] Error 1

Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.
Your system configuration

Operating system: Ubuntu 16:04
Compiler:gcc 5
CUDA version (if applicable):8
CUDNN version (if applicable): 5.1
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively): 2.7 no Matlab

When I make caffe, everything is right. But, when I follow the faster rcnn instructions, I got this problem when I run "make".

**Comment by MaeThird** [comment]
@AemikaChow compile protobuf from source with version code 3.3 solved my issue same as yours.

**Comment by OLGKAD** [comment]
Hey guys, 

I am experiencing a similar issue here. However, the only error I'm getting is: 
_
> CXX .build_release/src/caffe/proto/caffe.pb.cc
> In file included from .build_release/src/caffe/proto/caffe.pb.cc:5:0:
> .build_release/src/caffe/proto/caffe.pb.h:23:35: fatal error: **google/protobuf/arena.h: No such file or directory**
> compilation terminated.
_
I'm using protobuf 3.4.0. Anyone knows what could be causing the problem here?

**Comment by heronimus** [comment]
@OLGKAD  I got similar issue with protobuf 3.4.0 from conda. Manually compile protobuf 3.3.0 fix that.

**Comment by ymcasky** [comment]
@heronimus   Can you tell me how to manually compile protobuf 3.3.0 on conda? Thx a lot!

**Comment by heronimus** [comment]
@ymcasky it's not compile protobuf on conda, but compile protobuf from source (follow instruction on : github.com/google/protobuf). Make sure to remove protobuf package from conda, then compile 3.3.0 version from source. Sometime using already compiled package from conda or other package manager may cause incompatibility.

**Comment by ymcasky** [comment]
@heronimus I already install 3.3 as following link:
https://github.com/google/protobuf/blob/master/src/README.md and
The result is:
https://ppt.cc/f5LVDx
But I still get error as 
https://ppt.cc/fQaQyx
Do you have the same issue or do you you install guide for me? 
Thanks.

**Comment by newwhitecheng** [comment]
If you like me work on both tensorflow, anaconda and a lot of different platforms. It's very likely protoc conflict with your anaconda. Create new user account specifically for caffe and it solved!

**Comment by natasasdj** [comment]
I solved it (on Ubuntu 16.04) by: 
sudo apt-get remove libprotobuf-dev protobuf-compiler
sudo apt-get install libprotobuf-dev protobuf-compiler

**Comment by Ethannical** [comment]
CXX .build_release/src/caffe/proto/caffe.pb.cc
In file included from .build_release/src/caffe/proto/caffe.pb.cc:4:
.build_release/src/caffe/proto/caffe.pb.h:10:10: fatal error: 'google/protobuf/port_def.inc' file not found
#include <google/protobuf/port_def.inc>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [.build_release/src/caffe/proto/caffe.pb.o] Error 1

why this!help me

**Comment by mekong0404** [comment]
CXX .build_release/src/caffe/proto/caffe.pb.cc
In file included from .build_release/src/caffe/proto/caffe.pb.cc:4:
.build_release/src/caffe/proto/caffe.pb.h:10:10: fatal error: 'google/protobuf/port_def.inc' file not found
#include <google/protobuf/port_def.inc>
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [.build_release/src/caffe/proto/caffe.pb.o] Error 1

why this!help me

in mac .I have this problem in install caffe


same problem for Mac please help

**Comment by nashihu** [comment]
any update?

**Comment by gd1925** [comment]
Hi everyone, 

On my system, I don't have sudo rights. I am facing the same issue, but since I dont have admin rights, can I compile it by source without using sudo rights? Thanks.
