### ISSUE TITLE
What should I do if I want to use a pretrained model?

### ISSUE THREAD

**Issue by sxl2016** [BVLC/caffe#5016]
I want to use a pretrained model. But the number of classes is not suit my data. What should I do?

**Comment by williford** [comment]
@sxl2016 Please ask your question on the [Caffe user mailing list](https://groups.google.com/forum/#!forum/caffe-users) or on another website, such as http://stackoverflow.com/ or http://stats.stackexchange.com/. In short, you need to modify the model definition for the number of classes that you will use. It is easiest if you rename the layers that have a different number of parameters (e.g. weights and biases) due to the change in channel sizes. You can then load the pretrained weights with your new model definition.

To all: I think there should be an example of this in the tutorial, but the closest example doesn't seem to require a change of the number of classes (or doesn't explicitly mention this, I just skimmed through):
http://caffe.berkeleyvision.org/gathered/examples/finetune_flickr_style.html

I'm leaving this issue open to serve as a request for such an example.

**Comment by williford** [comment]
Also see: #186

**Comment by shelhamer** [comment]
Closing as the fine-tuning example does change the number of classes from ILSVRC (1000) to a subset of Flickr style (5). The ipython notebook is a better reference.
