### ISSUE TITLE
Feature Request - Making a bunch of layers into a module (prototxt) and reusing them

### ISSUE THREAD

**Issue by IMG-PRCSNG** [BVLC/caffe#5150]
**Feature request**

Since caffe has a prototxt definition similar to DOM models, Can we expect to have (in the near future) ways to define (repeating) modules in a separate prototxt and kind of *include* them into our main prototxt?

*Example*
Say I need to extract VGG features (fc1) inside my main network - Can I do 
```
layer {
    name: VGGLayerFromPrototxt
    proto: "path/to/vgg.prototxt
    bottom: "image"
    bottom: "label"
    vggtop: "fc1"
    top: "vggfeat"
}
```
This will make it easier to maintain repeatable modules as well - Like inception, resnet with batch norm etc. Since most of the development in the field are happening with repeating modules, I kinda felt this made sense.

**Comment by williford** [comment]
You will not be able to do this at the level of prototxt, but you can add modularity in code that creates the prototxt definitions, with either:
* Python code that generates the prototxt definitions (common)
* Template code that generates the prototxt definitions (only I do this, with Jinja2)

I'm giving some details on how I use Jinja2 templates below, although creating the prototxts with Python is probably a better way to go.

For a Jinja2 template, I define the following Jinja2 "macro" for creating a convolution layer followed by a ReLU. I've simplified it some from my original definition (which can create the prototxts for different versions of Caffe), to make it easier to understand.
```
{%- import '../../templates/common.j2' as c %}
{% macro fwd_layer(i, ii, num_output, input=none, opts={} ) %}
  # conv{{i}}_{{ii}}
  layer {  bottom: '
{%- if input is none -%}
  conv{{i}}_{{ii-1}}
{%- else -%}
  {{input}}
{%- endif -%}
  '  top: 'conv{{i}}_{{ii}}'  name: 'conv{{i}}_{{ii}}'  type: "Convolution"
    {{ c.lr(opts) }}
    convolution_param {    num_output: {{ num_output }}    pad: 1    kernel_size: 3  }}
    layer {  bottom: 'conv{{i}}_{{ii}}'  top: 'conv{{i}}_{{ii}}'  name: 'relu{{i}}_{{ii}}'  type: "ReLU" }
{%- endmacro %}
```

I think it is safe to close this issue, since modularity can currently be supported with the above techniques and I don't think the BVLC team would want to pursue allowing modularity at the level of the prototxt.

**Comment by IMG-PRCSNG** [comment]
Agreed. 
Forgive my ignorance. I wasn't thinking about doing it within code. Thanks!
