### ISSUE TITLE
Is it possible build caffe static when just build a caffe-based predict single image program?

### ISSUE THREAD

**Issue by jinfagang** [BVLC/caffe#5258]
**issue 1** Can build caffe as static library ? If positive, how to do it, and also how to set it in test single image program using c++ and cmake?

**issue 2** If I just build a program to predicting a image using c++, should it must build GPU version caffe?
Have anyone try above explorings, wish receive some help :)

**Comment by flx42** [comment]
There is a basic C++ example [here](https://github.com/BVLC/caffe/tree/master/examples/cpp_classification), it requires some understanding of how caffe does image pre-processing.
There is more advanced example [here](https://github.com/NVIDIA/gpu-rest-engine), as an inference server.

Both of these codes can use the GPU, but none of them use caffe as a static library.
However, using Docker like in my second link could be used instead of trying to use a static version of caffe.

**Comment by jinfagang** [comment]
Thanks for your advise! I think maybe I should try build caffe on Android or iOS.
