### ISSUE TITLE
Error classification_demo

### ISSUE THREAD

**Issue by Tariq-Abuhashim** [BVLC/caffe#5268]
### Issue summary

I receive the following linking error when running the MATLAB demo.

>> im = imread('../../examples/images/cat.jpg');
>> scores = classification_demo(im, 1);

Invalid MEX-file
'/home/tariq/Documents/caffe/matlab/+caffe/private/caffe_.mexa64':
libcaffe.so.1.0.0-rc4: cannot open shared object file:
No such file or directory.

Error in caffe.set_mode_gpu (line 5)
caffe_('set_mode_gpu');

Error in classification_demo (line 66)
  caffe.set_mode_gpu();

### Steps to reproduce

Caffe was compiled successfully, and tested in the terminal.
Mex function caffe_.mexa64 was compiled.
Matlab directories were found when compiled and generated using CMake.

### Your system configuration
Operating system: Ubuntu 16.04
Compiler: gcc
CUDA version (if applicable): 8 , but I set ONLY_CPU=ON
CUDNN version (if applicable): DISABLED
BLAS: Standard BLAS
Python or MATLAB version (for pycaffe and matcaffe respectively): MATLAB R2016b

**Comment by shelhamer** [comment]
Sorry, this is most likely due to a  linking issue in rc4 or to matcaffe installation. Try rc5 and ask installation questions on the mailing list.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

**Comment by DanChen001** [comment]
Hi, @Tariq-Abuhashim   ,  I meet the same problem, have you solved it ?  Thanks.

**Comment by Tariq-Abuhashim** [comment]
No I didn't. I used a different library.
