### ISSUE TITLE
how can i import caffe in my server apache

### ISSUE THREAD

**Issue by kbibi99** [BVLC/caffe#5303]
hello ,
i have tried to install caffe in my local pc and i succeed  import caffe module from my python interpreter but when i try to use it with my apache server it return 
Traceback (most recent call last):
  File "hello.py", line 5, in <module>
    import caffe
ImportError: No module named caffe

i'm using apache with xamp
how can i solve this problem ?

**Comment by shelhamer** [comment]
You need to configure the python path of your server so that it can locate the `caffe` python module. This is a Python/Apache usage question and not a Caffe issue.

From https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md:

> _Please do not post usage, installation, or modeling questions, or other requests for help to Issues._
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.
