### ISSUE TITLE
Testing on multiple models - Out of memory

### ISSUE THREAD

**Issue by mkyaqub** [BVLC/caffe#5313]
Hi,

I am using the C++ classification code in Caffe (compiled on the Windows branch) to test some images I have. I already trained a sequence of models and the idea is to test an image on the main classifier and then depending on its predicted class the image is tested on another classifier. I have one main classifier and 7 other sub-classifiers all between 100 - 140 MB and another large classifier (about 800MB). I load all the Caffe models to the main memory then sequentially test each image.   

On my Titax X Pascal GPU with 12GB  everything is fine but I have been trying to run it on a laptop which has a gtx 960M with 2GB GPU and I keep getting an out of memory message after a few iterations. When I run the system it works fine on the first few images but then crashes with an out of memory message. I monitored the used GPU memory and it keeps increasing. So I assume that that the GPU does not clear its memory on every image. Right?

I used Cuda 7.5 with cuDNN 4 as this is the only configuration I was able to compile on the laptop.

The forward pass is what makes the used GPU memory increase but it does not decrease after this line or even after leaving the function. 
``
net_->Forward();
``
How can I make Caffe code force the GPU to clear its memory after classifying each image?

Thanks in advance,

**Comment by shelhamer** [comment]
Increasing memory usage for repeated inference with the same input sizes is not normal in Caffe master. Is this a Windows issue? @willyd

**Comment by mkyaqub** [comment]
Yes, I am running Caffe in Windows. The system I have starts with a classifier which decides the type of the image and  then accordingly sends the image to a specific FCN to segment the object of interest. 
BTW, a while ago, I have tried this solution but Caffe did not compile.
https://github.com/BVLC/caffe/pull/2016/commits/839b0502648a5dcf056c3f4a6ace1d0198e6b03e#diff-4162d0c329c27ea34582833e1b57250fR173

Any suggestion?
Regards,

**Comment by willyd** [comment]
> Increasing memory usage for repeated inference with the same input sizes is not normal in Caffe master. Is this a Windows issue? @willyd

Not that I am aware of. 

Is it possible that this could be due to the fact that GPU memory is only allocated when a `Blob::gpu_data()` call is made? And if I am correct this won't happen unless `Net::forward()` is called. @shelhamer can you confirm this. 

If I am right, one way to find out if this is an actual memory leak or if the behavior is normal would be to load all the `Net`s and call `forward` on each and every one of them to make sure that all GPU memory is allocated. If it does not fail after than there probably is a memory leak. 

@mkyaqub If you can setup a simple example that can reproduce the behavior I will have a look.

As a side note, I am aware that @ajtulloch has some code that reuses activation memory buffers and can significantly lower the memory usage for inference. See:

https://github.com/ajtulloch/fb-caffe-exts

**Comment by shelhamer** [comment]
> The system I have starts with a classifier which decides the type of the image and then accordingly sends the image to a specific FCN to segment the object of interest.

This explains it. Caffe lazily allocates memory, so @mkyaqub is running out of memory only once all or enough of the FCNs are executed as dispatched by the classifier. @willyd is exactly right about the behavior with `Net::forward()`.

Caffe has a pretty all-or-nothing approach to memory. The only way to clear memory in a net is to delete the net itself. Fixing this reasonably might be rather involved. A memory pool like CUB could help https://github.com/BVLC/caffe/pull/4175

As a workaround you can delete and re-instantiate the `Net`s, but that will be slow given the need to re-init and re-alloc. Sorry there's not a better way in current master. You could try the fb-caffe-exts too.
