### ISSUE TITLE
 System entropy source not available, using fallback algorithm to generate seed instead.

### ISSUE THREAD

**Issue by wrzto** [BVLC/caffe#5560]

**Comment by PENGUINLIONG** [comment]
It's not actually an error, caffe still can do what it should do normally. It doesn't matter anyway.

In Linux we have entropy source which allow us to get random numbers more effectively. It can be accessed to by path `/dev/random`. We don't have such facility, however, on Windows. Alternatively, we use fallback algorithm to get random numbers.

P.S. You should post such question on mailing list. Github issue page is ready for bug report, functionality improvement, and development discussion rather than general questions.

**Comment by vasoyajignesh7** [comment]
I am also getting the same message.
But challenged for me here is that caffe.exe stops without any error message. Refer below snap.
![image](https://user-images.githubusercontent.com/20473126/87139093-0d8a5b00-c2bd-11ea-8e2c-0a85b8c1195a.png)



Great if some one could provide solution.

I am using caffe in windows platform.
