### ISSUE TITLE
Can't validate while training

### ISSUE THREAD

**Issue by hh2712** [BVLC/caffe#5578]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary
Dear all,
I am new to caffe and currently using the latest Titan X GPU to fine tune the FCN32s network, however, I found that it can't implement validation at all and gives the error "Check failed: error == cudaSuccess (2 vs. 0)  out of memory", which means it ran out of GPU memory and it indeed is the case. I found the test iteration in the original solver.prototxt was 736. In the paper "fully convolutional network for semantic segmentation", a single K40c GPU was used. Surely, the latest Titan X GPU should outperform the former one, according to the specification. 

I wonder why this is happening? Can anyone please kindly provide me with any insight?  

Best,
Hanyi Hu
### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system:Ubuntu 16.04
Compiler:
CUDA version (if applicable): 8.0
CUDNN version (if applicable): v5
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively): python 2.7.12

**Comment by Noiredd** [comment]
Use `nvidia-smi` tool to see what's happening on your GPU and which processes allocate how much memory.

Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
