### ISSUE TITLE
Example "Fine-tuning for style recognition" is broken due to missing links to flickr images

### ISSUE THREAD

**Issue by joelthchao** [BVLC/caffe#5593]
### Issue summary
Example **Fine-tuning CaffeNet for Style Recognition on “Flickr Style” Data**  is broken.
Can't download any images by the scripts (`examples/finetune_flickr_style/assemble_data.py`)
Root cause should be missing link of images.

### Steps to reproduce

```
python examples/finetune_flickr_style/assemble_data.py
```
```
Downloading 80000 images with 3 workers...
Writing train/val for 0 successfully downloaded images.
```
Links to images are broken (e.g. http://farm3.staticflickr.com/2887/12524447173)

### Your system configuration
Operating system: OSX yosemite
Python or MATLAB version (for pycaffe and matcaffe respectively): python 3.5

**Comment by joelthchao** [comment]
If anyone needs to find substitution download links, please refer to my [code](https://github.com/joelthchao/tensorflow-finetune-flickr-style/blob/master/assemble_data.py).

**Comment by Hosseinka** [comment]
@joelthchao I encountered to the same issue, then refered to your solution but there are some mismatches, because of using 2.7 python version ( like print and so on) ,,,after modifying them, there is an error like `File "examples/finetune_flickr_style/assemble_data.py", line 47, in main
    images_per_style = int(sys.argv[4])
ValueError: invalid literal for int() with base 10: '--label=5'` , 
I guess that it does not contain integer value to convert to string . Do you have any opinion to sort out this error

**Comment by joelthchao** [comment]
The purpose and entry of `assembly_data.py` are different between my script and the caffe's. You may use my code to download the images. ([instruction](https://github.com/joelthchao/tensorflow-finetune-flickr-style#download-flickr-style-dataset)) Then use these image to continue your work.
