### ISSUE TITLE
pycaffe works strange to draw network

### ISSUE THREAD

**Issue by monkeyhen** [BVLC/caffe#5616]
### Issue summary
 I installed caffe and it works fine. After pycaffe is compiled, I tried to use it to draw network structure.  However the generated png file looks strange, the text inside the box is replaced with small rectangles.
![image](https://cloud.githubusercontent.com/assets/6859595/25998620/7666c49e-3754-11e7-9a36-18f396420d0c.png)

Did anyone come across a problem like this?

### Your system configuration
Operating system: Red Hat 4.4.6
Compiler: gcc - 4.4.6
CUDA version : 6.5
CUDNN version (if applicable): no 
BLAS: openblas
Python or MATLAB version (for pycaffe and matcaffe respectively): anaconda2

**Comment by Noiredd** [comment]
Does the output look like this for the example networks, or just your own net? Could this be due to some issue with encoding of your network prototxt? Seems like an usage issue so I will close this for now, but I encourage you to post on the [caffe-users list][1] with more details (especially the prototext - please attach it).

 [1]: https://groups.google.com/forum/#!forum/caffe-users
