### ISSUE TITLE
What the connection between pool 1 and conv2 in caffe implementation

### ISSUE THREAD

**Issue by yyxiongzju** [BVLC/caffe#5677]
Hi,

I tried to do the inference by the trained model using my own network 
and I used the same structure as Lenet.
But when I use the same input and the same Lenet caffemodel, the difference comes at the conv2.
I used all the input in pool 1, so I was wondering if the connection between pool 1 and
 conv 2 is specified in caffe implementation?
If it is specified, then where can I get the parameter to specify the partial connection 
between pool 1 and conv 2?
I looked the caffe.proto and I did not find it.

In tinydnn, the connection table is specified. I am not sure the connection table is set by default in caffe.
Can someone help me out?

**Comment by MansourTrabelsi** [comment]
hello, i execute this command    " /home/caffe-master/scripts/download_model_binary.py /home/caffe-master/models/VGG16" but it return a error 
ERROR: '---' is not in list
usage: download_model_binary.py [-h] dirname
download_model_binary.py: error: argument dirname: Must be valid Caffe model directory with a correct readme.md

can you help me please

**Comment by Noiredd** [comment]
You're talking about some specific network, LeNet. Do not confuse caffe.proto, which defines the properties of the framework itself, with a network model that operates *within* that framework. Networks are commonly defined using prototxt files - those describe the connections between layers. See for example the [LeNet's prototxt](https://github.com/BVLC/caffe/blob/master/examples/mnist/lenet_train_test.prototxt).

Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
