### ISSUE TITLE
Problem in training process

### ISSUE THREAD

**Issue by ljm52519** [BVLC/caffe#5680]
After hundreds iterations,it crashed.And the nvidia-smi reveal "The GPU is lost.Reboot the system to recover the GPU",and this situation just happened when I use the hdf5 data to train model.

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

When describing your issue, please give us more information to work with. Are you using the newest release of Caffe (or if not - which version is it), what's your software/hardware configuration, what network are you running, what exact error message are you getting etc.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
