### ISSUE TITLE
batching can't speed up

### ISSUE THREAD

**Issue by mxmxlwlw** [BVLC/caffe#5722]
Hi,
      Batching can't speed up using GPU... Why is that?

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

There can be many reasons. If your GPU is fully utilized (check with `nvidia-smi`) at batch size 1 then inreasing the batch size isn't likely to help. This depends heavily on the hardware you use and the network you run. Please post those details on the users list if you want to discuss this further.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
