### ISSUE TITLE
In which caffe function or file weight updates..

### ISSUE THREAD

**Issue by sainisanjay** [BVLC/caffe#5725]
After computing the gradients in back-propagation we usually updates the parameters(weights and learning rate...). I want to know in caffe code where we are updating weight parameters.

Thanks

**Comment by Noiredd** [comment]
`Solver`'s method `ApplyUpdate` computes the update values and then [calls](https://github.com/BVLC/caffe/blob/c23b3563f0fa2999578c1a8b3f32dc9cdec5a037/src/caffe/solvers/sgd_solver.cpp#L122) `Net::Update`, which in turn iterates over the network's learnable parameters, [calling](https://github.com/BVLC/caffe/blob/accd188d3241c27a6d24b95cd95a4dca4f4078bc/src/caffe/net.cpp#L909) `Blob::Update` on each of them. This [method](https://github.com/BVLC/caffe/blob/3ba20549b7f49a76cd023d19f781a6891b2c2122/src/caffe/blob.cpp#L174) performs the actual change to each weight.

Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
