### ISSUE TITLE
cudnn.hpp have errors when i compile caffe

### ISSUE THREAD

**Issue by 994088895** [BVLC/caffe#5731]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary

when I compile the caffe, it had some errors. That seems like the version of cudnn dosn't match the caffe.So I want to know your version of cudnn. Thanks
like this 
```
In file included from ./include/caffe/util/device_alternate.hpp:40:0,
                 from ./include/caffe/common.hpp:19,
                 from ./include/caffe/blob.hpp:8,
                 from ./include/caffe/data_transformer.hpp:6,
                 from src/caffe/layers/image_data_layer.cpp:10:
./include/caffe/util/cudnn.hpp: In function ‘void caffe::cudnn::createPoolingDesc(cudnnPoolingStruct**, caffe::PoolingParameter_PoolMethod, cudnnPoolingMode_t*, int, int, int, int, int, int)’:
./include/caffe/util/cudnn.hpp:127:41: error: too few arguments to function ‘cudnnStatus_t cudnnSetPooling2dDescriptor(cudnnPoolingDescriptor_t, cudnnPoolingMode_t, cudnnNanPropagation_t, int, int, int, int, int, int)’
         pad_h, pad_w, stride_h, stride_w));
                                         ^
./include/caffe/util/cudnn.hpp:15:28: note: in definition of macro ‘CUDNN_CHECK’
     cudnnStatus_t status = condition; \
                            ^
In
Makefile:572: recipe for target '.build_release/src/caffe/layers/image_data_layer.o' failed
make: *** [.build_release/src/caffe/layers/image_data_layer.o] Error 1
```
### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system:Ubuntu16.04
Compiler:g++
CUDA version (if applicable):8.0
CUDNN version (if applicable):5.1
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):2.7

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

This looks almost certainly like a CUDA/cuDNN version mismatch. Different releases of the CUDA toolkit are compatible with different versions of cuDNN - you should check that. Consult the cuDNN download page for details and make sure you download and install the right version. Please post on the users list in case of further issues.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
