### ISSUE TITLE
How to create hdf5 files for Training and labeled images for caffe training?

### ISSUE THREAD

**Issue by ChidanandKumarKS** [BVLC/caffe#5737]
I had file named *.txt which has training and annotation images in the appropriate path namely

/home/Vin/Train_1.jpg /home/Vin/Annot_1.jpg
.....
.....

How to create hdf5 files for this txt file which contains paths of Training and labeled images ..

Kindly do the needful

REgards
Kumar

**Comment by Noiredd** [comment]
[See this answer on SO.](https://stackoverflow.com/a/31808324/6919631)

Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
