### ISSUE TITLE
Retraining model VGG_ILSVRC_16_layers.caffemodel throws errors

### ISSUE THREAD

**Issue by MohanaRC** [BVLC/caffe#5738]
I have been trying to retrain the VGG_ILSVRC_16_layers.caffemodel and I keep getting the following error,

I0705 15:55:07.324955 11522 caffe.cpp:155] Finetuning from home/xxx/dense_crowd_counting/VGG_ILSVRC_16_layers.caffemodel
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 140543368136512:
  #000: ../../../src/H5F.c line 439 in H5Fis_hdf5(): unable open file
    major: File accessibilty
    minor: Not an HDF5 file
  #001: ../../../src/H5Fint.c line 554 in H5F_is_hdf5(): unable to open file
    major: Low-level I/O
    minor: Unable to initialize object
  #002: ../../../src/H5FD.c line 993 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: ../../../src/H5FDsec2.c line 339 in H5FD_sec2_open(): unable to open file: name = 'home/xxx/dense_crowd_counting/VGG_ILSVRC_16_layers.caffemodel', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 140543368136512:
  #000: ../../../src/H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: ../../../src/H5Fint.c line 992 in H5F_open(): unable to open file: time = Wed Jul  5 15:55:07 2017
, name = 'home/xxx/dense_crowd_counting/VGG_ILSVRC_16_layers.caffemodel', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file
  #002: ../../../src/H5FD.c line 993 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: ../../../src/H5FDsec2.c line 339 in H5FD_sec2_open(): unable to open file: name = 'home/xxx/dense_crowd_counting/VGG_ILSVRC_16_layers.caffemodel', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
F0705 15:55:07.381656 11522 net.cpp:791] Check failed: file_hid >= 0 (-1 vs. 0) Couldn't open home/xxx/dense_crowd_counting/VGG_ILSVRC_16_layers.caffemodel
*** Check failure stack trace: ***
    @     0x7fd2ccc7195d  google::LogMessage::Fail()
    @     0x7fd2ccc736e0  google::LogMessage::SendToLog()
    @     0x7fd2ccc71543  google::LogMessage::Flush()
    @     0x7fd2ccc740ae  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fd2cd20ee78  caffe::Net<>::CopyTrainedLayersFromHDF5()
    @     0x7fd2cd213154  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x40b124  CopyLayers()
    @           0x40c65a  train()
    @           0x4081e0  main
    @     0x7fd2cc006830  (unknown)
    @           0x408b39  _start
Aborted (core dumped)

I am not sure what is causing the error.

I am using Ubuntu 16.04 and Python 2.7
I ran the following statement for the training process
/home/xxx/caffe/build/tools/caffe train -solver /home/xxx/dense_crowd_counting/models/dcc_crowdnet/solver.prototxt -weights home/xxx/dense_crowd_counting/VGG_ILSVRC_16_layers.caffemodel

**Comment by Noiredd** [comment]
From the look of those error messages, I would guess that either the file doesn't exist, or you don't have access privileges to it, or it is corrupted. Or that your path is malformed:
`/home/xxx/caffe/build/tools/caffe train -solver /home/xxx/dense_crowd_counting/models/dcc_crowdnet/solver.prototxt -weights home/xxx/dense_crowd_counting/VGG_ILSVRC_16_layers.caffemodel`

Looks like you're missing a backslash `/` in the path to your caffemodel.

Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md

**Comment by WZNoone** [comment]
hi,can you share the VGG_ILSVRC_16_layers.caffemodel?
