### ISSUE TITLE
caffe opencv color.cpp

### ISSUE THREAD

**Issue by jiangwqcooler** [BVLC/caffe#5751]
OpenCV Error: Assertion failed ((scn == 3 || scn == 4) && (depth == CV_8U || depth == CV_32F)) in cvtColor, file /home/disk2/sw/opencv-3.1.0/modules/imgproc/src/color.cpp, line 8141
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/disk2/sw/opencv-3.1.0/modules/imgproc/src/color.cpp:8141: error: (-215) (scn == 3 || scn == 4) && (depth == CV_8U || depth == CV_32F) in function cvtColor

*** Aborted at 1499418744 (unix time) try "date -d @1499418744" if you are using GNU date ***
PC: @     0x7f54e81fac37 (unknown)
*** SIGABRT (@0x3f100004471) received by PID 17521 (TID 0x7f54a7fff700) from PID 17521; stack trace: ***
    @     0x7f54e81facb0 (unknown)
    @     0x7f54e81fac37 (unknown)
    @     0x7f54e81fe028 (unknown)
    @     0x7f54e880ebbd (unknown)
    @     0x7f54e880cb96 (unknown)
    @     0x7f54e880cbe1 (unknown)
    @     0x7f54e880cdf8 (unknown)
    @     0x7f54e04ab362 cv::error()
    @     0x7f54e04ab4e0 cv::error()
    @     0x7f54dfb7d348 cv::cvtColor()
    @     0x7f54e9a467c8 caffe::AdjustSaturation()
    @     0x7f54e9a4b69b caffe::RandomSaturation()
    @     0x7f54e9a4bdff caffe::ApplyDistort()
    @     0x7f54e99d45b6 caffe::DataTransformer<>::DistortImage()
    @     0x7f54e98cc156 caffe::AnnotatedDataLayer<>::load_batch()
    @     0x7f54e992431c caffe::BasePrefetchingDataLayer<>::InternalThreadEntry()
    @     0x7f54e9aa1185 caffe::InternalThread::entry()
    @     0x7f54df4ada4a (unknown)

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

When posting to caffe-users, please give us more information about the error. What were you doing, when it occurred, what is your hardware/software specification etc. - for now it looks like a misuse of OpenCV.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
