### ISSUE TITLE
How to batch classify pictures in windows?

### ISSUE THREAD

**Issue by 408550969** [BVLC/caffe#5763]
I am currently doing ocr, I want to split the number of pictures after the classification, but the classification.exe can only sort a picture at a time, how to batch classify pictures in windows?

Operating system:windows7
Compiler:vs2013
CUDA version (if applicable):8.0
CUDNN version (if applicable):5.1
BLAS:default
Python or MATLAB version (for pycaffe and matcaffe respectively):anaconda2

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
