### ISSUE TITLE
convert_imageset LMDB Format (windows)

### ISSUE THREAD

**Issue by apassenger** [BVLC/caffe#5767]
I want to create my own dataset My txt file is here 
[](http://dosya.co/3gaehdxgql5p/train_siniflar_1_5000.txt.html)
And I called convert_imageset like this 
`convert_imageset [256*256] C:\traintxt\train_siniflar_1_5000.txt LMDB`
But I have this error:
E0711 10:50:08.045269 13868 io.cpp:89] Could not open or find file
I am sure that path is true for my images 
Any advice??

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

Try calling `convert_imageset` with no arguments - it should print some help on the syntax.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
