### ISSUE TITLE
When synchronize the data of CPU and GPU?

### ISSUE THREAD

**Issue by GreySky0012** [BVLC/caffe#5799]
In the GPU mode,I haven't found where the cpu functions are called,in other words,I don't know when the data would be synchronized into the cpu,and so do in the CPU mode.
So I want know when does the data be synchronized into another head?Or what's the meaning of the SyncedMemory Class?

**Comment by Noiredd** [comment]
SyncedMemory lets us only copy data between CPU and GPU on-demand. If all memory accesses are made to the GPU (via `gpu_data` etc.), nothing is ever copied back to the CPU to save time. When `cpu_data` is requested, synchronization is performed before returning the pointer - copy is only made when it is needed. SyncedMemory keeps track of where the most recent data is and handles those copy operations. I recommend reading its code ([header](https://github.com/BVLC/caffe/blob/master/include/caffe/syncedmem.hpp), [source](https://github.com/BVLC/caffe/blob/master/src/caffe/syncedmem.cpp)) for good understanding.

Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
