### ISSUE TITLE
How to read the prototxt file in binary way ?

### ISSUE THREAD

**Issue by ligongzheng** [BVLC/caffe#5809]
I found there are two functions for IO which are ReadProtoFromBinaryFIle and ReadProtoFriomTextFie.
It seems like the ReadProtoFromBinaryFile designed for reading caffemodel and ReadProtoFromTextFile designed for reading prototxt. I wonder if we can use ReadProtoFromBinaryFIle for reading prototxt file which was rewrite to binary file? If we can ,How to convert it from prototxt to binary file ?

**Comment by JunoBae** [comment]
2017. 7. 29. 오후 12:36에 "ligongzheng" <notifications@github.com>님이 작성:

**Comment by gloomyfish1998** [comment]
how to read labelmap_ilsvrc_det.prototxt file as json or text format , FileStorage could not recognize this, why????, any suggest/???? thanks in advance!!!!

**Comment by gloomyfish1998** [comment]
in opencv3.3 c++

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
