### ISSUE TITLE
Anaconda Python 3.6 raise undefined symbol error

### ISSUE THREAD

**Issue by MrWanter** [BVLC/caffe#5810]
I'm using `ubuntu 14.04,` `cuda 7.5` and `Anaconda` with `Python 3.6`, I have tried compilation with both `make` and `cmake`, both run successfully with all make command(`make all, make test, make runtest, make pycaffe`), then I add the .`.../caffe/python `path to `PYTHONPATH` in `.bashrc`, but then with `python -c "import caffe"`, both make methods give undefined symbol error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/cc/Downloads/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "/home/cc/Downloads/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: /home/cc/Downloads/caffe/python/caffe/_caffe.so: undefined symbol: _ZN5boost6python6detail11init_moduleER11PyModuleDefPFvvE
cc@cc-Lenovo-Rescuer-14ISK:~$ 
```
someone said that this problem is cased by Anaconda [#5090](https://github.com/BVLC/caffe/issues/5090) and suggest to make with simple system python, but since the `makefile.config` included Anaconda options, I believe it's possible to run with Anaconda, so can anyone who have successfully used caffe with Anaconda suggest me a solution? Thanks very much!

**Comment by yxchng** [comment]
I solve the problem by relinking libboost_python.so to libboost_python-py35.so. 
```
cd /usr/lib/x86_64-linux-gnu
sudo rm -rf libboost_python.so
sudo ln -s libboost_python-py35.so libboost_python.so
sudo ldconfig
```

**Comment by DoctorKey** [comment]
I have the same error

**Comment by auroua** [comment]
I encounter the same error, and @yxchng' solution indeed work. Thanks.

**Comment by derkbreeze** [comment]
I encounter the same error, and thanks to @yxchng , it helped me a lot

**Comment by WayneZww** [comment]
However, I do not know why, I did the same thing as you do @yxchng , but then I can not compile the caffe successfully, do anyone have some idea?

**Comment by derkbreeze** [comment]
@WayneZww  Hi wayne, I successfully compiled caffe and pycaffe using miniconda3.0 CUDA8.0 and Ubuntu16.04, the reason I previously can't compile caffe is that I uncommented the WITH_PYTHON_LAYER=1, so I encounter the libboost related error.
I suggest you comment the WITH_PYTHON_LAYER=1, and check your anaconda path, then you may compile caffe successfully and then pycaffe.

**Comment by WayneZww** [comment]
@derkbreeze Thanks a lot for you advice. I finished this problem last night. It seems that I forget to uncomment the  line 78 in the Makefile.config
`# Uncomment to use Python 3 (default is Python 2)`
`# PYTHON_LIBRARIES := boost_python3 python3.5m`
It is important because is this is not uncommented, it will automatically linked to python2 version libboost in Makefile due to line 202
`PYTHON_LIBRARIES ?= boost_python python2.7`
This is my perspective. I realize the problem in the Makefile firstly, so I just change it as 
`# PYTHON_LIBRARIES := boost_python3 python3.5m`
as what Makefile.config do which I realized it after fix this problem.
Before this change, I did the commands as what @yxchng did, And then I meet the problem that my libboost_python is not compiled with -fPIC, so I download a one compiled with -fPIC to replace the original one. Then, I can compile caffe successfully but this pycaffe problem still remains. 
Then after this change, I did the following
`cd /usr/lib/x86_64-linux-gnu/
sudo ln -s libboost_python-py35.so libboost_python3.so
sudo ln -s libpython3.5m.so.1.0 libpython3.5m.so`
And then I fix the problem.

**Comment by Simon32** [comment]
I followed @yxchng 's instruction however when i run the 
`sudo ldconfig`
 it shows 
`/sbin/ldconfig.real: /usr/local/lib/libopencv_imgcodecs.so.3.3 is not a symbolic link` 
can anyone help me?Thank you so much and really appreciate your help

**Comment by Noiredd** [comment]
Basing on reactions to @yxchng's post, I assume the issue is solved. I will close for now, but feel free to reopen in case the problem appears again.

**Comment by pi-Rsq** [comment]
> compiled with -fPIC

Where did you find the -fPIC compiled libboost_python for download?

**Comment by DonghunP** [comment]
What if I use python2??

**Comment by guyii54** [comment]
> I followed @yxchng 's instruction however when i run the
> `sudo ldconfig`
> it shows
> `/sbin/ldconfig.real: /usr/local/lib/libopencv_imgcodecs.so.3.3 is not a symbolic link`
> can anyone help me?Thank you so much and really appreciate your help

have you solved this problem?  It happens on my computer, too

**Comment by g782373711** [comment]
> I solved the problem by relinking libboost_python.so to libboost_python-py35.so and remake caffe.
> 
> ```
> cd /usr/lib/x86_64-linux-gnu
> sudo rm -rf libboost_python.so
> sudo ln -s libboost_python-py35.so libboost_python.so
> sudo ldconfig
> ```
> 
> Note that you may have to change libboost_python-py35.so accordingly, according to the version of Python 3 you have.

sometimes, you need to modify library in Makefile , not in Makefile.config
