### ISSUE TITLE
make runtest error

### ISSUE THREAD

**Issue by srikar8** [BVLC/caffe#5819]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary

InfogainLossLayerTest/2.TestInfogainLoss
F0803 16:42:25.413027 17336 cudnn_softmax_layer.cpp:15] Check failed: status == CUDNN_STATUS_SUCCESS (6 vs. 0)  CUDNN_STATUS_ARCH_MISMATCH
*** Check failure stack trace: ***
    @     0x7fdbea4bd5cd  google::LogMessage::Fail()
    @     0x7fdbea4bf433  google::LogMessage::SendToLog()
    @     0x7fdbea4bd15b  google::LogMessage::Flush()
    @     0x7fdbea4bfe1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fdbe7f4e6b6  caffe::CuDNNSoftmaxLayer<>::LayerSetUp()
    @     0x7fdbe7f037ed  caffe::InfogainLossLayer<>::LayerSetUp()
    @           0x49d687  caffe::InfogainLossLayerTest_TestInfogainLoss_Test<>::TestBody()
    @           0x91ded3  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x9174ea  testing::Test::Run()
    @           0x917638  testing::TestInfo::Run()
    @           0x917715  testing::TestCase::Run()
    @           0x9189ef  testing::internal::UnitTestImpl::RunAllTests()
    @           0x918d13  testing::UnitTest::Run()
    @           0x46d4bd  main
    @     0x7fdbe71b5830  __libc_start_main
    @           0x474fd9  _start
    @              (nil)  (unknown)
Makefile:533: recipe for target 'runtest' failed
make: *** [runtest] Aborted (core dumped)

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system:
Compiler:
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by Noiredd** [comment]
Looks like your GPU does not [support](http://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html#prerequisites) cuDNN. Hard to say though because you did not provide any information about your environment.

Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
