### ISSUE TITLE
Prediction results different from DIGITS

### ISSUE THREAD

**Issue by ibrahim014** [BVLC/caffe#5845]
Hello everyone.
I've trained CNN to classify 7 type of classes. But during tests I noticed that for some images classification results via DIGITS GUI and via python interface are different. Can anyone please help me how can i get exact same results which produce by DIGITS.? Which is the best code to load DIGITS trained model and classify image.

**Comment by Noiredd** [comment]
Most common source of discrepancies between Caffe predictions and those of DIGITS are due to preprocessing. I suggest you read DIGITS [inference code](https://github.com/NVIDIA/DIGITS/blob/master/digits/model/tasks/caffe_train.py#L1255) to see what happens there so you can reproduce its performance.

Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
