### ISSUE TITLE
running demo of Generating Images with Perceptual Similarity Metrics based on Deep Networks gives an error

### ISSUE THREAD

**Issue by NerminSalem** [BVLC/caffe#5846]
when i run the following command python demo.py pool5
i got the following error:
I0815 04:58:16.815672  7354 layer_factory.hpp:77] Creating layer input
I0815 04:58:16.815680  7354 net.cpp:84] Creating Layer input
I0815 04:58:16.815685  7354 net.cpp:380] input -> data
I0815 04:58:16.815704  7354 net.cpp:122] Setting up input
I0815 04:58:16.815711  7354 net.cpp:129] Top shape: 64 3 227 227 (9893568)
I0815 04:58:16.815714  7354 net.cpp:137] Memory required for data: 39574272
I0815 04:58:16.815717  7354 layer_factory.hpp:77] Creating layer conv1
F0815 04:58:16.815723  7354 layer_factory.cpp:69] Layer conv1 has unknown engine.
*** Check failure stack trace: ***
Aborted (core dumped)
can anyone help? thanks

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

Please attach the prototext of your network. It looks like something's wrong with the definition of conv1.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
