### ISSUE TITLE
how to disable prefetch when loading data?

### ISSUE THREAD

**Issue by clavichord93** [BVLC/caffe#5858]
I am doing some forward time test and I want to get rid of the time used by loading data. But I think prefetching make the results unstable. How can I disable prefetching?

**Comment by Noiredd** [comment]
I usually conduct all testing like that from Python: load a network, put some data in, make a first forward-backward pass (to allocate all resources) and then use `time` to measure how long each iteration takes. I suggest either using a deploy configuration (i.e. without a DataLayer but with an Input instead) or doing `Net.forward(start="layer1")` (where "layer1" is the first layer after input) to avoid running the DataLayer forward pass.

Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
