### ISSUE TITLE
getting error while building caffe on windows

### ISSUE THREAD

**Issue by ibrahim014** [BVLC/caffe#5862]
i am getting this error can you tell me how to solve this

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exi
ted with code -1073741515. [C:\Users\Ibrahim Hassan\Desktop\project\caffe\scripts\build\src\caffe\caffeproto.vcxproj]

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

Please attach the full output log - this single line does not contain enough information to help you.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
