### ISSUE TITLE
How to resize a tensor blob similarly with crop_and_resize function in tf ?

### ISSUE THREAD

**Issue by youngwanLEE** [BVLC/caffe#5884]
When I tried to down-sample a featureMap by 2/3 ratio, it is impossible to use convolution and pooling.

How can  I resize a featureMap tensor in caffe ?

**Comment by Noiredd** [comment]
I did something like this in two steps: first upsampling my blob 2x using deconvolution with bilinear weight filler and group param (see [this gist](https://gist.github.com/tnarihi/54744612d35776f53278) for a thorough explanation) and then doing a normal pooling to achieve a 3x dowsampling. Alternatively you could write a Python layer, but that will come at a performance penalty.

Anyway, usage, installation, or modeling questions, or other requests for help should be asked on the [caffe-users list][1] instead of issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
