### ISSUE TITLE
Volumetric convolution in caffe

### ISSUE THREAD

**Issue by chowkamlee81** [BVLC/caffe#5890]
I had a feature map of dim(HWC).
H->Height, W->Width,C->No of channels.

I would like to apply convolution operation on 3-dim feature map to have output like...(hwr2l)
h->height of modified feature map
w->width of modified feature map
r2->no of channels of modified feature map.
l-> no of label map and each label map is of resolution hw*r2.

How to implement this in mxnet?
Kindly provide solution....

**Comment by chowkamlee81** [comment]
I had a feature map of dim(HWC).
H->Height, W->Width,C->No of channels.

I would like to apply convolution operation on 3-dim feature map to have output like...(hwr2l)
h->height of modified feature map
w->width of modified feature map
r2->no of channels of modified feature map.
l-> no of label map and each label map is of resolution hw*r2.

How to implement this in caffe?
Kindly provide solution....

**Comment by Noiredd** [comment]
Look up how to perform an N-D Convolution using Caffe.

Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
