### ISSUE TITLE
ld: framework not found vecLib

### ISSUE THREAD

**Issue by Laknath1996** [BVLC/caffe#5942]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary

I am trying to install Caffe on my Mac, and when I enter the 'make all' command it generates the following error.

LD -o .build_release/lib/libcaffe.so
clang: warning: argument unused during compilation: '-pthread'
ld: framework not found vecLib
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [.build_release/lib/libcaffe.so] Error 1

I tried changing the path of the FindvecLib.cmake file as well. But it didn't work. 
I found out the path to the VecLib header files..
 
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A

But even though I entered this path it still gives the same error. I would be glad if someone could help me out and since I have made amendments to the FindvecLib.cmake now the original content is not there in the file. 

I use http://tutorial.caffe.berkeleyvision.org/installation.html for the installation process and there they have mentioned that the BLAS is incorporated in ATLAS. But apparently it gave an error, so I installed openBLAS instead.

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system: MacOS 10.12
Compiler: (I'm not quite sure, my bad!)
CUDA version (if applicable): 7.5.27
CUDNN version (if applicable): (I'm not quite sure, my bad!)
BLAS: OpenBLAS (I installed it, but guess the macOS should have ATLAS, help me out!)
Python or MATLAB version (for pycaffe and matcaffe respectively):2.7

**Comment by Noiredd** [comment]
> Compiler: (I'm not quite sure, my bad!)

From my quick online search, it seems that this is a crucial piece of information. For example [here](https://github.com/Homebrew/homebrew-science/issues/1016) reinstalling the compiler solved a similar issue.

I'm closing this issue since usage, installation, or modeling questions should be asked on the [caffe-users list][1] instead. If none of the solutions proposed in the link above work for you, please post a follow-up on this issue on the user list.

Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
