### ISSUE TITLE
/usr/bin/ld: can not find -llmb collect2: error: ld returned 1 exit status   Makefile:521

### ISSUE THREAD

**Issue by beautifullife99** [BVLC/caffe#6008]
/usr/bin/ld: can not find  -llmb
collect2: error: ld returned 1 exit status

Makefile:521: recipe for target 'matlab/+caffe/private/caffe_.mexa64' failed
make: *** [matlab/+caffe/private/caffe_.mexa64] Error 255

I had install caffe and matlab2014b,but I have a problem like that, (cpu)ubuntu16+caffe+opencv3+anaconda2.

**Comment by beautifullife99** [comment]
hope someone could give me some help, thanks a lot

**Comment by Noiredd** [comment]
This looks like a typical system configuration-related issue, see this question on [SO](https://stackoverflow.com/questions/16710047/usr-bin-ld-cannot-find-lnameofthelibrary).

Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
