### ISSUE TITLE
too many open files for image data layer

### ISSUE THREAD

**Issue by s0302102** [BVLC/caffe#6060]
Please use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) for usage, installation, or modeling questions, or other requests for help.
_Do not post such requests to Issues._ Doing so interferes with the development of Caffe.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue.

### Issue summary
when using ImageData layer, around 26-27w iterations, (batch size 8, for siamese network, there are two batches)， the program crashed and it promoted "could not open or find file xxx.jpg", Could not create logging file: too many open files. (don't know how to upload image files here)
But actually I checked that xxx.jpg exists and this error will occur every training.

### Steps to reproduce

If you are having difficulty building Caffe or training a model, please ask the caffe-users mailing list. If you are reporting a build error that seems to be due to a bug in Caffe, please attach your build configuration (either Makefile.config or CMakeCache.txt) and the output of the make (or cmake) command.

### Your system configuration
Operating system: Windows
Compiler: vs 2015
CUDA version (if applicable): 8.0
CUDNN version (if applicable):
BLAS: 
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by Noiredd** [comment]
By the look of it, this is an usage problem. Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

When posting to the users list, you can attach your network & solver prototexts as well as a full output log - this will help us help you troubleshoot the issue.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
