### ISSUE TITLE
update the method about SELU and Lecun_normal ?

### ISSUE THREAD

**Issue by liuguiyangnwpu** [BVLC/caffe#6081]
[SNNs-Self-Normalizing-Neural-Networks-Caffe-Reimplementation](https://github.com/HolmesShuan/SNNs-Self-Normalizing-Neural-Networks-Caffe-Reimplementation)

**Comment by Noiredd** [comment]
When reporting a bug, it's most helpful to provide the following information, where applicable:

* What steps reproduce the bug?
* Can you reproduce the bug using the latest [master](https://github.com/BVLC/caffe/tree/master), compiled with the `DEBUG` make option?
* What hardware and operating system/distribution are you running?
* If the bug is a crash, provide the backtrace (usually printed by Caffe; always obtainable with `gdb`).

Try to give your issue a title that is succinct and specific.

Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting an issue or a pull request.
