### ISSUE TITLE
Solvers other than SGD seems not working

### ISSUE THREAD

**Issue by AurusHuang** [BVLC/caffe#6086]
I'm trying different methods for my neural network to see if there's any improvements. I added the following line in my `solver.prototxt`:
`type: "Nesterov"`
However it still calls `sgd_solver.cpp` when training. The same happens for other types, like AdaDelta and AdaGrad. 
I'm using `caffe.exe` directly, and I haven't found any code that restricts `type` to be SGD only. 
Why it doesn't call `nesterov_solver.cpp` when training? 
P.S. Before you say "it should be discussed in Google mailing list", please understand that not all people have access to Google, and posting their issues here is their only choice.

**Comment by Noiredd** [comment]
All of the solvers [inherit](https://github.com/BVLC/caffe/blob/c430690aa5528e94e019971b94de325539984e77/include/caffe/sgd_solvers.hpp#L49) from the basic SGD solver. They usually only override the `ComputeUpdateValue` method, the majority of the work is still done by the [base class methods](https://github.com/BVLC/caffe/blob/master/src/caffe/solvers/sgd_solver.cpp). Since the `Iteration i, lr=...` and other messages come from the base methods (like `ApplyUpdate`), you mostly see that one in the log.
