### ISSUE TITLE
Check failed: mdb_status == 0 (5 vs.  0) Input/output error

### ISSUE THREAD

**Issue by harisudhan312** [BVLC/caffe#6115]
Trying to run caffe using python script for imagenet dataset. When I get the solver file using get_solver(), i get the error. I understand that it happens in my lmdb. But I couldn't find a way to solve it. Here is the error:

I1218 16:49:45.409528 15772 layer_factory.cpp:58] Creating layer data
F1218 16:49:45.409528 15772 db_lmdb.hpp:15] Check failed: mdb_status == 0 (5 vs.
 0) Input/output error
*** Check failure stack trace: ***

**Comment by Noiredd** [comment]
The problem is most likely with your database. When you were making it, did the script complete with no errors? Can the folder be accessed and read from? Post more information on caffe-users.

Please do not post usage, installation, or modeling questions, or other requests for help to Issues. Use the [caffe-users list][1] instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
