### ISSUE TITLE
F1219 22:12:38.255554 31632 gpu_memory.cpp:74] Check failed: initialized_ Create GPUMemory::Scope to initialize Memory Manager *** Check failure stack trace: ***

### ISSUE THREAD

**Issue by gittigxuy** [BVLC/caffe#6119]
I have installed cuda9.0 and cudnn 6.0

I have find several ways but I can not solve the problem.Please help me.

**Comment by Noiredd** [comment]
Please do not post usage, installation, or modeling questions, or other requests for help to Issues. Use the [caffe-users list][1] instead. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

When posting to the users list, please describe which solutions you have already tried, so that we can think of something new.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
