### ISSUE TITLE
Capsule Network in caffe

### ISSUE THREAD

**Issue by deep0learning** [BVLC/caffe#6166]
Hi!! Capsule Network is the new dimension of Deep Learning Community. It would be great if Capsule network is implemented in Caffe. Do you have any plan to work on that ?

**Comment by redhat12345** [comment]
Wow. That would be fine. If Capsule Network is implemented in caffe. When will we get in caffe?

**Comment by redhat12345** [comment]
Any update?

**Comment by Noiredd** [comment]
Caffe is more of a framework rather than a collection of ready solutions: it gives you building blocks to construct these solutions. So it is up to the users to come up with ways to arrange the blocks to create new network architectures. Whether capsules can be made using the layers Caffe has right now - I do not know, I only briefly skimmed the [relevant paper](https://arxiv.org/abs/1710.09829). If changes need to be made to the framework to allow building this type of a net, we will be happy to receive it as a PR. So if this is something you could come up with, I'll be glad to take a look.

I hope this answers your question, so I'll close this issue. Feel free to reopen if you have any more related questions though.
