### ISSUE TITLE
Pycaffe, Anaconda and caffe-cuda

### ISSUE THREAD

**Issue by LupinDefense** [BVLC/caffe#6170]
### Issue summary
apt-get install caffe-cuda 
I want to use anaconda with the module pycaffe, i have installed caffe
with manual of http://caffe.berkeleyvision.org/install_apt.html,
but i want to use the module pycaffe,
i should continue with this manual
https://yangcha.github.io/Caffe-Conda/
is it compatible?
Thanks.

### Steps to reproduce

python -c "import caffe;print caffe.__version__"
version__"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named caffe

### Your system configuration
Operating system: Ubuntu 17.10
Compiler: gcc-5
CUDA version (if applicable):
CUDNN version (if applicable):
BLAS:
Python or MATLAB version (for pycaffe and matcaffe respectively):

**Comment by Noiredd** [comment]
It doesn't look wrong - I suggest to try and if it fails, post to the [caffe-users list][1] about a specific problem.

All usage, installation, or modeling questions, or other requests for help should be posted there instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
