### ISSUE TITLE
Error make all

### ISSUE THREAD

**Issue by NFSPCDD** [BVLC/caffe#6200]
I  ran 
make all -j8
but get this error

LD -o .build_release/lib/libcaffe.so.1.0.0
/usr/bin/ld: /usr/local/lib/libboost_thread.a(thread.o): relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libboost_thread.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:572: recipe for target '.build_release/lib/libcaffe.so.1.0.0' failed
make: *** [.build_release/lib/libcaffe.so.1.0.0] Error 1

I have added -fPIC as follows but it didn‘t work.

**Comment by Noiredd** [comment]
Exact steps were given as an answer to #2171. If these don't work, please post to the [caffe-users list][1] with more details on the problem.

Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md

**Comment by wenzihan** [comment]
Have you solved the problem? I have the same problem. I added "cxxflags + = - FPIC" to the makefile, but it still didn't work
