### ISSUE TITLE
Cross validation

### ISSUE THREAD

**Issue by rmanor** [BVLC/caffe#621]
Is there any way to do cross validation with Caffe?
I usually test my data by randomly generating the training/validation/testing sets for several runs.
It seems that with Caffee I need to generate a new leveldb each time , use train_net, use test_net and repeat.
Thanks.

**Comment by acpn** [comment]
Hi guys,

I'm trying do cross-validation in caffe because I've a small set of images 3K, I'm do it this way:

split my train images in 10 subsets, then I generate the lmdb files, after this I train in subsets 1 to 9 and validation in 10, after this I finetuning this trained network in subsets 2 to 10 an validate in subset 1, and subsequently until pass for all subsets.

The problem is which the network suffers of overfiting because when I do finetuning my subset of validation already exposed to training phase.

So what I'm doing wrong? Is this way which do cross-validation in caffe?

I read about this in some places like github and  in caffe users too, but isn't clear.

If anyone help me I really thanks, I've lost a week on this and the problem persist.

Thanks guys.

**Comment by Codermanok** [comment]
[](https://groups.google.com/forum/#!topic/caffe-users/1UpQdQB5VGE).  there is an answer that may help you.
