### ISSUE TITLE
Caffe - Data Format for Custom data

### ISSUE THREAD

**Issue by chandanv2** [BVLC/caffe#6214]
Digits follows KITTI dataset format. 
To realise a model (caffe) in general all we need is the prototxt file and .caffemodel file which consists of the weights. So when this model is used for inference say on other system, how will this know the standard output label format that has to be given as the output ? Is the format included in the .caffemodel file (I dont think it is!) ?
To say it in other way my question is in which file the output label format for data inference is present? 
(A kitti trained set will give out inference in kitti data label format, whereas a COCO trained set will give out inference in COCO label format. Through which script or code this format is conveyed to the Framework or the system?)

**Comment by Noiredd** [comment]
Caffe does not output labels by itself. Usually the output is a vector of probabilities of each label (for classification tasks), its dimensions in this case are `batch_size`x`number_of_classes`, or a map of probabilities (for segmentation tasks), dimensions `batch_size`x`height`x`width`x`number_of_classes`, etc.  
It is the user's job to convert this to labels.

If you have further questions, please post to the [caffe-users list][1]. All usage, installation, or modeling questions, or other requests for help should be posted there instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
