### ISSUE TITLE
Cannot find extra_component library

### ISSUE THREAD

**Issue by ValoisKhanh** [BVLC/caffe#6216]
I am new to Caffe. When I ran "make all", I encountered this error:

AR -o .build_release/lib/libcaffe.a
LD -o .build_release/lib/libcaffe.so.1.0.0
/usr/bin/ld: cannot find -lextra_component-NOTFOUND
collect2: error: ld returned 1 exit status
Makefile:572: recipe for target '.build_release/lib/libcaffe.so.1.0.0' failed
make: *** [.build_release/lib/libcaffe.so.1.0.0] Error 1

I cannot find out the "extra_component" library?
I use Ubuntu 16.04, CPU_ONLY and I've installed OpenCV 2.4.13.5
Any help will be appreciated. Thank you.

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

Please attach your Makefile.config to the post as well as entire build output log.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
