### ISSUE TITLE
Make issues with -lnvidia-ml

### ISSUE THREAD

**Issue by 331744738** [BVLC/caffe#6227]
centos7.4
cuda9.1 
make all -j4（An error is as follows）

/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml
/usr/bin/ld: skipping incompatible /usr/lib/libnvidia-ml.so when searching for -lnvidia-ml

#####In many editions of the driver, still suggest incompatible, solve!#####

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

When posting to the caffe-users list, please attach your Makefile.config as well as a complete output log. You can store it by running `make all -j4 > log.txt`.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
