### ISSUE TITLE
How to see the loss of the layer in python if my loss layer has a stage included such as 'test on test' or 'test on train'?

### ISSUE THREAD

**Issue by ayeshasGithub** [BVLC/caffe#6233]
Hi,

if I have a loss layer like following:
layer {
  name: "loss"
  type: "SigmoidCrossEntropyLoss"
  bottom: "decode1"
  bottom: "flatdata"
  top: "test_cross_entropy_loss"
  include{phase: TEST
            }
  }

Then, I can see the loss of the above layer in python as following-->
test_loss_entropy[it//test_interval] = solver.test_nets[0].blobs['test_cross_entropy_loss'].data

How to see the loss of the layer if my layer has stage included like following?
layer {
  name: "loss"
  type: "SigmoidCrossEntropyLoss"
  bottom: "decode1"
  bottom: "flatdata"
  top: "test_cross_entropy_loss"
  include{phase: TEST
           stage: "test-on-test"
            }
  }

**Comment by Noiredd** [comment]
`solver.test_nets` is a list of nets in testing phase - Caffe instantiates a separate network object for each. You can select which net you want to access (`[0]`, `[1]` etc.). Also see the [lenet](https://github.com/BVLC/caffe/tree/master/examples/mnist#additional-notes-writing-layer-rules) example.

Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
