### ISSUE TITLE
python2.7 examples/web_demo/app.py

### ISSUE THREAD

**Issue by JavierRuano** [BVLC/caffe#6242]
python2.7 examples/web_demo/app.py

using deprecated V1LayerParameter
I0218 14:07:08.014688  8412 net.cpp:744] Ignoring source layer loss
Traceback (most recent call last):
  File "examples/web_demo/app.py", line 227, in <module>
    start_from_terminal(app)
  File "examples/web_demo/app.py", line 214, in start_from_terminal
    app.clf = ImagenetClassifier(**ImagenetClassifier.default_args)
  File "examples/web_demo/app.py", line 140, in __init__
    self.labels = labels_df.sort('synset_id')['name'].values
  File "/home/cantajuegos/anaconda2/lib/python2.7/site-packages/pandas/core/generic.py", line 3614, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'sort'

Regards

**Comment by gorenje** [comment]
I fixed this by changing [sort on this line](https://github.com/BVLC/caffe/blob/1.0/examples/web_demo/app.py#L140) to sort_values. It's probably because the code is expecting a different version of [pandas](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html) (pip installed 0.22.0 because the [requirements](https://github.com/BVLC/caffe/blob/1.0/examples/web_demo/requirements.txt#L5) don't specify a version)
