### ISSUE TITLE
conversion

### ISSUE THREAD

**Issue by xxxyyyzzzz** [BVLC/caffe#6248]
how to convert the output.txt to log file for gnuplot?
any answers..

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
