### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_61'

### ISSUE THREAD

**Issue by Saturday32** [BVLC/caffe#6255]
using cmake to build caffe, CUDA 8, cuDNN V7, 1070 Ti
when i use cmake it shows cuda 7.5 even though i have cuda 8.0 installed

"[  1%] Built target caffeproto
[  2%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_prelu_layer.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_61'
CMake Error at cuda_compile_generated_prelu_layer.cu.o.cmake:207 (message):
  Error generating
  /home/stanley/caffe/build/src/caffe/CMakeFiles/cuda_compile.dir/layers/./cuda_compile_generated_prelu_layer.cu.o

src/caffe/CMakeFiles/caffe.dir/build.make:483: recipe for target 'src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_prelu_layer.cu.o' failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/layers/cuda_compile_generated_prelu_layer.cu.o] Error 1
CMakeFiles/Makefile2:304: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
"

please help

**Comment by Noiredd** [comment]
Make sure your `/usr/local/cuda` symlink points to the right version of the toolkit. Also, I think you need CUDA 9 for compute_61 anyway.

Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
