### ISSUE TITLE
training Googlenet from scratch got low accuracy

### ISSUE THREAD

**Issue by IdealJiaqiZhang** [BVLC/caffe#6256]
Hi,
When I use models/bvlc_googlenet/train_val.prototxt and solver.prototxt to train googlenet from scratch on imagenet, I only got accuracy of 59% at top-1 and 83% at top-5 at max_iteration (10000000) . However, googlenet is claimed to achieve 68.9% and 89.04%. What accuracy did you get? Should I do some modifications to the prototxt files?
Thanks!

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
