### ISSUE TITLE
Add a new class to the Caffemodel

### ISSUE THREAD

**Issue by zpmmehrdad** [BVLC/caffe#6274]
Hi, everybody
I trained a model with 20 classes and I wanna add 5 classes to my old model.
can anyone explain?
Thanks

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

In short, you will need to change the classification layer - i.e. remove the old one and place a new one with 25 classes. This requires that you retrain the classifier on the new dataset (unless you can come up with some clever way to transfer the weights of the old model).

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md

**Comment by JavierRuano** [comment]
Do you need always generate weights together, isn't?
You answer similar to transfer knowledge from a convnet yo previous
knowledge with different weights?

Regards
Javier Ruano
