### ISSUE TITLE
Check failed: error == cudaSuccess (2 vs. 0)  out of memory

### ISSUE THREAD

**Issue by larklili** [BVLC/caffe#6289]
**### Issue summary**
sh Baseline.sh and then display the fllowing error:
# Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
    @     0x7ffa99a40daa  (unknown)
    @     0x7ffa99a40ce4  (unknown)
    @     0x7ffa99a406e6  (unknown)
    @     0x7ffa99a43687  (unknown)
    @     0x7ffa99dfab2b  caffe::SyncedMemory::mutable_gpu_data()
    @     0x7ffa99dab302  caffe::Blob<>::mutable_gpu_data()
    @     0x7ffa99e98430  caffe::BaseConvolutionLayer<>::forward_gpu_gemm()
    @     0x7ffa99f11621  caffe::ConvolutionLayer<>::Forward_gpu()
    @     0x7ffa99e03f49  caffe::Net<>::ForwardFromTo()
    @     0x7ffa99e04377  caffe::Net<>::ForwardPrefilled()
    @     0x7ffa99db9bbe  caffe::Solver<>::Test()
    @     0x7ffa99dba2c6  caffe::Solver<>::TestAll()
    @     0x7ffa99dc6471  caffe::Solver<>::Step()
    @     0x7ffa99dc6e3f  caffe::Solver<>::Solve()
    @           0x407f15  train()
    @           0x406281  main
    @     0x7ffa9879df45  (unknown)
    @           0x40691d  (unknown)
    @              (nil)  (unknown)
Aborted (core dumped)

 When training my model, display memory is insufficient, but my batch size is already 1. How could I solve this problem?Thanks!

### Your system configuration
Operating system:Linux

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

Please provide more information when you post to the users list. What hardware do you have, what network are you using (attach the prototxt), etc.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
