### ISSUE TITLE
Unable to Add Scale Layer Python

### ISSUE THREAD

**Issue by soulslicer** [BVLC/caffe#6298]
### Issue summary

I am not able to recreate the following Scale Layer in Python:

```
 layer {
   name: "s"
   type: "Scale"
   bottom: "o"
   top: "o"
   param {
     lr_mult: 0
     decay_mult: 0
   }
   param {
     lr_mult: 1
     decay_mult: 0
   }
   scale_param {
     filler {
       value: 1    }
     bias_term: true
     bias_filler {
       value: 0
     }
   }
 }
```

```python
caffeNet.tops[gScaleName] = L.Scale(caffeNet.tops[gConvName],
                                        param=[dict(lr_mult=0, decay_mult=0), dict(lr_mult=1, decay_mult=0)],
                                        scale_param=[dict(bias_term=True), dict(bias_filler=dict(value=0)), dict(filler=dict(value=0))]
                                        )
```
I tried this and it gives an error AttributeError: 'ScaleParameter' object has no attribute 'add'

**Comment by Noiredd** [comment]
Since this is an usage issue that you have also asked on Stack Overflow (where it received at least [one answer](https://stackoverflow.com/a/49345180/6919631)), I will close this.

Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
