### ISSUE TITLE
run：./build/tools/compute_image_mean * *，mean.binaryproto is empty

### ISSUE THREAD

**Issue by Jimjipeng** [BVLC/caffe#6300]
run “./build/tools/compute_image_mean /home/znzx/data/VOCdevkit/VOC2007/lmdb/VOC2007_trainval_lmdb/ /home/znzx/Desktop/prodect/ssd-train/compute_image_mean/mean.binaryproto“
result：mean.binaryproto is empty。。。 why？

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

Please add more information. Is the LMDB valid? Can you open it and load images from it?

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
