### ISSUE TITLE
sudo make all -j8    failed   Error

### ISSUE THREAD

**Issue by ZhouTaoshu** [BVLC/caffe#6301]
make: *** [.build_release/examples/cpp_classification/classification.bin] Error 1
.build_release/lib/libcaffe.so：对‘google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)’未定义的引用
.build_release/lib/libcaffe.so：对‘google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)’未定义的引用
.build_release/lib/libcaffe.so：对‘google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)’未定义的引用
collect2: 错误：ld 返回 1
Makefile:631: recipe for target '.build_release/examples/siamese/convert_mnist_siamese_data.bin' failed
make: *** [.build_release/examples/siamese/convert_mnist_siamese_data.bin] Error 1
.build_release/lib/libcaffe.so：对‘google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)’未定义的引用
.build_release/lib/libcaffe.so：对‘google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)’未定义的引用
.build_release/lib/libcaffe.so：对‘google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)’未定义的引用
collect2: 错误：ld 返回 1
Makefile:626: recipe for target '.build_release/tools/upgrade_net_proto_text.bin' failed

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md

**Comment by mleming** [comment]
^ @Noiredd  Question: can there be a policy update by which Caffe users can post these questions to Github? The Caffe users list is harder to search than Github, it usually doesn't show up on Google search results, it's less popular than Github, and mods aren't really responsive on the users list anyway. It's not the most helpful thing to come across this answer in my Google search results every time I have an issue with Caffe.

**Comment by Noiredd** [comment]
@mleming I am not a decisive person when it comes to policy, but in my opinion such a change would only cause confusion and be detrimental to the community and the framework. We try to keep the problems which affect *all users* (problems with the framework itself) separate from the ones that *only some people* have, because solving the former requires greater expertise and some activity (changes to the framework), while the latter are usually simpler to resolve and often have existing solutions. The people who write Caffe code are not necessarily the same people who try to help you on the users list, and we try not to mix their work loads. Issues are meant for the devs to manage their work - a bug submission is definitely interesting for them, but having all requests for help posted there would be counterproductive for the team.

I'm sorry that you keep finding the *"Please post (...) to the caffe-users list"* template reply in your searches. The set of [rules](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md#issues) we have for posting issues is only an attempt to make submissions more helpful. An issue which contains no information about the user's environment and configuration and no steps to help reproduce it isn't helpful for *anybody*: neither for developers, who have no chance to fix it, nor for the users who come across it when encountering a similar problem. We close such issues to keep order in the tracker - however, if you re-submitted a similar issue *with* all the necessary information, it wouldn't be dismissed.

Regarding the users-list, I realize that not all the questions asked there get answers - we really need more knowledgeable people helping others out there. I try to answer as many as I can, but my expertise and (especially) free time both have their limits. If your question has been missed, think of how you could improve on it: maybe the problem hasn't been described with enough detail, maybe the same problem has already been resolved elsewhere? I recommend checking out the topic Caffe on [Stack Overflow](https://stackoverflow.com/questions/tagged/caffe), too.
