### ISSUE TITLE
22845 db_lmdb.hpp:15] Check failed: mdb_status == 0 (2 vs. 0) No such file or directory

### ISSUE THREAD

**Issue by datamonday** [BVLC/caffe#6314]
when I runpython examples/ssd/ssd_pascal.py 
 I got this error,but I can run ssd_pascal_webcam and ssd_pascal_video.py normally. what's wrong,and what should I do?thank you very much!

 I0327 01:57:39.369675 22832 layer_factory.hpp:77]  Creating layer data
I0327 01:57:39.369884 22832 net.cpp:100] Creating Layer data
I0327 01:57:39.369902 22832 net.cpp:408] data -> data
I0327 01:57:39.369937 22832 net.cpp:408] data -> label
F0327 01:57:39.370539 22845 db_lmdb.hpp:15] Check failed: mdb_status == 0 (2 vs. 0) No such file or directory
*** Check failure stack trace: ***
    @     0x7fba838f75cd  google::LogMessage::Fail()
    @     0x7fba838f9433  google::LogMessage::SendToLog()
    @     0x7fba838f715b  google::LogMessage::Flush()
    @     0x7fba838f9e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fba8418fcc2  caffe::db::LMDB::Open()
    @     0x7fba841fc8d6  caffe::DataReader<>::Body::InternalThreadEntry()
    @     0x7fba83fc8725  caffe::InternalThread::entry()
    @     0x7fba77c9c5d5  (unknown)
    @     0x7fba704696ba  start_thread
    @     0x7fba8294e41d  clone
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by datamonday** [comment]
查了很多都说是路径问题，可我发现路径貌似没问题，而且编译完了也么修改，但是我到examples/voc0712下打开lmdb的数据，得到了这样的提示：The link “VOC0712_test_lmdb” is broken. Move it to Trash? This link cannot be used because its target “/home/chopin/data/VOCdevkit/VOC0712/lmdb/VOC0712_test_lmdb” doesn't exist. 并且在运行 ./data/VOC0712/create_data.sh的时候只得到了这样的反馈，不知道是否正常？chopin@Ubuntu16:~/caffe$ ./data/VOC0712/create_data.sh
/home/chopin/caffe/build/tools/convert_annoset --anno_type=detection --label_type=xml --label_map_file=/home/chopin/caffe/data/VOC0712/../../data/VOC0712/labelmap_voc.prototxt --check_label=True --min_dim=0 --max_dim=0 --resize_height=0 --resize_width=0 --backend=lmdb --shuffle=False --check_size=False --encode_type=jpg --encoded=True --gray=False /home/chopin/data/VOCdevkit/ /home/chopin/caffe/data/VOC0712/../../data/VOC0712/test.txt /home/chopin/data/VOCdevkit/VOC0712/lmdb/VOC0712_test_lmdb
/home/chopin/caffe/build/tools/convert_annoset --anno_type=detection --label_type=xml --label_map_file=/home/chopin/caffe/data/VOC0712/../../data/VOC0712/labelmap_voc.prototxt --check_label=True --min_dim=0 --max_dim=0 --resize_height=0 --resize_width=0 --backend=lmdb --shuffle=False --check_size=False --encode_type=jpg --encoded=True --gray=False /home/chopin/data/VOCdevkit/ /home/chopin/caffe/data/VOC0712/../../data/VOC0712/trainval.txt /home/chopin/data/VOCdevkit/VOC0712/lmdb/VOC0712_trainval_lmdb
。可以说一下需要修改那些路径和VOC数据的放置路径以及解决方法吗？非常感谢！

**Comment by Noiredd** [comment]
The error message is pretty clear about what's wrong: `db_lmdb.hpp:15] Check failed: mdb_status == 0 (2 vs. 0) No such file or directory` - meaning, the DataLayer was unable to open the source database. Check your paths, make sure the data is there.  
By the way, you seem to be confusing repositories - master Caffe does not even have anything like `examples/ssd/ssd_pascal.py`. If you are using a specialized fork, make sure to check its repository for help first.  

I will close this issue as usage related. Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md

**Comment by datamonday** [comment]
I install ssd on Ubuntu16.04 and try to train pascal VOC when I run examples/ssd/ssd_pascal.py I got that error.
If the path wrong to result in this error, what path and profile I should to edit? I will be very grateful if you are willing to help me.Thanks again!

**Comment by Noiredd** [comment]
The error is caused in the DataLayer - look into your network prototxt and check the path to input database in your Data Layer.
