### ISSUE TITLE
Possible to train on multiple GPU with Python API

### ISSUE THREAD

**Issue by soulslicer** [BVLC/caffe#6315]
Is it possible to manually train my net via python, with the solver.step() function. Is there a way to allow it to train on multiple GPUs?

Also, I want to know how Caffe transfers the load to multiple GPU? Is it just a matter of increased speedup, by which Batch A,B,C etc. are queued up and then dequed by multiple GPU? Or is it some kind of virtual batch size increase?

**Comment by Noiredd** [comment]
Python interface can only handle a single GPU at a time (`caffe.set_device()`). A way around this is to instantiate multiple processes, each holding an individual device, but this only lets you do model parallelism, not data parallelism.

When training on multiple GPUs (using the command line interface), the speed-up is achieved by processing individual batches on individual GPUs: so instead of a single net with a batch size N, you have, let's say, 4 nets, each processing a different batch of N images. Then the gradients are exchanged between devices. Effectively this is equivalent to increasing a batch size by a factor equal to the number of devices used.

**Comment by soulslicer** [comment]
Thanks, sorry I still have another question based on this.

So if NCCL gives you data parallelism, will it work in my situation? I need to train my net on sequence data. But for it to generalize, i need it to train on multiple sequences at once. The net looks something like this:

https://i.stack.imgur.com/F7fEz.png

My net basically needs to take in a video with frames [I0, I1, I2, I3]. But if i want to train on multiple videos it would become [I0,I0,I0, I1,I1,I1, etc.] and i could slice them accordingly. Is it possible to even multi gpu parallelize such a setup?
