### ISSUE TITLE
caffe runtest fail

### ISSUE THREAD

**Issue by justinner** [BVLC/caffe#6334]
Hello,I make  runtest  failed,following are errors:
    **RUN      ] IntersectionOverUnionLossLayerTest/0.TestTwoTrianglesBackward
F0408 11:19:52.191068 28240 intersection_over_union_loss_layer.cpp:137] Did not find the point meta
*** Check failure stack trace: ***
    @     0x7fbaf4bc05cd  google::LogMessage::Fail()
    @     0x7fbaf4bc2433  google::LogMessage::SendToLog()
    @     0x7fbaf4bc015b  google::LogMessage::Flush()
    @     0x7fbaf4bc2e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fbaedb09d50  caffe::IntersectionOverUnionLossLayer<>::find_point_meta()
    @     0x7fbaedb077f1  caffe::IntersectionOverUnionLossLayer<>::compute_diff()
    @     0x7fbaedb09529  caffe::IntersectionOverUnionLossLayer<>::d_area_d_pred()
    @     0x7fbaedb3587e  caffe::IntersectionOverUnionLossLayer<>::Backward_cpu()
    @           0x467eb8  caffe::GradientChecker<>::CheckGradientSingle()
    @           0x46b3a3  caffe::GradientChecker<>::CheckGradientExhaustive()
    @           0x527c1a  caffe::IntersectionOverUnionLossLayerTest<>::TestTwoTrianglesBackward()
    @           0x80cde3  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x80669a  testing::Test::Run()
    @           0x8067e8  testing::TestInfo::Run()
    @           0x8068c5  testing::TestCase::Run()
    @           0x806b7f  testing::internal::UnitTestImpl::RunAllTests()
    @           0x806eb3  testing::UnitTest::Run()
    @           0x459a29  main
    @     0x7fbaecd8f830  __libc_start_main
    @           0x460199  _start
    @              (nil)  (unknown)
Makefile:469: recipe for target 'runtest' failed
make: *** [runtest] 已放弃 (core dumped)**
If I can get some help,I will be very grateful,Thanks very much.

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

We don't have an IntersectionOverUnionLoss layer in master. If you're using some specialized fork of Caffe, please make it clear in your post or consult the maintainers of your fork.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
