### ISSUE TITLE
Excuse me ,is there any Caffe implementation code of  【Show and Tell: A Neural Image Caption Generator】?

### ISSUE THREAD

**Issue by LongruiDong** [BVLC/caffe#6339]
I am learning a classical image caption model [Show and Tell: A Neural Image Caption Generator](http://arxiv.org/abs/1609.06647)

is there any Caffe implementation code of it?
thanks~

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
