### ISSUE TITLE
Make it trivial to change boost version used

### ISSUE THREAD

**Issue by mackiem** [BVLC/caffe#6344]
### Issue summary
Windows build does not support CUDA 9+, due to incorrect boost version being used (boost 1.61.0). There is no easy way to change this boost version. The 10 gen of NVidia cards do not support CUDA 8.0. This is a blocker from training large models in a short time on a Windows machine.

### Steps to reproduce
Build Windows caffe on a machine with GTX 1060 or better.

### Tried solutions
Changing cmake boost version to 1.65 in dependencies.cmake does not solve the problem. It results in the following error:

CMake Error at C:/Program Files/CMake/share/cmake-3.10/Modules/FindBoost.cmake:1928 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.61.0

  Boost include path:
  C:/Users/blah/.caffe/dependencies/libraries_v140_x64_py27_1.1.0/libraries/include/boost-1_61

  Detected version of Boost is too old.  Requested version was 1.65 (or
  newer).
Call Stack (most recent call first):
  cmake/Dependencies.cmake:8 (find_package)
  CMakeLists.txt:80 (include)

### System configuration

* Operating system: Windows 10
* Compiler: MSVC 2013 64 bit
* CUDA version (if applicable): 9 
* CUDNN version (if applicable): 7.1.2 
* BLAS: 
* Python version (if using pycaffe): no
* MATLAB version (if using matcaffe): no

### Issue checklist

- [x] read the guidelines and removed the first paragraph
- [x] written a short summary and detailed steps to reproduce
- [x] explained how solutions to related problems failed (tick if found none)
- [x] filled system configuration
- [x] attached relevant logs/config files (tick if not applicable)

**Comment by willyd** [comment]
I am about to update the version of boost the windows build uses to 1.66. I hope I can make this happend over the weekend. For a preview check https://github.com/willyd/caffe/tree/windows. Please note that MSVC 2013 support will be dropped, so you will want to update to 2015 or 2017.

**Comment by mackiem** [comment]
I have my main project in VS 2013 (which I plan to integrate caffe into). Can't I just build it from source? I'm just wondering why the whole cmake paradigm is broken here. No offense, just curious.

**Comment by mackiem** [comment]
Ok, I managed to change the boost version by doing this. But, unfortunately the compile error still stands with boost 1.65.0. Let me try 1.66.0 now.

But, here's how to do it:

1. Download boost version you want to some location (let's call this BOOST_PATH)

2. Edit the scripts/build_win.cmd cmake command as follows:
:: Configure using cmake and using the caffe-builder dependencies
:: Add -DCUDNN_ROOT=C:/Projects/caffe/cudnn-8.0-windows10-x64-v5.1/cuda ^
:: below to use cuDNN
cmake -G"!CMAKE_GENERATOR!" ^
      -DBLAS=Open ^
      -DCMAKE_BUILD_TYPE:STRING=%CMAKE_CONFIG% ^
       -DBUILD_SHARED_LIBS:BOOL=%CMAKE_BUILD_SHARED_LIBS% ^
       -DBUILD_python:BOOL=%BUILD_PYTHON% ^
       -DBUILD_python_layer:BOOL=%BUILD_PYTHON_LAYER% ^
       -DBUILD_matlab:BOOL=%BUILD_MATLAB% ^
       -DCPU_ONLY:BOOL=%CPU_ONLY% ^
       -DCOPY_PREREQUISITES:BOOL=1 ^
       -DINSTALL_PREREQUISITES:BOOL=1 ^
       -DUSE_NCCL:BOOL=!USE_NCCL! ^
       -DCUDA_ARCH_NAME:STRING=%CUDA_ARCH_NAME% ^
       -DBOOST_NO_BOOST_CMAKE=TRUE ^
       -DBOOST_ROOT=C:/boost_1_65_0 ^ :: The custom boost path version
       -DBOOST_LIBRARYDIR=C:/boost_1_65_0/lib64-msvc12.0 ^ :: The custom boost path library location
       "%~dp0\.."

Not the the options BOOST_ROOT, BOOST_NO_BOOST_CMAKE, BOOST_LIBRARY_DIR

**Comment by mackiem** [comment]
Closing this issue as there exists a workaround to change boost version. Note that CMAKE does not support boost 1.66.0 (as of now) if you are trying to make that work .

**Comment by gfursin** [comment]
Hi @mackiem,

We also suffered from similar issues when working on performance evaluation of different AI/ML algorithms, since we want to compile Caffe with different compilers, libraries and tools, and it's always a pain ;) ...

This motivated us to create a simple python framework (CK) to install different packages separately (Boost, cuDNN, OpenBLAS, clBLAS, CLBlast, etc) using different compilers (VS2013,VS2017) across different platforms (Linux, Windows, MacOS, Android), and then automatically glue them together to build Caffe.

You can try it youself in just a few steps:

```
$ pip install ck
$ ck pull repo --url=https://github.com/dividiti/ck-caffe

$ ck install package --tags=lib,boost
```

You should normally see the following:
```
More than one package found:

0) lib-boost-1.66.0-min-for-caffe  Version 1.66.0-min-for-caffe  (04254b0e8fd053ef)
1) lib-boost-1.66.0  Version 1.66.0  (0417ba98aa5ca4ad)
2) lib-boost-1.65.1-min-for-caffe  Version 1.65.1-min-for-caffe  (e8e0c4ee4898b84b)
3) lib-boost-1.65.1  Version 1.65.1  (8bb8a5b19b48120c)
4) lib-boost-1.64.0-min-for-caffe  Version 1.64.0-min-for-caffe  (cb7aa7d5bbd74d94)
5) lib-boost-1.64.0  Version 1.64.0  (c6a6991d5c951d20)
6) lib-boost-1.62.0-min  Version 1.62.0  (44094af948731a1c)

Select package number (or Enter to select 0):
```

You can then actually select "lib-boost-1.65.1-min-for-caffe" - we prepared this package to compile minimal number of Boost functions required by Caffe - it speeds up build by 10x on Windows ;) ...

You can then build caffe (CK will detect available Microsoft and CUDA compilers and libraries and will rebuild extra packages):

```
$ ck install package:lib-caffe-bvlc-master-cudnn-universal
```

After installing, you can see registered environment for this Caffe packge:
```
$ ck show env --tags=lib,caffe
```

You can then use it with CK virtual env (similar to Python virtual env, but can also work with binary packages):
```
$ ck virtual env --tags=lib,caffe
```

This allows you to build multiple Caffe flavors in your system hopefully with much less pain...

This approach solved our current problems, so will be happy if it help you too ;) !
You can find more info here: https://github.com/dividiti/ck-caffe/wiki
