### ISSUE TITLE
Multi branches‘ backpropagation in split point (relative to multi-task learning)

### ISSUE THREAD

**Issue by zhonhel** [BVLC/caffe#6351]
I want to use Caffe to do a multi-task learning. So, the backbone network in somewhere splits into two branch, and every branch has a loss layer in the end.

I confused that the different branch's diff doing a what operation in the split point , is it an adding? Where can I find the corresponding code?

Thank you very much~

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
