### ISSUE TITLE
mean.binaryproto problem

### ISSUE THREAD

**Issue by RedWZhang** [BVLC/caffe#6353]
I have generated  traival_lmdb 8.3GB(my own trainset)，but when I computed mean.binaryproto only 1KB without 3 channal mean values.(I have try VOC dataset，the same problem)

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
