### ISSUE TITLE
how to connect caffe with mongodb

### ISSUE THREAD

**Issue by ambl2357** [BVLC/caffe#6357]
i used caffe frame work.

I want connect monngodb and exchange data

What should I do?

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
