### ISSUE TITLE
ModuleNotFoundError: No module named '_caffe' 

### ISSUE THREAD

**Issue by Tomel23** [BVLC/caffe#6368]
### I use anaconda3 to install caffe by comand: conda install caffe in virtual env named : myenv with python 3.6.5
When i try  import caffe  in pytnon interpreter i have error: 

>  import caffe
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/opt/DL/caffe-ibm/python/caffe/__init__.py", line 1, in <module>
>     from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropS olver, AdaDeltaSolver, AdamSolver, NCCL, Timer
>   File "/opt/DL/caffe-ibm/python/caffe/pycaffe.py", line 13, in <module>
>     from _caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
> ModuleNotFoundError: No module named '_caffe
> 

my ~/.bashrc file looks like :
#.bashrc
#Source global definitions
rt PATH="/home/prztszeliga/anaconda3/bin:$PATH"
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

#Uncomment the following line if you don't like systemctl's auto-paging feature:
#export SYSTEMD_PAGER=
#User specific aliases and functions
#added by Anaconda3 installer
export PATH="/home/prztszeliga/anaconda3/bin:$PATH"
export CAFFE_ROOT="/home/prztszeliga/anaconda3/envs/myenv/lib/python3.6/site-packages/caffe"
export PYTHONPATH="anaconda3/envs/myenv/lib/python3.6"

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
