### ISSUE TITLE
fatal error: cublas_v2.h: No such file or directory

### ISSUE THREAD

**Issue by Anonymousaug** [BVLC/caffe#6378]
Error while installing caffe 
fatal error: cublas_v2.h: No such file or directory
 #include <cublas_v2.h>

https://github.com/BVLC/caffe/

* Operating system: 
Ubuntu14.04
32bit

* Python version (python2.7): 

![caffe error](https://user-images.githubusercontent.com/38894104/39493250-a0456130-4dab-11e8-801d-298348fbcf4b.PNG)

Please if anyone have solution to resolve this error....

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
