### ISSUE TITLE
Multi-channel image input

### ISSUE THREAD

**Issue by cqwwww** [BVLC/caffe#6386]
I would like to use a 6-channel image as the input of my network. And the 6-channel image is made by two 3-channel images. But I have no idea how to get these six channels into an image. Does anyone know how to get a 6-channel image or how to input two images together into the network?

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

You could use a HDF database, I think it doesn't limit you to 3 channels. In my early experiments I also made 6-channel images from two 3-channel ones that were concatenated side to side (I sliced and concatenated them in the right order which is a little bit of hassle).

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
