### ISSUE TITLE
install matcaffe

### ISSUE THREAD

**Issue by pengwang123** [BVLC/caffe#6398]
Hi, I have installed the pre-compiled Caffe on Ubuntu, it seems the pre-compiled version doesn't include the matcafee , so how can I install that? still build from  the cafffe source code? in that case, I will have two caffe.
Thanks!

**Comment by CDLuminate** [comment]
matcaffe depends on proprietary (Matlab) hence not provided by the pre-built Ubuntu and Debian package. To use matcaffe, one has to compile it by him/herself.

**Comment by soulslicer** [comment]
matcaffe is a complete disaster. could never make it to work

**Comment by Noiredd** [comment]
Also please consult the [build instructions](http://caffe.berkeleyvision.org/tutorial/interfaces.html) for matcaffe interface.

Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
