### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_92'

### ISSUE THREAD

**Issue by Ceruma** [BVLC/caffe#6408]
CustomBuild:
  Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile_1.dir/layers/Release/cuda_compile_1_generated_absval_
  layer.cu.obj
  nvcc fatal   : Unsupported gpu architecture 'compute_92'
  CMake Error at cuda_compile_1_generated_absval_layer.cu.obj.Release.cmake:219 (message):
    Error generating
    C:/Projects/caffe/build/src/caffe/CMakeFiles/cuda_compile_1.dir/layers/Release/cuda_compile_1_generated_absval_laye
  r.cu.obj

Could any one help me solve the issue?

**Comment by RustyRaptor** [comment]
Getting this as well but with compute_20. I believe this has something to do with the nvcc or cuda version. I don't know where the architecture is defined.

**Comment by RustyRaptor** [comment]
ah found it go to the makefile.conf file and look for CUDA_ARCH. Just set it to whatever your GPU supports. You can find that on a wiki somewhere it usually corresponds to a compute version as in 2.1 will be compute_21 etc

**Comment by RustyRaptor** [comment]
Aha here we go. Just remove all the lines that are on CUDA_ARCH except the one that matches your GPU. Use this to see which one. 
http://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/

**Comment by Noiredd** [comment]
Yes this is related to your CUDA SDK version, @RustyRaptor is giving a good advice.

Closing, assuming the given answer helped. If not, please reopen and provide further details, especially how the suggested solution failed.

**Comment by zchrissirhcz** [comment]
@Noiredd @RustyRaptor @Ceruma By specifying the GPU architecture manually will work, however, it is weird. Since in windows branch, `cmake/Cuda.cmake` already gives code to test GPU's architecture:

```CMake
################################################################################################
# A function for automatic detection of GPUs installed  (if autodetection is enabled)
# Usage:
#   caffe_detect_installed_gpus(out_variable)
function(caffe_detect_installed_gpus out_variable)
  if(NOT CUDA_gpu_detect_output)
    set(__cufile ${PROJECT_BINARY_DIR}/detect_cuda_archs.cu)

    file(WRITE ${__cufile} ""
      "#include <cstdio>\n"
      "int main()\n"
      "{\n"
      "  int count = 0;\n"
      "  if (cudaSuccess != cudaGetDeviceCount(&count)) return -1;\n"
      "  if (count == 0) return -1;\n"
      "  for (int device = 0; device < count; ++device)\n"
      "  {\n"
      "    cudaDeviceProp prop;\n"
      "    if (cudaSuccess == cudaGetDeviceProperties(&prop, device))\n"
      "      std::printf(\"%d.%d \", prop.major, prop.minor);\n"
      "  }\n"
      "  return 0;\n"
      "}\n")

    execute_process(COMMAND "${CUDA_NVCC_EXECUTABLE}" "--run" "${__cufile}"
                    WORKING_DIRECTORY "${PROJECT_BINARY_DIR}/CMakeFiles/"
                    RESULT_VARIABLE __nvcc_res OUTPUT_VARIABLE __nvcc_out
                    ERROR_QUIET OUTPUT_STRIP_TRAILING_WHITESPACE)

    if(__nvcc_res EQUAL 0)
      # nvcc outputs text containing line breaks when building with MSVC.
      # The line below prevents CMake from inserting a variable with line
      # breaks in the cache
      string(REGEX MATCH "([1-9].[0-9])" __nvcc_out "${__nvcc_out}")
      string(REPLACE "2.1" "2.1(2.0)" __nvcc_out "${__nvcc_out}")
      set(CUDA_gpu_detect_output ${__nvcc_out} CACHE INTERNAL "Returned GPU architetures from caffe_detect_gpus tool" FORCE)      
    endif()
  endif()

  if(NOT CUDA_gpu_detect_output)
    message(STATUS "Automatic GPU detection failed. Building for all known architectures.")
    set(${out_variable} ${Caffe_known_gpu_archs} PARENT_SCOPE)
  else()
    set(${out_variable} ${CUDA_gpu_detect_output} PARENT_SCOPE)
  endif()
endfunction()
```
If correctly run that cmake function `caffe_detect_installed_gpus`, a GTX1080Ti GPU will get 6.1 as its architecture, instead of 9.2. But why the wrong architecture is 9.2, instead of other arbitary numbers?

Well, actually, if you're using windows system that do not use English as system language (e.g. Simplified Chinese), that cmake function will firstly match CUDA's version like `9.2` if you're using CUDA 9.2. The root reason is the encoding in files (such as `c:\program files\nvidia gpu computing toolkit\cuda\v9.2\include\crt\math_functions.h` contains the characters that cannot shown in ASCII(936) encoding. Thus, if you run this command:
```bat
d:
git clone https://github.com/BVLC/caffe caffe-BVLC
cd caffe-BVLC
git checkout -b windows origin/windows
.\scripts\build_win.cmd   # will occur the "cuda architecture 9.2 is not OK" error

nvcc .\build\detect_cuda_archs.cu  # try to get cuda arch version in cmd window
```
and you will get warning messages before the expected version info:

>c:\program files\nvidia gpu computing toolkit\cuda\v9.2\include\crt\math_functions.h: warning C4819: >该文件包含不能在当前代码页（936）中表示的字符。请将该文件保存为 Unicode 格式以防数据丢失
>    正在创建库 a.lib 和对象 a.exp
> 6.1

Now the solution is very easy. Just ignore those prepended warning information when do regular expression matching in `Cuda.cmake`'s `caffe_detect_installed_gpus` function's definition, i.e. change:

```cmake
      string(REGEX MATCH "([1-9].[0-9])" __nvcc_out "${__nvcc_out}")
```
to:
```cmake
      string(REGEX MATCH "([1-9].[0-9])$" __nvcc_out "${__nvcc_out}")
```
Note the only difference is the `$` charecter, which ensures matching the number.number appearing in any end of line, and since only cuda arch number match that pattern, it works.

@Noiredd Again, I think we should get to know why a compilation/building problem occurs, instead of just using a trick to ignore that.

**Comment by yanhaiming56** [comment]
I also have the error "nvcc fatal   : Unsupported gpu architecture 'compute_481'".How can resolve the error

**Comment by zchrissirhcz** [comment]
@yanhaiming56 You need to specify your cuda arch dependencies, and in my pasted blog content I've already give the solution. That is:

`cmake/Cuda.cmake`，line 7,  removing `20` and `21` support, since newer cuda don't support them and treat as error. Also adding `52` to support GTX970 card. Thus the updated line is:
```cmake
set(Caffe_known_gpu_archs "30 35 50 52 60 61")
```

`cmake/Cuda.cmake`，around line 40,  specify the nvcc cuda arch version. I use 1080Ti which is 6.1 compute arch version, so changing:
```cmake
      string(REGEX MATCH "([1-9].[0-9])$" __nvcc_out "${__nvcc_out}")
      string(REPLACE "2.1" "2.1(2.0)" __nvcc_out "${__nvcc_out}")
```
to:
```cmake
    set(__nvcc_out "6.1")
```

**Comment by wangruicsu** [comment]
> Aha here we go. Just remove all the lines that are on CUDA_ARCH except the one that matches your GPU. Use this to see which one.
> http://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/
> It appears to have worked for me with sm_60 I have a GTX 1060 6GB so it's pascal arch

it works！

**Comment by ys198918** [comment]
> I also have the error "nvcc fatal : Unsupported gpu architecture 'compute_481'".How can resolve the error

what gpu are you using?
