### ISSUE TITLE
accuracy testing on imagenet validation dataset googlenet

### ISSUE THREAD

**Issue by g-amardeep** [BVLC/caffe#6410]
Im trying to build batches for accuracy testing of googlenet model
I have created the lmdb file and corresponding binaryproto file.

I use the ~/caffe/models/bvlc_googlenet/train_val.prototxt file, update the absolute path to lmdb file in the train_val-prototxt file.

I then use below command to run the caffe test command to generate batches. 
50 per batch x 1000 iterations = 50000 images

 **caffe/build/tools/caffe test -gpu 0 -iterations 1000 -model /home/ubuntu/caffe/models/bvlc_googlenet/train_val.prototxt -weights /home/ubuntu/TensorRT-4.0.0.3/data/googlenet/googlenet.caffemodel**

I use the default  googlenet.caffemodel file in the TensorRT install path as weights (I m assuming its trained for googlenet) .
Below is the snapshot of error i get. 

I suspect it is to with resizing/cropping of the images . Any help is highly appreticated.

**F0529 11:55:49.607640  4262 net.cpp:774] Cannot copy param 0 weights from layer 'loss1/classifier'; shape mismatch.  Source param shape is 20 1024 (20480); target param shape is 1000 1024 (1024000). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.
*** Check failure stack trace: ***
    @     0x7f330c9da5cd  google::LogMessage::Fail()
    @     0x7f330c9dc433  google::LogMessage::SendToLog()**

**Comment by Noiredd** [comment]
When you change an output shape of a layer, dimension of its parameter blob also changes - in this case you changed a FC from 1000 to 20 outputs. Caffe tries to import the parameters from the caffemodel but fails to convert a 1000x1024 blob into 20x1024. Simplest way is to rename the classifier so that Caffe didn't try to import it from the caffemodel.

Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
