### ISSUE TITLE
why batch size affects speed in inference?

### ISSUE THREAD

**Issue by public1024** [BVLC/caffe#6411]
I thought, with gpu, if I test nets with different batch sizes the speed for inference would barely change. However in my experiment, the time for one inference increases as the batchsize increases. There seems to be a linear relationship between them. In my net, I used python layer for data input and included some tested new layers (GPU version). Could anyone give me some hints?

**Comment by Noiredd** [comment]
This is normal. With larger batch size your GPU has more data to process; since it has limited resources, more work means more time taken.

Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
