### ISSUE TITLE
Log layer robustly defined?

### ISSUE THREAD

**Issue by iollmann** [BVLC/caffe#6415]
### Issue summary
Log layer (neuron) does not guard against negative inputs.
Log(x<0) = NaN

Since neuron functions typically follow convolution and/or convolution + batch norm, which will commonly produce negative numbers, it seems that the log layer will produce destructive output most of the time.  Is it well defined?

### Steps to reproduce
code inspection.  Log layer resolves down to MKL vsLN which honors IEEE-754 edge cases for log.

### System configuration
any

**Comment by Noiredd** [comment]
It's on purpose. If you want to clip the inputs to remove negative values, I'd suggest using ReLU first, then Log. Otherwise it would be a waste of resources to have the Log itself check for negatives every single time (especially that when the layer is already running Forward, there's nothing better that could be done aside from just returning a NaN).
