### ISSUE TITLE
train model

### ISSUE THREAD

**Issue by AshleyRoth** [BVLC/caffe#6426]
Hello! Can someone give a link to manual how to train caffe model? Thanks!

* Operating system: Ubuntu 16.04 
* Compiler: GCC 4
* CUDA version (if applicable): 8
* CUDNN version (if applicable): 7.0.5
* BLAS: -
* Python version (if using pycaffe): 3.6.4
* MATLAB version (if using matcaffe): don't use

**Comment by arjun-kava** [comment]
follow link, I had ran my first Dog Cat example using this link,
https://chunml.github.io/ChunML.github.io/project/Training-Your-Own-Data-On-Caffe/

**Comment by AshleyRoth** [comment]
Thanks! I tried train, I get .caffemodel. So, I have second question. How I can test my trained model? Thanks

**Comment by Thomio-Watanabe** [comment]
@AshleyRoth 
The main website has several examples:
http://caffe.berkeleyvision.org

**Comment by Noiredd** [comment]
There's an entire [/examples](https://github.com/BVLC/caffe/tree/master/examples) directory about training and testing models.

Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
