### ISSUE TITLE
how to add L1 regularization for scale factors of bn layer?

### ISSUE THREAD

**Issue by walk2out** [BVLC/caffe#6442]
## Important - read before submitting
Hello, everyone:
    Now, I want to make scale factors of bn layer sparse, so I intend to add L1 regularization for the scale factors. So does anyone know how to write the bn layer in .prototxt but not add loss layer?

Thanks

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
