### ISSUE TITLE
Caffe Tiling with resulting image

### ISSUE THREAD

**Issue by PiyalGeorge** [BVLC/caffe#6448]
I'm detecting objects using the caffemodel created and the movidius stick. Caffemodel is trained with images of 300X300 dimensions. I'm trying to detect objects in video or image. Incase of video, we check frame-by-frame. these frames/images which are in rectangle-form, are checked for objects. First, this rectangular frame/image is resized 300X300, to a square frame/image. then this square-shaped frame/image is checked for objects. But when performing this action,  accuracy is less. So inorder to overcome, i did this:-
Assume our rectangular frame/image having width=533 height=300. now instead of resizing the whole image to 300X300, i cropped the image. The current image was divided into two pieces, where first image is cropped (0,0,300,300) and second image is cropped (233, 0, 533, 300) of current image. Now each image is checked for objects. this will get you right objects, since no resizing is done. But once detection is done in each piece, next we have to merge each pieces. At this time, duplication of objects can/will come. So how to overcome this?

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
