### ISSUE TITLE
Crop a feauture map into multiple bounding boxes?

### ISSUE THREAD

**Issue by soulslicer** [BVLC/caffe#6452]
Is there any layer that allows you to pass in say [M, N, x1, y1, x2, y2] and a feature map, and get a bunch of cropped bounding boxes?

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
