### ISSUE TITLE
Unable to find right labeled dataset to use this model

### ISSUE THREAD

**Issue by pg1647** [BVLC/caffe#6475]
### Issue summary

 I could not find the dataset with labels that correspond to order of labels as the outputs of the network . The original IMAGENET dataset has a different mapping of class numbers than the one used here. 

Can you point me to a source where I can find the dataset with labels that match the outputs of this AlexNet implementation ? Or could you share on what data is this model pre-trained? It will be really helpful.

### Issue checklist

- [x] read the guidelines and removed the first paragraph
- [x] written a short summary and detailed steps to reproduce
- [x] explained how solutions to related problems failed (tick if found none)
- [ ] filled system configuration
- [ ] attached relevant logs/config files (tick if not applicable)

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
