### ISSUE TITLE
Remove some unnecessary codes in classification.cpp

### ISSUE THREAD

**Issue by GarryLau** [BVLC/caffe#6478]
## Important - read before submitting

*Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue!*

*Please do not post installation, build, usage, or modeling questions, or other requests for help to Issues.*
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead.
This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

### Issue summary
In the file: "caffe\examples\cpp_classification\classification.cpp" there are some unnecessary codes.
Codes between L151 and L155 are unnecessary:
```C++
  Blob<float>* input_layer = net_->input_blobs()[0];
  input_layer->Reshape(1, num_channels_,
                       input_geometry_.height, input_geometry_.width);
  /* Forward dimension change to all layers. */
  net_->Reshape();
```

### Steps to reproduce
Comment the codes will be OK, you can also get the right results.

### Tried solutions
Comment the codes between L151 and L155.

### System configuration
Actually, it does not matter with System configuration.
* Operating system: Ubuntu 16.04
* Compiler: GCC\G++
* CUDA version (if applicable): 9.0
* CUDNN version (if applicable): 7.0
* BLAS: OpenBlas
* Python version (if using pycaffe): 2.7
* MATLAB version (if using matcaffe): no

### Issue checklist

- [ ] read the guidelines and removed the first paragraph
- [ ] written a short summary and detailed steps to reproduce
- [ ] explained how solutions to related problems failed (tick if found none)
- [ ] filled system configuration
- [ ] attached relevant logs/config files (tick if not applicable)

**Comment by Noiredd** [comment]
Thank you for your interest. Please note that this is but a simple example, mostly for educational purposes rather than high-performance inference. Maybe those lines could be removed, or maybe they would be *but only in your case* - I don't know that off the top of my head. But I think they should stay, if only as a good practice example (you should check whether the image you want to classify fits in your network).

I will close this issue for now. If you feel like this deserves more attention - please open a PR and start a discussion there.
