### ISSUE TITLE
[caffe-users list] How to use Caffe2 pre-trained models in Caffe??

### ISSUE THREAD

**Issue by passionguan** [BVLC/caffe#6484]
Dear All,

How can we use Caffe2 pre-trained models in Caffe?? It looks like Caffe2 is more like a different deep learning framework to Caffe. Does anyone try using Caffe2 pre-trained models in Caffe??

Thanks!

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
