### ISSUE TITLE
Creating Graph (blob) file with caffemodel and prototxt files 

### ISSUE THREAD

**Issue by negarl** [BVLC/caffe#6492]
How can I create a graph (blob) with the caffemodel and prototxt files? I want to use pre-trained data from openpose and use it as an argument for one of the Movidius Neural Compute Stick functions.

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
