### ISSUE TITLE
deploy.prototxt not found

### ISSUE THREAD

**Issue by jassonjackson** [BVLC/caffe#6493]
jason@jason-virtual-machine:~/caffe$ sh examples/myfile4/demo.sh
F0809 17:07:25.670375 48850 io.cpp:36] Check failed: fd != -1 (-1 vs. -1) File not found: examples/myfile4/deploy.prototxt
*** Check failure stack trace: ***
    @     0x7f5927d6e5cd  google::LogMessage::Fail()
    @     0x7f5927d70433  google::LogMessage::SendToLog()
    @     0x7f5927d6e15b  google::LogMessage::Flush()
    @     0x7f5927d70e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f5928266138  caffe::ReadProtoFromTextFile()
    @     0x7f59282624e6  caffe::ReadNetParamsFromTextFileOrDie()
    @     0x7f5928119642  caffe::Net<>::Net()
    @           0x407fcb  Classifier::Classifier()
    @           0x404203  main
    @     0x7f592671f830  __libc_start_main
    @           0x4046f9  _start
    @              (nil)  (unknown)
Aborted (core dumped)
who can tell me how to solve this problem ?thank you !!

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
