### ISSUE TITLE
E: You must put some 'source' URIs in your sources.list

### ISSUE THREAD

**Issue by ucasiggcas** [BVLC/caffe#6502]
I refer the website http://caffe.berkeleyvision.org/install_apt.html
first 
sudo apt install caffe-cuda
second
sudo apt build-dep caffe-cuda
and up the error：
E: You must put some 'source' URIs in your sources.list
what does it mean ？
Don't know how to deal it, help !!

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request. Specifically, remember to write down your machine details.  
Also, look up what this error means. There are lots of answers on various websites, try some of them first. If it still persists - then make a post with details of the failure.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md

**Comment by ucasiggcas** [comment]
rubbish
