### ISSUE TITLE
i train a 6channels input (6*32*32) model and then i want to classify a new data(6*32*32 numpy) use python

### ISSUE THREAD

**Issue by qq286838947** [BVLC/caffe#6511]
i want to convert the （6,32,32） data to blobs but when i run transformer.perprocess : 
net.blobs['data'].data[...] = transformer.perprocess('data',in)
ValueError:could not broadcast input array from shape (32,32,32) into shape (1,6,32,32)  
i print the in.shape    out (6,32,32)  
it confuse me

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md

**Comment by qq286838947** [comment]
errors:
numpy size :  (4, 32, 32)
Traceback (most recent call last):
  File "detect_mulichannels.py", line 146, in <module>
    test(my_project_root, deploy_proto,line)
  File "detect_mulichannels.py", line 117, in test
    net.blobs['Data1'].data[...] = transformer.preprocess('Data1',im)     
ValueError: could not broadcast input array from shape (32,32,32) into shape (1,4,32,32)


my code : 		
                print "numpy size : " ,im.shape
		net.blobs['Data1'].data[...] = transformer.preprocess('Data1',im)

maybe i must to use the :  
      transformer.set_channel_swap('Data1', (0,1,2,3))????
