### ISSUE TITLE
How to know the label meaning of BVLC_ALEXNET.caffemodel

### ISSUE THREAD

**Issue by Frankzhangnxp** [BVLC/caffe#6521]
## Important - read before submitting

*Please read the [guidelines for contributing](https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md) before submitting this issue!*

*Please do not post installation, build, usage, or modeling questions, or other requests for help to Issues.*
Use the [caffe-users list](https://groups.google.com/forum/#!forum/caffe-users) instead.
This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe.

### Issue summary
Hi ALL, 
     We are running the Alexnet validation code in ARM compute library. It use bvlc_alexnet.caffemodel , so I download the caffe model from http://dl.caffe.berkeleyvision.org/bvlc_alexnet.caffemodel. We generate a "cat" to this model, and the expected labels result is 281, but our label result is 669. I don't know if the label 281 is cat, and what the label 669 mean. 

### System configuration

* Operating system:     Yocto Linux
* Compiler:       Yocto toolchain
* CUDA version (if applicable): no
* CUDNN version (if applicable): no
* BLAS: 
* Python version (if using pycaffe): 
* MATLAB version (if using matcaffe): 

### Issue checklist

- [ ] read the guidelines and removed the first paragraph
- [ ] written a short summary and detailed steps to reproduce
- [ ] explained how solutions to related problems failed (tick if found none)
- [ ] filled system configuration
- [ ] attached relevant logs/config files (tick if not applicable)

**Comment by Frankzhangnxp** [comment]
@shelhamer 
Hi Shelhamer,
     The model (http://dl.caffe.berkeleyvision.org/bvlc_alexnet.caffemodel) is made by you. Could you please tell me the label meaning or do you have the mapping file for this model? Thank you

Best Regards,
Frank

**Comment by Noiredd** [comment]
This model has been trained on ImageNet, you should look up the ImageNet label mapping.

Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
