### ISSUE TITLE
The question of backward pass  from bachnorm layer

### ISSUE THREAD

**Issue by lusenkong** [BVLC/caffe#6522]
I have saw this formula in batch_norm_layer.cpp file,

// if Y = (X-mean(X))/(sqrt(var(X)+eps)), then
  // **dE(Y)/dX =(dE/dY - mean(dE/dY) - mean(dE/dY \cdot Y) \cdot Y)./ sqrt(var(X) + eps)**

what is the second line really means ??

**Comment by Noiredd** [comment]
Please post usage, installation, or modeling questions, or other requests for help to the [caffe-users list][1] instead of Issues. This helps developers maintain a clear, uncluttered, and efficient view of the state of Caffe. Please read the [guidelines for contributing][2] before submitting an issue or a pull request.

 [1]: https://groups.google.com/forum/#!forum/caffe-users
 [2]: https://github.com/BVLC/caffe/blob/master/CONTRIBUTING.md
