### ISSUE TITLE
Multi-GPU operation and data / model Parallelism

### ISSUE THREAD

**Issue by shelhamer** [BVLC/caffe#876]
Multi-GPU operation and data / model / hybrid parallelism are planned and in development for Caffe. The purpose of the thread is to focus the conversation, since this has been asked here, there, and everywhere. There are several ways to approach parallelization, so feel free to discuss your own work to this end here.

Note that Caffe does work with multiple GPUs in a standalone fashion right now: you can train on one GPU while extracting features on another and so on.

**Comment by naibaf7** [comment]
For forward processing, I'm currently trying to implement SplitNet, which adds the possibility to split up a network DAG on multiple devices and process the network forwarding asynchronously across multiple devices.
This is necessary because our dense labeling network (for microscopy images) does not fit well into the memory of one GPU anymore.

**Comment by futurely** [comment]
While #2114 and a series of related PRs https://github.com/BVLC/caffe/issues/1535#issuecomment-117018020 have solved the data parallelism, there isn't yet a pull request for model parallelism. [Here](https://github.com/facebook/fbcunn/blob/master/fbcunn/ModelParallel.lua) is Facebook's implementation just for reference.

**Comment by PhoenixDai** [comment]
Looks like Nvidia has figured out how to train model on Caffe with multiple GPUs. This page https://developer.nvidia.com/digits showed performance comparison on training with different number of GPUs. In the video on the page, it showed how to use multiple GPUs with DIGITS. Is there any plan to have this feature in Caffe?

**Comment by choosehappy** [comment]
@PhoenixDai 's comment is related to the digits github issue: https://github.com/NVIDIA/DIGITS/issues/92. It seems they have forked their own caffe version which supports multiple gpus?

**Comment by thatguymike** [comment]
The Nvidia branch uses #2114

**Comment by shaibagon** [comment]
Linking to SO [related question](http://stackoverflow.com/q/33726333/1714410).

**Comment by futurely** [comment]
The master branch supports multi-GPU training. Please refer to the latest documents.
https://github.com/BVLC/caffe/blob/master/docs/multigpu.md
https://github.com/BVLC/caffe/blob/master/docs/tutorial/interfaces.md

**Comment by xiaoxiongli** [comment]
thank you for your great job!   Now I am training googlenet in my K80, as you know , K80 has 2 core, and I enable these 2 core by "-gpu 0,1", the training speed is faster! 
    I know the cuda-convnet2 using the method introduced by "Alex Krizhevsky. One weird trick for parallelizing convolutional neural networks.",  Is that the mothod caffe using for Multi-GPU Parallelism?

**Comment by tuonion** [comment]
Hi ,@shelhamer.  

Does Caffe support  'model / hybrid parallelism'  as you mentioned above?

**Comment by Lisandro79** [comment]
Hi,
I am working on a project that requires the use of 4 GPUs on a server to analyze images. I would like to do it in caffe (I prefer it over torch or tensorflow) but it seems that multiple GPU is still not available for test / inference.

Is there any estimated date for a version update of caffe that will allow using multiple GPUs for test / inference? 

Thanks a lot

**Comment by cypof** [comment]
We don't have a plan to add that right now but I would be happy to help.
You can split your dataset and test each part independently, or distribute
items to multiple nets as you go. Are you using the Python API?

**Comment by Lisandro79** [comment]
Hi Cypof, 

Thanks for your fast response. I am not sure I completely understand your suggestions. Let me first provide you with more details about the task.

We have a web server that receives requests (image files) from users. This server has a queue of requests at any given time. Our workstation has 4 TitanX GPUS within a motherboard. So I need to use the 4 GPUs to speed up (four times) the processing time of my queue. The requests will be handled as follows:

request 1 GPU:0; 
request 2 GPU:1; 
request 3 GPU:2; 
request 4 GPU:3; 
request 5 GPU:0; 
request 6 GPU:1; 
...

I am using caffe with the Python API. The problem comes with the selection of the GPU. If I select GPU= 0 with the first request of the queue

caffe.set_mode_gpu()
caffe.set_device(0)
# run inference

then I cannot select GPU=1 with the next request. Even If I load the caffe model and a model in torch, torch cannot use GPU=1 after caffe has set the device to '0' because caffe "locks" all other GPUs. 

So regarding your suggestions

1- "You can split your dataset and test each part independently".
I think this solution does not apply to this case (please correct me if I am wrong)

2-  "Distribute items to multiple nets as you go"
Is this similar to what I described above (using one network in caffe and another network in torch in different GPUS) but with multiple nets in caffe? Could you please elaborate a bit more on this? 

Thank you very much for you help

**Comment by pythonanonuser** [comment]
@Lisandro79 did you figure out a solution to this issue? I have a similar problem

**Comment by Lisandro79** [comment]
Hi @pythonanonuser,

Unfortunately, I have to say that my solution will be to use TensorFlow. I could not find a solution to my problem in Caffe.

In my opinion, the lack of parallelism for testing of Caffe is a major disadvantage for deployment of web applications. I would like to know what other members of the Caffe community have to say about this. 

I really like Caffe and I would prefer to use it over other libraries, but at the moment I find that the parallel capabilities of Tensorflow plus the use of tensorboard do make a difference for production.

Best

**Comment by cypof** [comment]
I meant to prototype something but haven't got to it. I think the easiest way would be to use multiprocessing, either a Queue, and one Process per GPU, or maybe a Pool so that you can call map() on your inputs and directly get your ouputs. It also depends on where you want to store the results etc.

**Comment by shelhamer** [comment]
Closing as NCCL + pycaffe #4563 is an effective approach to data parallel training of any kind of Caffe net. More involved forms of parallelism can be left to further efforts.
