### ISSUE TITLE
boost::python vs. cython and Python interface preprocessing profiling and improvement

### ISSUE THREAD

**Issue by kloudkl** [BVLC/caffe#941]
Boost.Python is too slow for a practical application system. It takes several hours to extract features for only ten thousand images using the current pycaffe interface. There shouldn't be such a huge performance gap between the C++ version and the other languages. According to some benchmark results, Cython can be much faster than Boost.Python. It Caffe wants the users to frequently use the concise Python interface in their daily experiments, the binding technology should be changed to Cython.

Simple benchmark between Cython and Boost.Python
http://blog.chrischou.org/2010/02/28/simple-benchmark-between-cython-and-boost-python/

C++ wrapper benchmark: Cython, PyBindGen, Boost
https://groups.google.com/forum/#!topic/cython-users/lQO9lGj5JEc

[Stackless] [C++-sig] [Boost] Trouble optimizing Boost.Python   integration for game development (it seems too slow)
http://www.stackless.com/pipermail/stackless/2009-August/004249.html

Python vs. Cython vs. D (PyD) vs. C++ (SWIG)
http://prabhuramachandran.blogspot.com/2008/09/python-vs-cython-vs-d-pyd-vs-c-swig.html

https://github.com/cython/cython/wiki/SWIG

**Comment by alfredox10** [comment]
I'm trying to implement an object detection python program that uses Caffe, and I'm trying to make it faster but I have not found any information on how to make it compatible with PyPy. Does anyone know how to achieve this?

**Comment by SlimeQ** [comment]
bruh. it's just not compatible. if you're looking for speed, writing custom C++ functions and adding them to the wrapper is probably your best bet.

i'm really not trying to be dismissive here, i just spent a lot of time looking into pypy/caffe last week only to find that it's more complicated than it's worth. if you can find a way to pass data to caffe without using numpy, you might be able to get something going, but i'm not totally sure how that'd be done.

**Comment by alfredox10** [comment]
Hey Slime! lol

I can pass the data to caffe without using numpy, but you said caffe isn't compatible with pypy either, so I'm not sure that would help though?

**Comment by SlimeQ** [comment]
nah, you're thinking pycaffe. caffe is c++, it doesn't even know that pypy exists. the problem is that caffe needs a contiguous array of floats, and python lists are basically arrays of pointers to floats (or more accurately, [pointers to doubles](https://docs.python.org/3/faq/design.html)) so they need to be converted to contiguous memory to be operated on efficiently. typically numpy is used for this, but numPyPy is still in development and as such it is [missing some functionality](http://buildbot.pypy.org/numpy-status/latest.html). 

you can certainly [try the latest numPyPy implementation](https://bitbucket.org/pypy/numpy) but there's no guarantee that it will be faster or even work at all. that being said, please do let us know how that goes as i'm sure there are a lot of people around here wanting more speed out of caffe without getting down and dirty with C++.

in any case, this probably isn't the proper thread to discuss numPyPy ;)
